### ISSUE TITLE
a sample with OAuth2Configuration

### ISSUE THREAD

**Issue by sadeghhp** [IdentityServer/Thinktecture.IdentityServer3#1002]
Hi, Could you please make a sample with OAuth2Configuration for identityManager and identityServer for SecurityMode of SecurityMode.OAuth2 ?

**Comment by danvanderboom** [comment]
I'm looking for the same information. I got some of this set up, and it works locally. When it runs in an Azure website, however, I can navigate to the identity manager page and log in, but the menu is missing. Are there specific claims or roles needed for Identity Manager to reveal more functionality when run remotely?

**Comment by brockallen** [comment]
The IdentityManager repo already has this configured in the sample hosting app.
