### ISSUE TITLE
After Consent Screen  request is going from client application  to server continously

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#1003]
Submit the Form continously from client to server(Idsrv3)

![image](https://cloud.githubusercontent.com/assets/10266752/6426243/f535ba1c-bf76-11e4-9c59-3fc83a1f9c05.png)

**Comment by RajMondaz** [comment]
I am using https for (Idsrv3) while return back to client  i am return to http                                                      i am getting error below image:-                                                                                                                                   
![image](https://cloud.githubusercontent.com/assets/10266752/6426308/65b50baa-bf7a-11e4-8964-7ae82ffac8af.png)

**Comment by brockallen** [comment]
Right -- the error is telling you to use https for the client app as well.

**Comment by RajMondaz** [comment]
is that it is mandatory to use HTTPS  or we can use HTTP also.  because previously i am running with different client that is running with HTTP now it is not working.                                                                               Then what is the Solution for this Problem. whether we can make some changes in the web.config then it will work or some any changes we have make in client or server.

**Comment by brockallen** [comment]
During dev it's safe to use HTTP, but for production your clients and your token service should use HTTPS.

**Comment by mschulz531** [comment]
I've seen a similar situation...I am doing the same thing...the client app is using http and the identity server is using https.  The app was continuously redirecting and eventually a 400 Server Error was returned.  During my debugging of this issue, I tried various solutions.  At one point I changed the default route of the app to a controller page that did not have the [Authorize] attribute.  When I hit this page first, then browsed to a page with the [Authorize] attribute specified, it worked correctly.  Using Fiddler, I discovered that the only difference between the two session traces was the setting of the ASP.NET_SessionId cookie.  The redirect loop does not happen if the ASP.NET_SessionId cookie is set before authenticating with openid/identityserver.  Not liking that solution, I started to add debug code in my application.  To make a long story short, I discovered that if I added a Session_Start() method to my global.asax.cs file, the ASP.NET_SessionId cookie is set correctly in BOTH scenarios as described above.  I don't fully understand why this change fixes the problem other than to assume that hooking into the Session_Start method causes the session cookie to be initialized correctly.

I have fiddler trace logs to show the good and bad scenarios if anyone is interested.
I would be interested in hearing any theories to what is happening here.

Note: I do plan on forcing the app use HTTPS but that has not been configured yet.

**Comment by coreyperkins** [comment]
I'm seeing the same thing, it's quite easy to recreate in my setup. I fire up my project, log in once, clear my browser's history, then try to login again. Nasty loop starts and never ends...

**Comment by mschulz531** [comment]
the fix is very simple...have you tried it?

**Comment by coreyperkins** [comment]
mschulz531, it appears to have worked for me as well, at least in my dev environment. I am going to deploy to a staging environment soon to see if it worked there as well.

I did what you said and added an empty Session_Start() to my Global.asax.

        protected void Session_Start()
        {
        }

**Comment by coreyperkins** [comment]
This also worked in my testing environment. I will be glad to post traces/logs/etc if they will be of use.

Thanks!

**Comment by bcbeatty** [comment]
Thanks! This fixed worked. I've been fighting this for days.
I had two projects with the same Startup.Auth.cs, with different redirectUri.
One project would work as expected, the other would be caught in an endless loop.
I added the Session_Start method and this fixed the endless loop.

I'm still getting an issue with RequestAuthorizationCodeAsync always returning false.

**Comment by mschulz531** [comment]
No problem Brian, you still with Sogeti?

**Comment by bcbeatty** [comment]
No I left there in June. I'm at Magenic
