### ISSUE TITLE
CookieSecure in CookieOptions

### ISSUE THREAD

**Issue by gabi-radu** [IdentityServer/Thinktecture.IdentityServer3#1005]
Hi,

We use IdSrv behind a load balancer, so we have set the EnableSSL flag to false and all works fine, except that the Cookies IdSrv uses are not set secure.

There is an IdentityServerOptions.AuthenticationOptions.CookieOptions objects used to set various cookie options for the three (primary, external and partial) IdSrv cookies, but this doesn't include a CookieSecure option so the default is always used. Being behind a load balancer, the cookies will not be secure. 

It would be nice to have a CookieSecure option added so that if we want the load balancer to add SSL and still use secure cookies, we could just set to Always.

Thanks.

**Comment by brockallen** [comment]
Does your load balancer properly ignore the secure flag in order to pass them along to IdSvr's HTTP (non-SSL) endpoints?

**Comment by gabi-radu** [comment]
Hi,

Yes it does already using CookieSecure = Always on the client MVC
application hosted in the same environment.

Thanks

**Comment by brockallen** [comment]
Well, what I mean is that a load balancer must deliberately ignore the HTTP spec in order to pass along a cookie that's marked as secure.

**Comment by gabi-radu** [comment]
Yeah that is exactly whats happening. The problem is there is no way of
specifying IdSrv to configure the cookies as secure, that I could see.
Perhaps adding an extra property in CookieOptions and using it in the
ConfigureCookieAuth app builder extension class.

**Comment by brockallen** [comment]
Something like this:

https://github.com/IdentityServer/Thinktecture.IdentityServer3/commit/ae2d7402364e3e053000f5c526678768a3eb77d7

**Comment by gabi-radu** [comment]
Yes this is exactly what I had in mind. Thank you, much appreciated.
