### ISSUE TITLE
Can't load controllers external to Core

### ISSUE THREAD

**Issue by LavaFields** [IdentityServer/Thinktecture.IdentityServer3#1006]
I see this restriction was recently added here: https://github.com/IdentityServer/Thinktecture.IdentityServer3/commit/da685dfd3fd4937396c1191830cfc50a4ef634a6.

The company I work for has a requirement that services support a health check API. I would like for my externally defined controller to be discovered and registered in the same "app" as IdentityServer, rather than having to define another WebApi registration on a separate port.

**Comment by brockallen** [comment]
Why not provide an endpoint in the OWIN pipeline?

**Comment by leastprivilege** [comment]
Nothing stops you adding additional endpoints to your app (either via OWIN or a separate Web API host). You just can't add controller to **our** host.

**Comment by LavaFields** [comment]
Thanks! I'm new to OWIN and WebAPI and wasn't aware of their full capabilities. I've got it working now.
