### ISSUE TITLE
Purpose of Port 44321

### ISSUE THREAD

**Issue by lennane** [IdentityServer/Thinktecture.IdentityServer3#1007]
I have most of MVC Authentication Sample running on my server at https://www.t3xfer.com using SSL port 443 on Windows Server 2008. user can be "bob" or "jpl7" both with password "secret".
However I dont know how to set up the CallApi port so that port 44321 isn't necessary. I was thinking a regular RESTful URI could do it.

Neither of the following work with the port 44321 open. The first is direct from the sample.

        private async Task<string> CallApi(string token)
        {
            var client = new HttpClient();
            client.SetBearerToken(token);

            var json = await client.GetStringAsync("https://localhost:44321/identity");
            return JArray.Parse(json).ToString();
       }

---------------------------------------------------------------------
			
	private async Task<string> CallApi(string token)
        {
            var client = new HttpClient();
            client.SetBearerToken(token);

            var json = await client.GetStringAsync("https://www.t3xfer.com:44321/identity");
            return JArray.Parse(json).ToString();
        }

Thanks,

Jim

**Comment by brockallen** [comment]
I'm confused -- where is port 44321 configured? If it's in any of our samples, then it's just a coincidence and has no meaning.

**Comment by lennane** [comment]
It inside the MVC Authentication Sample inside the Controllers folder inside the program CallApiController.cs
All other port numbers in the samples are :44319
My goal was to replace https://localhost:port  with https://www.t3xfer.com and the implied port 443
Sorry I didnt provide the exact code section

**Comment by lennane** [comment]
It inside the MVC Authentication Sample inside the Controllers folder inside the program CallApiController.cs
All other port numbers in the samples are :44319
My goal was to replace https://localhost:port  with https://www.t3xfer.com and the implied port 443
Sorry I didnt provide the exact code section

**Comment by brockallen** [comment]
Well, so again, I think whatever port is being used is a coincidence.
