### ISSUE TITLE
Multi-Tenant - Tenant for Logout, LoggedOut, Consent, ClientPermissions, and Error?

### ISSUE THREAD

**Issue by eromanowski** [IdentityServer/Thinktecture.IdentityServer3#1008]
I'm trying to figure out how to get a customer logo to change based on the tenant across all the Views. 

I'm working based off the CustomViewService example. 

I see the tenant gets passed in on Login (thru SignInMessage), but is there a way get the tenant  on Logout, LoggedOut, Consent, ClientPermissions, and Error? My goal is to maintain the customer branding across all those views.

**Comment by brockallen** [comment]
On Login, this is easy since the SignInMessage is passed (which has the tenant). But for the others, it's difficult since the context can't always be known.

**Comment by eromanowski** [comment]
My only option at this point sounds like I should leave those Views unbranded then? The only out-of-box solution I can see is to use a separate Client for each customer that needs branding. But my co-worker brought up concerns that this will make securing the API much more challenging.

**Comment by leastprivilege** [comment]
As Brock said - many of the view are not tenant specific - so if you want branding - you need separate instances - or you come up with an alternative way of setting the tenant (custom http parameters, IP address etc).

**Comment by eromanowski** [comment]
Thanks guys for the feedback. I just wanted to make sure there wasn't something easy I was missing.
