### ISSUE TITLE
Safari on Mac and iOS download endsessioncallback on loggedOut page

### ISSUE THREAD

**Issue by Nicholi** [IdentityServer/Thinktecture.IdentityServer3#1009]
For some reason when the iframe on loggedOut.html is hit the browser downloads endsessioncallback. I've noticed this on Safari 8.0.2 and on an iOS 8 iPhone/iPad.

I know there are a ton of weird quirks with Safari and iframes...guessing it may be related to that? Or that the iframe is display:none? I already tried switching to visibility:hidden but that didn't make a difference. Am going to just let the iframe be visible and see if that changes it at all maybe.

**Comment by leastprivilege** [comment]
Heard that one before. If you have a solution - let us know. Gonna start tracking that.

**Comment by Nicholi** [comment]
It seems the problem is that the endsessioncallback request has no Content-Type header and in the all-knowing wisdom of the Safari devs instead of trying to handle the response as html it just downloads it. Sort of makes sense, since no content-type is specified for the response...but since no other browser does it like this seems like bad precedent on their part.

I tested by just creating a plain html page with an external iframe request (but on the same webserver). This works fine as expected in Safari. Then with some PHP finangling (because I'm lazy) I made sure the iframe response had EXACTLY the same http headers as would be seen in an IdentityServer3 endsessioncallback request, as well as an empty response (Content-Length: 0). This finally triggered the download behavior in Safari. Switching just the Content-Type back to something Safari likely sees as "displayable" allows the iframe to be embedded as expected with no download. What Safari considers "displayable" I have no idea, but both "text/plain" and "text/html" work fine it seems. As long as it is switched to either of those the bug should be no more.

Haven't actually tested this, but all you should need to do is change to
```
        public HttpResponseMessage LogoutCallback()
        {
            Logger.Info("End session callback requested");

            return new HttpResponseMessage(HttpStatusCode.OK)
                {
                    Content = new StringContent(String.Empty, Encoding.UTF8, "text/plain")
                };
        }
```

**Comment by brockallen** [comment]
Do you know if a Content-Type of text/plain will also trigger a download? IOW, I'm wondering if using text/html would be any better.

**Comment by brockallen** [comment]
Anyway -- We added text/html to dev -- please test it and let us know. Thx.

**Comment by Nicholi** [comment]
Yeah tested a build from dev, that works.

**Comment by brockallen** [comment]
Thanks!

**Comment by bjarkeorama** [comment]
We are using Thinktecture.IdentityServer3 1.2.1 is it possible to do a workaround or is the only option to update?

Regards

**Comment by brockallen** [comment]
As of now we only made this fix on the dev branch.
