### ISSUE TITLE
Loggin in after account verification.

### ISSUE THREAD

**Issue by mwereda** [IdentityServer/Thinktecture.IdentityServer3#1012]
In project I'm working on we use IdentityServer which is identity server for lots of clients (mostly websites)
I have such problem:
1. User creates account using registration page that's within website X. 
2. After registration verification email is being sent.
3. When clicking verification email user should be automaticaly logged in with IdentityServer.

Is it possible to perform step 3 using IdentityServer? If yes - could you give me some hints on how to do that?

**Comment by brockallen** [comment]
Essentially a dup of #930

**Comment by brockallen** [comment]
IssueLoginCookie API added to dev. Please try it out and let us know if it helps.
