### ISSUE TITLE
identity server with resource server  works on iis express but not in iis

### ISSUE THREAD

**Issue by yon86** [IdentityServer/Thinktecture.IdentityServer3#1013]
i hosted the project as per the instructions and works from visual studio iis express but when I host in on iis its not working I always get 401 unauthorized error even though it was authorized on iis express. I maybe missing something basic when hosting on iis. thanks for the help

**Comment by mschulz531** [comment]
you have to setup SSL in IIS - settings that you made for IIS Express do not carry over to IIS.

**Comment by yon86** [comment]
I have setup ssl in iis I get the token fine from iis its when I hit the resource server I see 401 all the time. I am using self signed iis certificate

**Comment by brockallen** [comment]
You need to figure out how to get SSL working properly in IIS. There's a PS video that shows this in the Web API course.

**Comment by yon86** [comment]
thank you very much it works now

**Comment by vargamat** [comment]
Sorry I know this is an old thread but I have the same problem can you give me the link to that PS video?
