### ISSUE TITLE
Login form Loop - Implicit Flow

### ISSUE THREAD

**Issue by rdewor** [IdentityServer/Thinktecture.IdentityServer3#1014]
We have implemented an identity server utilizing entitity framework in order to store data in sql databases and a client based on angular js with implicit flow as grant.

Everytime we try to login to the server after it has been started we are stuck loading the login form. It appears as if the browser is trying to load the page, while the network request has long finished. After many reloads the form eventually appears and we can login to the server.

Any idea what might cause this problem?

**Comment by bcbeatty** [comment]
I'm getting a similar issue with Hybrid mode

**Comment by bcbeatty** [comment]
See if  adding an empty Session_Start will fix it

`protected void Session_Start()
`{}

[issue 1003](https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/1003)

**Comment by djcameron** [comment]
We have this same problem using Implicit Flow and MVC
