### ISSUE TITLE
Identity Server V3 for Securing WCF Service?

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/Thinktecture.IdentityServer3#1015]
Hello,

We have already configured identity server 3 for our Rest Services and we will go further this approach.
Now we have quite a lot of "old" WCF Soap Services. They are currently using kind of WsTrust SamlTokens, but not properly implemented.

Can we use identity server3 to secure whose WCF Services? Is there a plugin for IDserver3?

Thank you very much

**Comment by leastprivilege** [comment]
Well - WCF can consume JWT tokens - so the token acquisition part would be the same.

There are some modifications to WCF and custom code necessary to send/consume the tokens.

**Comment by davidmrichter** [comment]
Is there any sample or Blog entry available which I could somehow follow?

**Comment by leastprivilege** [comment]
I don't have anything handy. It is around the usage of ChannelFactory<T>.CreateChannelWithIssuedToken and the WCF service accepting JWT tokens.

**Comment by leastprivilege** [comment]
I finally got some time to look into that and got it working - will post a sample soon.

**Comment by tannhattnt** [comment]
Hi Dominick, do you have a sample about IdentityServer V3 and WCF integration yet?

**Comment by leastprivilege** [comment]
http://leastprivilege.com/2015/07/02/give-your-wcf-security-architecture-a-makeover-with-identityserver3/

**Comment by tannhattnt** [comment]
super! vielen Dank!

**Comment by tannhattnt** [comment]
Hi Dominick, again, I can get Access Token by using GetJwt() in your WCF Service security example, but I want a bit more. Now, with this Access Token or Username & Password, how can i get user credential or Claims ?

Btw, in your example, it is a Self-hosted WCF service. I try this way and it works quite well. But with my WCF services, which are hosted on IIS. I try to configure like your self-hosted example(binding, service credential... in web.config) but it does not work, it always reports an Exception about the endpoint address is not correct, and remote server return 404. 

this is a part of web.config file:
<system.identityModel>
    <identityConfiguration name="identity" >
      <securityTokenHandlers>
        <clear/>
        <add type="Namespace.IdentityServerWrappedJwtHandler, Namespace, Version=1.0.0.0, Culture=neutral"></add>
      </securityTokenHandlers>
      <claimsAuthorizationManager type="Namespace.RequireAuthenticationAuthorizationManager, Namespace, Version=1.0.0.0, Culture=neutral"/>
    </identityConfiguration>
  </system.identityModel>
  <system.serviceModel>
    <services>
      <service name="Service.Service1">
        <host>
          <baseAddresses>
            <add baseAddress="https://myservice" />
          </baseAddresses>
        </host>
        <endpoint address="/Service1.svc"
                  binding="ws2007FederationHttpBinding"
                  bindingConfiguration="service-binding"
                  contract="Service.IService1" />
        <endpoint address="mex" binding="mexHttpsBinding" contract="IMetadataExchange"/>
      </service>
    </services>
    <behaviors>
      <serviceBehaviors>
        <behavior>
          <serviceMetadata httpsGetEnabled="true" />
          <serviceDebug includeExceptionDetailInFaults="true" />

          <serviceCredentials useIdentityConfiguration="true" identityConfiguration="identity">
            <serviceCertificate findValue="*.myservices" storeLocation="LocalMachine" storeName="My" x509FindType="FindBySubjectName"/>
          </serviceCredentials>
          <serviceAuthorization principalPermissionMode="Always"></serviceAuthorization>
        </behavior>
      </serviceBehaviors>
    </behaviors>
    <bindings>
      <ws2007FederationHttpBinding>
        <binding name="service-binding" maxReceivedMessageSize="20000000">
          <security mode="TransportWithMessageCredential">
            <message issuedKeyType="BearerKey" establishSecurityContext="false"></message>
          </security>
        </binding>
      </ws2007FederationHttpBinding>
      <basicHttpBinding>
        <binding name="service-basic" maxReceivedMessageSize="20000000">
          <security mode="None"></security>
        </binding>
      </basicHttpBinding>
    </bindings>

**Comment by leastprivilege** [comment]
Not sure I follow - you request a token, you send the token to a service. That's how it works.

If your client application wants to get access to the contents of the token, make your service return the claims as part of a SOAP call.

**Comment by MosamM** [comment]
Hi, we are facing the same issue while hosting the Service in IIS i.e. remote server return 404 while the code works in case of self hosted environment. Also, the sender sends token but expects only string as return value. Kindly advise.
