### ISSUE TITLE
NDC Video Link Broken

### ISSUE THREAD

**Issue by CharlieMott** [IdentityServer/Thinktecture.IdentityServer3#1016]
Link is broken to the Video (http://www.ndcvideos.com/#/app/video/2651) referenced from here (https://identityserver.github.io/Documentation/).

**Comment by heraclesaraujo** [comment]
working fine here...

**Comment by sania13** [comment]
It is doing for me too after about 30-40 minutes. 

You need to close the browser and open it again. It will work.

**Comment by brockallen** [comment]
Yep, works for me. Closing.

**Comment by CharlieMott** [comment]
Linked worked on my iPhone but not using IE on work laptop.
Found a direct link to Vimeo which worked for me from IE on work laptop: https://vimeo.com/113604459

**Comment by leastprivilege** [comment]
The direct link is much better. thanks!
