### ISSUE TITLE
Mapping Username from 3rd party providers

### ISSUE THREAD

**Issue by stroebele** [IdentityServer/Thinktecture.IdentityServer3#1018]
I have IdSrv up and running with 3rd party providers from our local ADFS server and Google. When a user logs in from one of those 3rd party services an account gets created for them, however the Username is a GUID. Is there a way to pull a more reasonable Username?

**Comment by leastprivilege** [comment]
I assume you are using the in-memory user service? this is just for testing.

And with username you mean the subject - which is a user id - a Guid is very reasonable for that.

**Comment by stroebele** [comment]
Sorry, I should have mentioned that. I'm not using the InMemoryService rather MembershipReboot.

**Comment by AlbertoLeon** [comment]
@stroebele in MembershipReboot you can set your own GUID with the parameter userID when CreateAccount is called. Is one of the last optional parameters
