### ISSUE TITLE
AuthorizationCode flow from a C# acceptance test and JavaScript

### ISSUE THREAD

**Issue by roryprimrose** [IdentityServer/Thinktecture.IdentityServer3#1019]
I have a question about using AuthorizationCode flow. I'm trying to use IdentityServer3 as a development STS whereas in production we will be using an on-premise ADFS. My understanding is that ADFS will support JWT with AuthorizationCode. Our solution has a Web API, an AngularJS website (pure client side code, no MVC) and an acceptance test project for the API.

I'm confused about how to request an authorization code in the acceptance tests from IdentityServer which I can then pass to the API. The OAuth2Client seems to be designed around HTTP request response whereas the acceptance test is more like a console application.

The ultimate goal here is to get both the javascript in the website and the code in the acceptance test to get a code from IdentityServer (simulating ADFS in production) to provide to the Web API which can then (presumably) get the identity from the STS using the provided code.

Any pointers would be appreciated.

**Comment by leastprivilege** [comment]
That's not quite trivial - you need to simulate a browser using HttpClient - navigate to authorize endpoint, follow redirects, remember cookies, post to login page etc.

**Comment by brockallen** [comment]
Also, I'm not certain that ADFS and IdSvr will behave 100% the same -- there are some things that are done differently across the two. For example, ADFS doesn't use client secrets for code flow or refresh tokens.
