### ISSUE TITLE
What happens when IIS Hosting this IdentityServer Re-cycles.

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/Thinktecture.IdentityServer3#1020]
What happens when IIS Hosting this IdentityServer Re-cycles. Do we need to do anything to save current state of Application and restore when IIS Re-cycles 'or' these AccessTokens and authorization is treated stateless and can go back any time?.

**Comment by brockallen** [comment]
As long as you configure the stores and services as suggested here:

https://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html

**Comment by skatukojwala** [comment]
Thank you for answering all the questions I had.
