### ISSUE TITLE
DefaultViewService coupled with ViewEngine

### ISSUE THREAD

**Issue by 20John22** [IdentityServer/Thinktecture.IdentityServer3#1021]
I was looking for a way to customize login, consent pages and I have found IUserView and DefaultViewService. From what I can see you created ViewEngine for rendering html pages using web api. It's really nice approach and I would like to use it in other projects. Is there a chance to sepeare view engine from DefaultViewService and move it to different project?

Is there a chance to support such feature?

**Comment by brockallen** [comment]
No, no plans. Sorry.
