### ISSUE TITLE
Localizing login/logout per user language

### ISSUE THREAD

**Issue by mikkark** [IdentityServer/Thinktecture.IdentityServer3#1024]
I am a little confused regarding the localization of Identityserver (IS). I want to localize the pages per the language selected by the user in the UI of our app. For the login page this is simple (imagine that the browser has the language stored in local storage or something) because the login message goes to the ViewService. In there I can put the ui_locale url parameter in the model and read that in my custom Javascript. However, sadly the logout message can not be used in the same way because it is not given to the view service.

I failed to find an example on how to do a per-user localization and the list of services to override wasn't helpful here (apart from the viewservice for the login page). The same question applies to localizing the error messages. The only extension point is to write a custom localization service that has a single api, the GetString method. How is it possible to return a localized string depending on the language of the user?

**Comment by johnkors** [comment]
You could inject the [OwinEnvironmentService](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Services/OwinEnvironmentService.cs) into your LocalizationService and make use of whatever you store in the environment to decide what localization you want to use.

**Comment by mikkark** [comment]
Thanks for a quick response! I used a combination of a cookie, OwinEnvironmentService injection, custom view service and custom localization service and it seems to be doing the trick. Thank you.

**Comment by johnkors** [comment]
np. Could you close this issue as well?

**Comment by mikkark** [comment]
Yes I can, sorry about that :)
