### ISSUE TITLE
Custom Views in an OWIN Worker Role

### ISSUE THREAD

**Issue by bcbeatty** [IdentityServer/Thinktecture.IdentityServer3#1025]
I'm trying to customize my own login view to add a Forgot Password link and its functionality.
I'm trying to duplicate the functionality in the Custom View Service sample app, but I have (at least) 1 difference in the project setup: My app is a self hosted Owin console application and not a web site, it will eventually be an azure worker role.
What are the changes I need to make to get this working in when Owin is self hosted as a worker role?
 
I'm using Identity Server v3
Thanks

**Comment by brockallen** [comment]
Well, this is not really an IdSvr specific question. In short, anything you relied upon IIS/ASP.NET for, you'd have to have a replacement in the OWIN self-hosted scenario.

**Comment by bcbeatty** [comment]
Follow up question, once I get past this, is this the best practice to add forgot password link functionality?

**Comment by brockallen** [comment]
Well... seems like a useful thing from the login page, right?
