### ISSUE TITLE
Authorize endpoint redirects to invalid redirect_uri if there are invalid params

### ISSUE THREAD

**Issue by giulianob** [IdentityServer/Thinktecture.IdentityServer3#1026]
If there are invalid parameters like a missing nonce or anything that returns Invalid(ErrorTypes.Client) in AuthorizeRequestValidator.ValidateProtocol, the user will be redirected to whatever redirect_uri was given. This seems to go against the OAuth spec which states: 

"If the request fails due to a missing, invalid, or mismatching redirection URI, or if the client identifier is missing or invalid, the authorization server SHOULD inform the resource owner of the error and MUST NOT automatically redirect the user-agent to the invalid redirection URI."

**Comment by leastprivilege** [comment]
Could you give me an example - normally the client_id and redirect_uri are validated first. Only if they are OK we send errors back to the client.

**Comment by giulianob** [comment]
Sure, for example, if I navigate to something like:

http://localhost/connect/authorize?client_id=rec14web&response_type=id_token+token&scope=openid+profile+roles&redirect_uri=https://www.somemaliciouswebsite.com&acr_values=tenant%3Atest&response_mode=form_post&ui_locales=en‐US

(Notice the nonce is missing)

The AuthorizeRequestValidator.ValidateProtocol will return an error of type ErrorTypes.Client. Then the logic in the controller is to POST the error back to the redirect_uri. It looks like the query string parameters have some validations in ValidateProtocol that happen before the redirect_uri is checked to see if it's in the whitelist. If any of those fail, the user is taken to whatever redirect_uri was given. If you put the nonce in there, then you get the expected "Client is invalid" error page but without the nonce the user is redirected to the error page. I think validating the redirect_uri should happen before the other validations like checking for valid nonce otherwise this is allows for open redirection attacks.

Regards

**Comment by leastprivilege** [comment]
Yes you are right - we were so focused on not leaking tokens that these fell through the cracks. Working on a fix.

thanks for reporting

**Comment by leastprivilege** [comment]
Fixed on dev. Can you check if it works as expected.
