### ISSUE TITLE
The client is disconnected because the underlying request has been completed.  There is no longer an HttpContext available.

### ISSUE THREAD

**Issue by johnkors** [IdentityServer/Thinktecture.IdentityServer3#1027]
Nuget package 1.2.1

Started seeing this error for ```DefaultCorsPolicyService```. Async / or registration issue (pr request?). ?

```
exception.Data	  	
exception.HResult	  	-2146233079
exception.InnerException.Data	  	
exception.InnerException.HResult	  	-2147467259
exception.InnerException.Message	  	The client is disconnected because the underlying request has been completed.  There is no longer an HttpContext available.
exception.InnerException.Source	  	System.Web
exception.InnerException.StackTrace	  	   at System.Web.HttpBufferlessInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Owin.Host.SystemWeb.CallStreams.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Web.Http.NonOwnedStream.Read(Byte[] buffer, Int32 offset, Int32 count) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer3\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0
   at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Http.Formatting.FormUrlEncodedMediaTypeFormatter.ReadFormUrlEncoded(Stream input, Int32 bufferSize) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer3\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0
exception.Message	  	Error reading HTML form URL-encoded data stream.
```

**Comment by brockallen** [comment]
Do you have any more detailed logs?

**Comment by brockallen** [comment]
Also, what do you have configured for CORS?

**Comment by brockallen** [comment]
I just added a bunch of logging on dev for CORS, so if you have some time perhaps try the build from myget and see if the logging helps.

**Comment by johnkors** [comment]
Using the ```DefaultCorsPolicyService``` and 

```
CorsPolicy = new CorsPolicy {AllowedOrigins = new[] {"http://domain1.no", "http://domain2.no", "http://domain3.no"}}
```

Will look into logs.

**Comment by johnkors** [comment]
We've only seen it once in one environment (test) out of our 4, so might have been a one off. Will monitor for it and see if we get it in an env with more traffic.

These are the events that occured at the time of exception. 
![image](https://cloud.githubusercontent.com/assets/206726/6522733/8dbaf200-c3e8-11e4-98e2-9046864b9605.png)

**Comment by brockallen** [comment]
So what's strange is that no where in the Cors policy code (and given the policy you have) is the request read (at least in our code). So the lack of context makes it difficult to track down.

**Comment by johnkors** [comment]
Yep, I'll get back to this issue if I see it reccuring.

**Comment by brockallen** [comment]
Well, at least this prompted me to add better logging to the CORS code :)
