### ISSUE TITLE
TFA via Resource Owner Password Flow

### ISSUE THREAD

**Issue by AnEmptyBliss** [IdentityServer/Thinktecture.IdentityServer3#1030]
I have Identity Server all nicely running with a custom user service that supports TFA using Authenticator apps and SMS codes, via the Authorization Code Grant flow.

My question is, is it all possible to implement similar using the resource owner password grant?

For example, if the client application wants to be responsible for all the screens involved (login, sms code entry etc), then is it possible for Identity Server to issue partial login indicators that can be visible to the consuming application? The consuming application then continues with the required parts of the TFA (which may involve calling other custom endpoints within the Identity Server host) before redirecting back to Identity Server to complete the sign-in process.

From what I think I understand, TFA is only really a good fit via Authorization Code grant with Identity Server, but just thought I'd ask the question in case I'm missing something.

Hope that all makes sense!

**Comment by leastprivilege** [comment]
Well you can - but IdSrv will not assist you in any way. RO flow is a simple request/response api call.

You could drive everyhting in the client UI - and you can pass additional parameters to the token endpoint. So it is possible, but completely custom.

**Comment by AnEmptyBliss** [comment]
Okay thank you - I'll have a go at figuring it out.
