### ISSUE TITLE
Log4Net not logging

### ISSUE THREAD

**Issue by superstevek** [IdentityServer/Thinktecture.IdentityServer3#1032]
Hi, I am trying to use log4net as the log provider for idserv3 but seem to be having some problems in that nothing is getting logged, i'm assuming I have just missed some part of the set up but cant see what.

I have "LogProvider.SetCurrentLogProvider(new Log4NetLogProvider());" and the logging options (of the IdentityServerOptions) set as:
                                                LoggingOptions = new LoggingOptions
                                                                        {
                                                                        EnableHttpLogging = true,
                                                                        EnableWebApiDiagnostics = true,
                                                                        IncludeSensitiveDataInLogs = true,
                                                                        WebApiDiagnosticsIsVerbose = true
                                                                        },
in the OwinStartup class. And i have the below set in the web.confg:
 <log4net>
    <appender name="EventLogAppender" type="log4net.Appender.EventLogAppender">
      <param name="LogName" value="Application" />
      <param name="ApplicationName" value="IdentityServer" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %-5level %logger [%property{NDC}] - %message%newline" />
      </layout>
      <securitycontext type="log4net.Util.WindowsSecurityContext">
        <credentials value="Process" />
      </securitycontext>
    </appender>   
    <root>
      <level value="INFO" />
      <appender-ref ref="EventLogAppender" />
    </root>
 </log4net>

Any help would be greatly appreciated.

**Comment by superstevek** [comment]
the web.config XML got lost in that last post, here it is:

```xml
<log4net>
    <appender name="EventLogAppender" type="log4net.Appender.EventLogAppender">
      <param name="LogName" value="Application" />
      <param name="ApplicationName" value="IdentityServer" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %-5level %logger [%property{NDC}] - %message%newline" />
      </layout>
      <securitycontext type="log4net.Util.WindowsSecurityContext">
        <credentials value="Process" />
      </securitycontext>
    </appender>   
    <root>
      <level value="INFO" />
      <appender-ref ref="EventLogAppender" />
    </root>
 </log4net>
```

**Comment by leastprivilege** [comment]
never used it with Log4Net - @damianh would know (LibLog 2.1)

**Comment by damianh** [comment]
https://github.com/damianh/LibLogSample/blob/master/LibLogSample/Program.cs#L10
https://cmatskas.com/application-logging-with-liblog/

**Comment by superstevek** [comment]
Thanks very much gents, missing the vital line:

log4net.Config.XmlConfigurator.Configure();

all logs to be logging now, much appreciated.

**Comment by hieplam** [comment]
Hi superstevek, where is your Log4NetLogProvider about, do i need to download extra package?
I'm trying to use log4net as the log provider in Identity server 3 but it seem it can not log anything
