### ISSUE TITLE
Different CustomViewService for different clients

### ISSUE THREAD

**Issue by ChrisVinall** [IdentityServer/Thinktecture.IdentityServer3#1033]
Quick question: Is it possible to use different IViewService implementations for different clients? I suspect the answer is "no" but thought I'd double check.

I'll give what I'm trying to do as well in case it's a Bad Idea: I have a mobile app wanting to use a Web API application secured by idsrv. I want the login process to be native in the app rather than via HTML views. Ideal for this would be just returning JSON for this client. I can, of course, just use the normal views and extract the JSON that gets rendered into the HTML. Just trying to save a little overhead.

Thanks.

**Comment by leastprivilege** [comment]
This does not make sense. If you want a native UI - just use the RO flow.

**Comment by ChrisVinall** [comment]
OK, thanks. From Googling my impression had been that I needed implicit flow, but reading about RO it makes sense.

**Comment by ChrisVinall** [comment]
....except, that doesn't support external auth. I guess I'll use RO for local login, custom grant for native Facebook login, and some browsery thing for Google login. Things have gotten messier than I originally envisioned. That's security for you I guess.

**Comment by leastprivilege** [comment]
or just implicit for all. (no native UI, no native Facebook).
