### ISSUE TITLE
Extend Identity server to produce token based upon Soap Call result

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/Thinktecture.IdentityServer3#1034]
Hello,

We have an identity server3 which is in federation with an WS federation service.
Now this Ws Federation service is not yet available. So we plan for transistion to use an instance of Identity server which makes an call to some SOAP Service with Username, passwort . If this call is successful - The user is regarded as authenitcated, otherwise not.

Can we wrap whose calls in identity server3(with WSFedPlugin?) ? 
As with the identity Server samples - I just have to replace the access to the InMemoryUsers with the soapcalls, right?
Is there a code sample targeting this scenario?

Thank you very much!

**Comment by brockallen** [comment]
You could maybe use this in the meantime:

https://www.nuget.org/packages/Thinktecture.IdentityModel.EmbeddedSts/
https://github.com/IdentityModel/Thinktecture.IdentityModel/tree/master/source/EmbeddedSts
https://github.com/IdentityModel/Thinktecture.IdentityModel/tree/master/samples/EmbeddedSts

**Comment by brockallen** [comment]
Oh I see -- never mind, you're already doing the same with another instance of IdSvr. So that's fine.

I guess I don't follow the question -- there are no SOAP calls with WS-Fed. All the calls travel via the browser.

**Comment by davidmrichter** [comment]
We have an "old" Soap Service, which we can (ab)use to get Information. if the user is typing the right password and if yes which roles he has. 
We know that later,  we will have that done via an WS Federation service available, without any Soap Calls. For this service we already configured a identity server3 instance with WSFed Plugin acting as surrogate until the real WS Fed SErvice is available.

Until then I wanted to modify the the WSFed Service surrogate to do those SOAP Calls identifying the user, getting its rolls and if being successfull sending back the SAML Tokens to our OAuth REsource Server.
Another option would be to include that special "authentification" without the WSFed Surrogate right on our "pure" Oauth Server. This would be then a bit deviant from our later production scenario.

**Is there a hook in identity server, there I could perform those SOAP Calls to identitfy the user and eventually create a Token if the user entered the right credentials?**

**Comment by brockallen** [comment]
If I understand the situation, I'd suggest to that the surrogate IdSvr have a user service that makes those SOAP calls.

**Comment by leastprivilege** [comment]
The hook is called IUserService - and is documented.
