### ISSUE TITLE
We cannot pass any custom errors information in AuthenticateResult

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/Thinktecture.IdentityServer3#1035]
We are overriding following method to customize our user logins, We need to pass lot of error information if the login fails, Since the is returned as part of generic type we cannot extend AuthenticateResult to pass failure information.

Please let me know if there is any other better way of handling these errors. Since we are customizing our login screens and errors messages we need more information to be passed around.

public Task AuthenticateLocalAsync(string username, string password, SignInMessage message)
{

}

**Comment by johnkors** [comment]
The single param ctor of [AuthenticateResult](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Models/AuthenticateResult.cs#L61) takes an error msg, which is provided to the [LoginViewModels ErrorMessage property](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/ViewModels/ErrorViewModel.cs#L30) (```LoginViewModel``` inherits ```ErrorViewModel```).

**Comment by skatukojwala** [comment]
Um.., Sending everything in one string could be painful, especially with enterprise integration scenarios.

**Comment by brockallen** [comment]
You want to pass back failure to where? The client application?

**Comment by leastprivilege** [comment]
Enterprise integration is always painful ;)

**Comment by skatukojwala** [comment]
yes, I need this information to client application.

**Comment by brockallen** [comment]
The OIDC is very clear on what and how error messages are sent back to the client. This is why we don't expose anything along these lines.

**Comment by skatukojwala** [comment]
Great! Thank you for clarifying it. What is OIDC?

**Comment by skatukojwala** [comment]
Never mind Open ID Connect?.

**Comment by brockallen** [comment]
Yes, the OIDC spec*

**Comment by skatukojwala** [comment]
Thank you for clarifying this.

**Comment by skatukojwala** [comment]
Would it be okay to use JSON to send our error message information?

**Comment by brockallen** [comment]
Well, maybe it makes the most sense to log this sort of stuff to a DB? What's an example of what you need to do?

**Comment by skatukojwala** [comment]
Thank you Allan, as of now we can live with this one string, but I foresee needed more information 
to be passed for enterprise integrations. 

Just quick question,  The errors that we are sending are interpreted by Framework and returns standard OpenID error codes back to the client right?.   Just in case if we end up passing JSON in it does it fails?. Do you remember top of you head?.

**Comment by brockallen** [comment]
No -- the error message on the result is a error to the user. See the docs:

https://identityserver.github.io/Documentation/docs/advanced/userService.html

**Comment by skatukojwala** [comment]
Great! That is perfect.
Technically I can pass a JSON Object if needed and interpret in my Custom
error page.

Thank you,
Srinivas.

**Comment by brockallen** [comment]
Well, it wasn't really designed for that, so do that at your own risk.

**Comment by Davidsual** [comment]
Hi
I am trying to authenticate a user with username / password and get an access token.
I am using IdentiyServer3 + Asp.Net Identity.

If in my custom IUserService in the method Task<AuthenticateResult> AuthenticateLocalAsync I raise an error like:
return new AuthenticateResult("User Locked out");

the next Layer in IDS Core/Validation/TokenRequestValidator,cs will always override my error message with:

 var authnResult = await _users.AuthenticateLocalAsync(userName, password, signInMessage);
if (authnResult == null || authnResult.IsError || authnResult.IsPartialSignIn)
{
LogError("User authentication failed");
RaiseFailedResourceOwnerAuthenticationEvent(userName, signInMessage);
return Invalid(Constants.TokenErrors.InvalidGrant);
}

InvalidGrant

How  can I override this behavior?

I want to return custom json to my client with error User Locked out.

Currently I am always receive the message "invalid_grant"

Thank you and compliment for your work

**Comment by brockallen** [comment]
@Davidsual In 2.0.0 (I don't remember if we did this on 1.x) if you return an error message in the user service AuthenticateResult it will come back in the response from a resource owner token request. For example:
```
{
  "error": "invalid_grant",
  "error_description": "Use is locked out"
}
```

**Comment by pankajisgarg** [comment]
Hi, 
I also don't see custom error on login page. I am using IdentiyServer3 & CustomViewService sample as base and added Custom UserService. 

`            if (output.status == true)
            {
                var user = MapUser(output);
                Users.Add(user);
                context.AuthenticateResult = new AuthenticateResult(user.Subject, user.Username, user.Claims);
            }
            else
            {
                new AuthenticateResult("Invalid OTP, please verify and try again.");
            }
`
But on login screen i only see generic error message i.e. "Error: Invalid username or password ".
Can you please let me know, what is missing.

Thanks
