### ISSUE TITLE
Pluralsight training

### ISSUE THREAD

**Issue by julianpaulozzi** [IdentityServer/Thinktecture.IdentityServer3#1036]
Both "Thinktecture.IdentityServer3" as the "BrockAllen.MembershipReboot" are increasingly popular and the Pluralsight has been an invaluable resource for following.
Besides the more Dominick already been there with great stuff.
Would not it be something very nice to have that training focused exclusively on those contributions?

**Comment by brockallen** [comment]
Perhaps.
