### ISSUE TITLE
Signing request to protected resource

### ISSUE THREAD

**Issue by alexeyauslender** [IdentityServer/Thinktecture.IdentityServer3#1039]
Is it possible to use signed requests to protected resource in order to ensure that the desired request parameters are delivered to the protected resource without having been tampered with?

**Comment by leastprivilege** [comment]
By default the assumption is, that SSL will take care of that.

If you don't want to solely rely on SSL there are a number of approaches, e.g. hawk or the upcoming MAC specification (that works hand in hand with the also upcoming proof of possession specs).

That's an implementation detail between client and resource.

**Comment by alexeyauslender** [comment]
My problem is that parameters might be tampered on client during implicit flow,in this case SSL would not solve my problem.

**Comment by leastprivilege** [comment]
Hold on - that's something completely different. Are you talking about client/resource or client/OP communication?

If someone can tamper data on the client already - there's not much you can do about it because the client is already compromised.

also - we do pretty strict input validation on the incoming requests - in which way would a "tampered implicit flow" hurt us?

**Comment by alexeyauslender** [comment]
OK.I didn't explained my self clear enough .I am talking about implicit flow in which my application (web site) accessing my protected resource after authentication with idsrv. In this case I am transferring parameters to API through URL ,so it is possible to tamper with this parameters from client.
I thought that may be it is possible to sign request in order to ensure that parameters delivered to API without having been tempered?

**Comment by johnkors** [comment]
Typically, your API requests are done using an access token that are signed by idsrv. The API then verifies that the access token is valid (signed by idsrv cert) before it process any request (and params).

**Comment by alexeyauslender** [comment]
The problem is that access token doesn't includes user specific data.If you are logged in user and wish to temper with parameters you can change some parameters in url and in this way compromise data on API side(the access token in this case valid) .So the question is how to ensure on API side that request parameters has not been tempered on client before request.

**Comment by johnkors** [comment]
I guess you use input validation in your API controllers, so what kind of tampering are you talking about that is not catched by that?

**Comment by alexeyauslender** [comment]
In our platform the end user may create entity and add to this entity different assets. From application point of view Web Site accessing some Web Api in order to create entity and then Web Site keep accessing different Web Apis in order to add assets to this entity. So main question is ,how should I authorize request in all this APIs which depends on entity id and assets ids which might be tempered on client side(as I already mentioned we are transferring parameters through url).I mean should entity id and user id be a part of the token in order to avoid tempering(all tokens are signed and there for secured from tempering).If I'll use entity Id and  user id as parameters which transfers to api through url the end user might send different entity id in order to compromise data.(for example : connect assets of somebody else entity to his one).

**Comment by leastprivilege** [comment]
So you are really talking about authorization.

Well - the token should contain enough identity information so that the resource can find out if the user is allowed what he's trying to do. Not really an identity server issue.

**Comment by alexeyauslender** [comment]
Exactly Dominick ,authorization only.So should I extend access token claims in order to add end user specific data or may be subject claim may solve this issue ,as I understand this is the only claim with user specific data.

**Comment by leastprivilege** [comment]
subject claim, role - things like that.
