### ISSUE TITLE
Resolving registrations in custom controllers/user service

### ISSUE THREAD

**Issue by stevenfirstrowinc** [IdentityServer/Thinktecture.IdentityServer3#1041]
Hi,

I'm using the CustomUserService sample to implement similar functionality to the Eula example.  In the sample you use an in memory static list of users.  Obviously that won't work in real scenarios.  What I really want is my custom UserAccountService to be injected.  I've registered it in my factory (obviously) but how can I get it to my controller so I can mark the user as having accepted it?  

If it makes any difference I'm using Owin/Katana.  This will probably be one of those 'duh' moments once explained.

**Comment by brockallen** [comment]
Once your outside of IdSvr, then you get those things with your own approach. If you want to use DI, then use the DI system of MVC.

**Comment by stevenfirstrowinc** [comment]
does that mean I have to create/use a separate container than the one I already configured while setting up IdSrv?

**Comment by brockallen** [comment]
Yep. 

-Brock

**Comment by stevenfirstrowinc** [comment]
last question...  As I am using Owin I see that the Autofac container is being carried around in the environment; is it a bad idea to use that?  This is more of a curiosity question than anything.

**Comment by brockallen** [comment]
Umm... I don't think so -- we use our own key for it (unless we picked a bad name -- and I don't remember what we used).

**Comment by stevenfirstrowinc** [comment]
it's actually idsrv:AutofacScope and looking at it closer, it's not exactly the same thing.  Anyway thanks for the assist.  I can decide about my DI (if) when I finish the other parts.

**Comment by weitzhandler** [comment]
In bearer authorization, can I have the `Controller.User.Identity` in a WebAPI return the authenticated user?
