### ISSUE TITLE
Instead of Cookies in the ClaimsIdentity  can i use DefaultAuthenticationTypes.ApplicationCookie In the SigninCallback function in the Idsrv3

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#1042]
Instead  of example 1 can i use Example 2 in the SignIncallback Function in Idrsv3  and we are using "Cookies" if i am using cookies in the client application  not able to get the User.Identity.Name                                                                                                                                                       Example :- 1 var id = new ClaimsIdentity(claims, "Cookies"); 

Example :- 2 var id = new ClaimsIdentity(claims, DefaultAuthenticationTypes.ApplicationCookie);

**Comment by leastprivilege** [comment]
This question has no context whatsoever. closing.
