### ISSUE TITLE
Resource Owner Flow with Bearer Token Authorization

### ISSUE THREAD

**Issue by soliveira** [IdentityServer/Thinktecture.IdentityServer3#1043]
Hi I’m using Identity Server to authenticate an API application. On the API I use:
```C#
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
           {
               Authority = options.Authority,
               RequiredScopes = options.RequiredScopes,
               AuthenticationMode = AuthenticationMode.Active
           });
```
I need to authorize both client and Users for that I resource owner flow in the client and the Resource Authentication at the API.
The Token passed in the header contains the claims for the client and the “sub” claim. How can I get the user claims from the API application? I know I can use the userinfo endpoint, but where should I make the call to this endpoint?
I’ve tried to extend the ResourceAuthorizeAttribute, and ClaimsTransformation but I can’t reach the AccessToken.
Keep in mind that the STS, RP and API clients live on separate servers.

Can you help?

**Comment by leastprivilege** [comment]
By adding scopes to the token request that link to user claims. Check the docs.

**Comment by soliveira** [comment]
I had included the scopes in the token request:
```
  private void Test()
        {
            var token = RequestGuestToken();

            var client = new HttpClient
            {
                BaseAddress = new Uri("API_ENDPOINT")
            };

            client.SetBearerToken(token.AccessToken);
            var response = client.GetStringAsync("api/test").Result;
        }

 private static TokenResponse RequestUserToken()
        {
            var client = new OAuth2Client(
                new Uri("TOKEN_ENDPOINT"),
                "clientId",
                "secret");
            return client.RequestResourceOwnerPasswordAsync("username", "pass", "openid profile roles email").Result;
        }
```
Access Token:
```
{
  "client_id": "clientId",
  "scope": [
    "email",
    "openid",
    "profile",
    "roles"
  ],
  "sub": "fc6dd9ac-37b7-4032-b8f8-053c59607694",
  "amr": "password",
  "auth_time": 1425900840,
  "idp": "idsrv",
  "iss": "http://iss.info",
  "aud": "http://aud.info",
  "exp": 1425901941,
  "nbf": 1425900841
}
```

Am I missing something?

thks

**Comment by leastprivilege** [comment]
Well - you only requested identity scopes - with those you could contact the userinfo endpoint to get the claims for the user.

You haven't requested any resource scopes - so strictly speaking you cannot access "api/test" - or rather you are not validating the scopes in your api endpoint.

Again the docs have more info on scopes and claims.

**Comment by soliveira** [comment]
It seems that I'm not being able to explain correctly my issue, trust me I read the documentation... twice, or probably more :)

In my application the Authorization configuration is delegated to a Policy Server, responsible to match roles to (resource, Action) pair.

 In reality I'm using the role claim to validate the resources, I extended the ResourceAuthorizationManager to match the Roles to the authorized resources:

```
// ResourceAuthorizationManager
  public override Task<bool> CheckAccessAsync(ResourceAuthorizationContext context)
        {
            var resource = context.Resource.Select(x => x.Value).ToList();
            var action = context.Action.First().Value;

            return Task.Run(async () => await this.policyService.CheckAccessAsync(action, resource, this.GetPrincipalRoles(context).ToList()).ConfigureAwait(false));
        }

// Policy Service
 public async Task<bool> CheckAccessAsync(string action, string resource, IList<string> principalRoles)
        {
            if (principalRoles == null || !principalRoles.Any())
            {
                return false;
            }

            var policies = await this.policyGateway.GetPoliciesAsync().ConfigureAwait(false);

            if (!policies.ContainsKey(resource))
            {
                return false;
            }

            var resourceActions = policies[resource];

            if (!resourceActions.ContainsKey(action))
            {
                return false;
            }

            var requiredRoles = resourceActions[action];

            return requiredRoles.Intersect(principalRoles).Any();
        }
```

My missing piece is the access to the userinfo endpoint. When should I make the call? Or is it possible to include the roles in the Authorization Token?

**Comment by leastprivilege** [comment]
Do this:

* create a custome scope representing your API (ScopeType.Resource)
* add ScopeClaims to that Scope definition for every claim you want to be available in your API
* request a token using that scope

**Comment by soliveira** [comment]
Perfect.... Worked like a charm.

Thanks allot
