### ISSUE TITLE
WsFederation question

### ISSUE THREAD

**Issue by protoforge** [IdentityServer/Thinktecture.IdentityServer3#1050]
I have a remote organization with their own ADFS server which isn't returning to the IdentityServer application after I login.

Nothing in the IdentityServer log indicates an obvious problem.  Their site simply presents a generic error page after I successfully enter credentials.  There's no indication of it attempting to come back to my server (nothing in any logs or the web browser that I see).  It feels like they simply didn't enter the endpoint and/or identifier correctly.

I've tested with my own ADFS server and the workflow and configuration seems valid on my side.  

Q1 - They did a manual RP trust configuration since I don't have a metadata file.  Is there an automated way of generating a metadata file so a manual configuration isn't required on their side?  

Q2 - Other than double-checking settings, what logs can they check or operations can they do that might help me troubleshoot?  

Here's the trivial ADFS setup I have:

    var adfs_external = new WsFederationAuthenticationOptions
    {
        AuthenticationType = "adfs_ext",
        Caption = "The Customer",
        SignInAsAuthenticationType = signInAsType,
        MetadataAddress = "https://connect.theirdomain.com/federationmetadata/2007-06/federationmetadata.xml",
        Wtrealm = "urn:something-unique"
    };
    app.UseWsFederationAuthentication(adfs_external);

The only items in the ADFS RP properties (validated with my own ADFS configuration):

ADFS 2.0 profile with a WS-Federation Passive protocol - url set to https://myhost.com/ID  (the IdentityServer instance)

After the RP wizard, the settings seen in the ADFS setup are:

Identifiers:
urn:something-unique
https://myhost.com/ID

Endpoint (WS-Federation Passive protocol):
https://myhost.com/ID

Thanks in advance!

**Comment by protoforge** [comment]
Sure enough...  They were using a different urn for the Wtrealm....   

I think my original question of how to generate metadata is still a topic.  FedUtil seems deprecated.  How do we create the file so configuration problems are minimized?

**Comment by leastprivilege** [comment]
I don't know - I never used fedutil - i think it is easy enough to enter the 3 data points manually.

.NET has all the APIs so you could create your own fedutil.
