### ISSUE TITLE
Feature: Google Authenticator Integration

### ISSUE THREAD

**Issue by dealproc** [IdentityServer/Thinktecture.IdentityServer3#160]
Not necessarily for the v3.0 release, but it would be interesting to have Google Authenticator support built into the 2-Factor tooling for Identity Server v3.

http://blog.tinisles.com/2011/10/google-authenticator-one-time-password-algorithm-in-javascript/

Not sure if this is doable or not, and if it'd make sense or not, but definitely something to discuss.

**Comment by leastprivilege** [comment]
closing. there will be a 2FA sample soon showing the general approach.
