### ISSUE TITLE
Cleanup embedded stylesheet

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/Thinktecture.IdentityServer3#261]
Verify the usage of all classes in site.css

**Comment by leastprivilege** [comment]
yes - that needs to be done before RTM

**Comment by leastprivilege** [comment]
IdP buttons are still "off"

**Comment by brockallen** [comment]
You know, some high-paid designer at twitter designed that first list item to be slightly off. 

Fixed on dev.
