### ISSUE TITLE
The assemblies delivered via the NuGet packages have an Authenticode signature

### ISSUE THREAD

**Issue by skentjones** [IdentityServer/Thinktecture.IdentityServer3#541]
Our assemblies are all Authenticode signed and cannot load assemblies which are not. Can the assemblies we pull from the NuGet packages be signed?

**Comment by brockallen** [comment]
We will eventually add an authenticode signature, but not for RTM next week.

Is this still an issue? We asked Microsoft, and you can load unsigned assemblies from signed assemblies.

**Comment by skentjones** [comment]
I am no longer with the organization under which this was originally asked, but we are now evaluating under my new organization. You can load the DLLs but long term we tie a lot of checking to Authenticode signatures. So still wondering if this will be available.
