### ISSUE TITLE
How to build on mono?

### ISSUE THREAD

**Issue by haf** [IdentityServer/Thinktecture.IdentityServer3#555]
I can't find a file to build with.

`xbuild source/Thinktecture.IdentityServer.v3.sln` fails.

**Comment by brockallen** [comment]
We don't have a mono infrastructure (as you know). We're releasing next week, so after RTM if you'd like to help with this we can chat. Thx.

**Comment by haf** [comment]
I have actually migrated to Hawk and released my own library for it https://github.com/logibit/logibit.hawk - I'm leaving OAuth behind for now, and I'm actually pretty happy about that.

**Comment by brockallen** [comment]
Ok, thanks for the update.

**Comment by krippz** [comment]
Well I was eager to look at how to build on Mono, ran int this post http://www.ryanmelena.com/2014/10/31/thinktecture-identityserver-v3-on-mono/  by Ryan Melena.
I'll still look into it, see what Mono is required and so on.

**Comment by AlexZeitler** [comment]
@krippz Did you manage to build it on Mono / Linux?
Looks like things like `RsaEncryptionCookieTransform` and `RsaSignatureCookieTransform` are missing?

**Comment by AlexZeitler** [comment]
Was able to build it using the [Microsoft.IdentityModel](https://www.nuget.org/packages/Microsoft.IdentityModel/) NuGet package and start the SelfHost.
