### ISSUE TITLE
Allow refreshing claims when refreshing access token

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/Thinktecture.IdentityServer3#573]

**Comment by RaulMo7** [comment]
Hi guys.

I have a possible solution for this issue, possibly not the best way but it may give you an idea to implement this functionality because I think it's important.

In theory the only thing I did was that when you call the refresh token endpoint of the claims-are consulted in database to be updated too, with this ensures that always the updated claims-in ClaimsPrincipal information becomes available.

In class TokenResponseGenerator.cs
method ProcessRefreshTokenRequestAsync


It has been modified so that it is as follows:

private async Task<TokenResponse> ProcessRefreshTokenRequestAsync(ValidatedTokenRequest request)
        {
            Logger.Info("Processing refresh token request");

            var oldAccessToken = request.RefreshToken.AccessToken;
            oldAccessToken.CreationTime = DateTimeOffsetHelper.UtcNow;
            oldAccessToken.Lifetime = request.Client.AccessTokenLifetime;

            var subjectId = ClaimsExtensions.GetValue(oldAccessToken.Claims, Constants.ClaimTypes.Subject);

            var db = new DefaultMembershipRebootDatabase();
            var userRepository = new DefaultUserAccountRepository(db);
            var userAccountService = new UserAccountService(new MembershipRebootConfiguration(), userRepository);

            var account = userAccountService.GetByID(new Guid(subjectId));

            var claims = GetClaimsFromAccount(account, userAccountService);

            foreach (var claim in claims)
            {
                if (oldAccessToken.Claims.Contains(claim, new CustomClaimComparer()))
                {
                    oldAccessToken.Claims.RemoveAll(e => e.Type == claim.Type);
                    oldAccessToken.Claims.Add(claim);
                }
            }

            var newAccessToken = await _tokenService.CreateSecurityTokenAsync(oldAccessToken);
            var handle = await _refreshTokenService.UpdateRefreshTokenAsync(request.RefreshTokenHandle, request.RefreshToken, request.Client);

            return new TokenResponse
                {
                    AccessToken = newAccessToken,
                    AccessTokenLifetime = request.Client.AccessTokenLifetime,
                    RefreshToken = handle
                };
        }

I'll be careful if they require any additional information.

Greetings

**Comment by satlom** [comment]
Hi!
Do you know when this feature would make its way into the product?
This is a very important feature if you develop SPA apps. 
If the user change tenant in the application, you need a way to recreate all claims when you refresh the access token.

**Comment by fberlin** [comment]
+1 for this. 

I extend DefaultClaimsProvider and override GetAccessTokenClaimsAsync to set custom claims.. 
This works great on inital login but is not called when using a refreshtoken..
 It would be really nice if this method is executed when refreshing an accesstoken.

**Comment by leastprivilege** [comment]
I added it to the todo queue - busy right now. sorry.

**Comment by leastprivilege** [comment]
I spiked it on the "RefreshRefreshTokenClaims" branch.

https://github.com/IdentityServer/Thinktecture.IdentityServer3/pull/959

Give it a try and see if it works as you expect - if I don't hear anything back I assume you don't need the feature anymore.

**Comment by satlom** [comment]
Do I need to build it myself? 
I use the pre-released packages from Nuget pointing to "https://www.myget.org/F/thinktecture/api/v2/".
Will the new feature be included there?

**Comment by leastprivilege** [comment]
good point - i will merge it

**Comment by leastprivilege** [comment]
should be up soon 

https://ci.appveyor.com/project/leastprivilege/thinktecture/build/1.1.117

**Comment by satlom** [comment]
Hi!
We use EntityFramework "Thinktecture.IdentityServer.EntityFramework.Entities.Client"
The property "UpdateAccessTokenOnRefresh" seems to be missing.

**Comment by leastprivilege** [comment]
of course it does ;)

**Comment by leastprivilege** [comment]
Switch to an in-memory client for testing.

**Comment by satlom** [comment]
Perfect!!
It works as expected.
We changed the factory to InMemory but we need it in Entity framework also.
Do you know when it will be available in a Pre-Release?

**Comment by fberlin** [comment]
I can comfirm that it works great with an in-memory client. :-)
But just like Saltom I use Entity Framwork so I'm only halfway there with in-memory clients.

**Comment by leastprivilege** [comment]
Sure - but the whole point of the exercise was to get feedback if the feature is working for you or not.

We will add the EF schema changes to the 1.2 version of both IdSrv and EF once we know what we need to do (@brockallen).

**Comment by fberlin** [comment]
I think this is a very good solution and it fulfills my needs.

Looking forward to 1.2!

**Comment by satlom** [comment]
Great!
I'm also looking forward to the 1.2 release.
