### ISSUE TITLE
Allow CORS settings on Client registration

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/Thinktecture.IdentityServer3#584]

**Comment by brockallen** [comment]
Added an InMemoryClientCorsPolicyService on dev. 

@leastprivilege  Should this filter by Flow? Right now it filters clients by implicit and hybrid.

Will add an EF based implementation in the EF repo.

**Comment by brockallen** [comment]
Oh... I missed the idea that this was to be a client setting - that's a breaking change. Maybe for now filtering by flow is sufficient, then in a v2 we add a new Client flag?

**Comment by brockallen** [comment]
EF project now has a CORS policy service. Again, right now it's just grabbing the origins from the redirect URIs. If we choose to do something else (like a Client property) then it's easy enough to add.

**Comment by brockallen** [comment]
Add Allowed CORS Origins to client class and change in-mem implementation to use those.
