### ISSUE TITLE
Automatic Logout After Timeout Period

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/Thinktecture.IdentityServer3#666]
Hi,

We have been using implicit client and are currently looking at session timeouts.
After a certain period of inactivity (eg 20mins) our RP needs to be re-authenticated.

We looked into the Hybrid workflow with the refresh tokens, but weren't sure if this was what we needed.
If we have multiple RPs and only one of them needs to be re-authenticated after 20mins, is it possible to do this?

Would the following work?
- Set this RP to use its own hybrid client
- Set access token expiry  to 2 mins
- Set refresh token to sliding expiration of 20 mins.

After 20 mins of inactivity, when the RP goes to idsvr with a stale refresh token, will the user be prompted to login again? We have tried this, but havent' seen it working yet.

**Comment by parkinsona** [comment]
Do you have any more advice on this issue?

**Comment by leastprivilege** [comment]
I still don't understand - you can set the cookie lifetimes for each RP individually - and yes every RP should be a client in IdSrv.

The second knob you can turn in the cookie lifetime in idsrv.

**Comment by parkinsona** [comment]
Thanks again for your help.

Lets say I set both cookie lifetimes of the RPs to 20minutes, but the idsvr cookie lifetime to 4 hours. After 1 hour of activity, both RP cookies will be expired. When a user tries to access protected content, will the user be prompted to login again, or will they be auto logged in because idsvr still has an active cookie?

**Comment by leastprivilege** [comment]
Why 1 hour?

As long as IdSrv has an active cookie - there will be no login screen - you could set the IdSrv cookie to a short timeout (e.g. 20mins) - and the RP ones to longer (20 mins vs 8 hours).

**Comment by parkinsona** [comment]
1 hour was just an example.

Ok, I will set idsrv to a shorter timeout (eg 20) and give the RP ones different lengths. This is what I wasn't sure about, so you've answered that for me.

With this approach, would I need to use refresh tokens (ie Hybrid workflow), or will setting timeouts on the cookies in the RP for implicit client be suitable?

**Comment by leastprivilege** [comment]
Refresh tokens are completely unrelated. Implicit flow is fine.

**Comment by parkinsona** [comment]
Thanks for the update. I will go with this approach and stick with implicit flow.

**Comment by parkinsona** [comment]
Hi @leastprivilege,

Due to other priorities, i'm only getting back to this issue now.
After discussing this with a collegue, I'm still not sure about a few things.

You recommended to set the cookie expirations, which is fine. However, we've noticed, that the default identity token lifetime is 6 minutes.

Consider the following:
Implicit Client
RP - cookie expiration of 8 hours, ID token lifetime - 5 minutes
idsvr - cookie expiration 1 hr

After 5 minutes, the RP will be redirected to idsvr to get a new token.
By default, it doesn't look like idsvr cookie is set to sliding expiration. So after 1 hour, the next new token request would go to idsvr and the login page would be presented.

Is this what should happen?
Would we also need to update the ID token lifetime?

If we made idsvr cookie sliding, that looks like it would fix some things. But may not be ideal.

**Comment by leastprivilege** [comment]
id token lifetime and cookies are unrelated concepts - you can configure them individually. The id token is only used for validation (and maybe logout).

Maybe you have not set the UseTokenLifetime = false on the OIDC MW - which set the cookie to the same lifetime as the id token.

**Comment by parkinsona** [comment]
The UseTokenLifetime makes sense now.

We're looking at doing something like this to achieve our goal.

- idsvr cookie timeout - 1 hour
- all id token life times, 5 minutes
- all RPS - usetokenlifetime = false
- RP1 - cookie lifetime 3 hours, sliding
- RP2 - cookie lifetime 6 hours, sliding

This means after the RPs expire, they will be forced to relog. Which is fine, if the user doesn't want to enter their details again, there is the remember me option.

Is there any potential risks with this approach?
The only downside, is that if a user's claims are updated, you can't refresh them without logging back into idsvr. This isn't a deal breaker, and could still be controlled with appropriate lifetime values.

Is it best to use a short token lifetime, so that if it does get intercepted, the damage done will be miniaml?

**Comment by parkinsona** [comment]
Hi Dom,

We've tried a few implementations for this original issue, but we're still finding ourselves stuck. I'm curious to know if you've come across this issue in identity manager yet.

#### Our Scenario
- RP 1 - client application, needs to time out after 20 mins of inactivity.
- RP 2 - user management app (self service identity management). 
- RP 1 can link to RP2 for user management.

#### Current implementation
- RP1 & RP2 - 5 minute token lifetime, we use token lifetime for cookie expiration, which is non-sliding
- idsvr - 20 minute timeout, sliding expiration.

#### What works
- user out after the expected time.
- Going from RP1 to RP2 works because idsvr will be current

#### What doesn't work
- Ajax Calls - to keep identity server alive, we request a new token every 5 minutes. But we keep the RP cookies non-sliding to achieve this. What happens, is if you do an ajax action on the 5 minute mark, it doesn't go and retrieve a new token, and just returns an unauthenticated request. The handling of this is fine, but its the frequency that is the problem. Even if we pushed the lifetime up to 20 minutes, a user would get this error every 20 minutes.

#### Possible Solutions
1. Use sliding expiration on the RP cookies. This would stop the ajax issue, but it won't keep identity server active. If the user was active for 30 minutes before in RP1, then they go to RP2 they would need to log in again.
2. Renew the id token prior to its expiry to ensure it never expires. I don't know how to do this, or if it would solve the ajax issue.
3. Increase the life time of the identity server cookie & use sliding RP cookie - Similar to 1, but it would allow more time before login is requested when switching between RPs. This then invalidates the requirement to have a 20 minute timeout.

I'm starting to think what I'm attempting to do is either wrong, dumb or impossible. Or all of the above.
My business, is wanting single sign in, but they also want short timeouts. It seems that these 2 requirements are conflicting. 

Any ideas?

**Comment by leastprivilege** [comment]
I think both requirements are conflicting (SSO = don't login very often vs short timeout == login more often)

**Comment by parkinsona** [comment]
Thanks for the confirmation. I kept thinking this was going to be impossible to solve. Knowing these are conflicting requirements, will help me disucss the options with our business people.
