### ISSUE TITLE
Add welcome page

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/Thinktecture.IdentityServer3#696]

**Comment by brockallen** [comment]
maybe we just redirect to the client permissions page -- @leastprivilege thoughts?

**Comment by leastprivilege** [comment]
RTM or postpone?

static page with links to permissions and discovery?

**Comment by brockallen** [comment]
No time for RTM

**Comment by brockallen** [comment]
So just a welcome page using the built-in assets with same links as the current host welcome page. A single flag to disable on the IdSvr options.

**Comment by brockallen** [comment]
embedded welcome page added on "welcome" branch. @leastprivilege maybe take a look?

**Comment by brockallen** [comment]
ok, merged to dev. if we don't like it we can back it out.
