### ISSUE TITLE
Built-in support for 2FA

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/Thinktecture.IdentityServer3#706]

**Comment by iltera** [comment]
Is 2FA still a discussion, or going to be a part of IDS for sure?

**Comment by brockallen** [comment]
The milestone is set to "Post RTM".

**Comment by brockallen** [comment]
We have a sample for this and it's not much work. I'm not sure we can build a generic 2fa infrastructure for the various 2fa approaches that might be required. I'm inclined to close this with 'wontfix' -- opinions?

**Comment by leastprivilege** [comment]
yep. as long as the extensibility points allow doing it - that's good enough.
