### ISSUE TITLE
Pre-populate the username field based on the value of login_hint

### ISSUE THREAD

**Issue by extremeboredom** [IdentityServer/Thinktecture.IdentityServer3#748]
The description of login_hint at http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest suggests that it is intended to be used for the OP to populate a username field on behalf of the user based on some information that the RP has already gathered.

The login_hint is currently ignored unless prefixed by 'idp:' or 'tenant:', after which it is used to populate that information instead. (https://github.com/thinktecture/Thinktecture.IdentityServer.v3/blob/2c0ef5f7dc3be0b804d1e1734dad634dc1288fad/source/Core/ResponseHandling/AuthorizeInteractionResponseGenerator.cs#L69)

Ensure that the value being sent in login_hint gets set as the initial value for the username field of the login page.

**Comment by leastprivilege** [comment]
done

**Comment by leastprivilege** [comment]
on the dev branch

**Comment by brockallen** [comment]
my part also done on dev.
