### ISSUE TITLE
AllowLocalLogin doesn't work

### ISSUE THREAD

**Issue by sidwall** [IdentityServer/Thinktecture.IdentityServer3#753]
The flag AllowLocalLogin doesn't seem to do anything.

**Comment by brockallen** [comment]
What flag? 

Just kidding -- we just removed it for now. We'll revisit post-RTM is it's a needed feature.

**Comment by sidwall** [comment]
OK, I thought it would be nice if the local login box was made invisible if AllowLocalLogin=false.

**Comment by leastprivilege** [comment]
Do you need that per client? We also have a global setting for that on the AuthenticationOptions.

**Comment by sidwall** [comment]
Yes, we use one STS for all our applications (https://apps.ivl.se/SecurityManager). Each of these applications have its own set of users that may origin from external sources or not.

**Comment by brockallen** [comment]
@leastprivilege we also need to check this in the authorize endpoint. for a user already logged in w/ an idp claim that is IdentityServer, we can't use that current logged in user if the client has EnableLocalLogin set to false.

**Comment by brockallen** [comment]
UI part done on dev
