### ISSUE TITLE
Adding to an Fsharp project causes compile error with Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver

### ISSUE THREAD

**Issue by gaspode44** [IdentityServer/Thinktecture.IdentityServer3#761]
I'm attempting to add identity server to a f# web api but when I add the package or manually add a reference to the identity server assembly I get a compile error with code that previuosly compiled without errors - the line that has the error is where a Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver is assigned

I'm using the pre-release version of the package - removing the reference fixes the error - it only happens with this assembly adding other references don't result on the same error

Is there something in identity server that could be masking the CamelCasePropertyNamesContractResolver type

I've posted this on SO (http://stackoverflow.com/questions/27940765/adding-reference-to-thinktecture-identityserver-3-causes-this-type-has-no-access) as its likely to be an F# issue but as it only occurs with this asm I thought I would add here as well

**Comment by leastprivilege** [comment]
tbh I don't know.

As a workaround - run idsrv in its own project.

**Comment by gaspode44** [comment]
I see source for core takes the newtonsoft dll as package dep - but the identity server nuget only lists owin - am I missing something? - pretty certain this is an odd f# issue and have posted to a couple f# places  - will update this issue if I get a resolution

**Comment by leastprivilege** [comment]
We internalize all dependencies using ILMerge - hence only OWIN as external dependency

**Comment by brockallen** [comment]
Having said that, if you're referencing IdentityServer from NuGet, then you should not be having conflicts with Json.Net.

**Comment by gaspode44** [comment]
maybe that explains it - not used ILMerge but does that mean that if I have a ref to the newtonsoft dll and identity server then there are potentially two conflicting implementations with the same type? - or is it more like a kind of inlining exercise?

**Comment by gaspode44** [comment]
this may be tripping up F# type inference I'm guessing

**Comment by brockallen** [comment]
In your project you should be using IdentityServer from NuGet/MyGet. Our use of Json.Net is internalized (sort of like static linking from the C++ days). Your app can then reference Json.Net and shouldn't see our use of it in any way.

If you do have a problem with this suggested approach, let us know.

**Comment by gaspode44** [comment]
ok will try building from src without ILMerge and try referencing the ouput and see if that is the cause

**Comment by brockallen** [comment]
Or use NuGet...

**Comment by gaspode44** [comment]
ok looks like that is the cause - simply referencing the un merged core asm does not break the code in the same way - not clear yet whether there is some switch I can set on ILMerge to solve it - don't think that F# is incompatible with ILMerge per se - its still producing IL - but looks like the merge operation seems to hide the default constructor in the newtonsoft type - I'll keep digging

**Comment by gaspode44** [comment]
just to clarify I was using nuget - thats when I first found the issue - referencing the merged dll causes the error , referencing the un-merged does not

**Comment by brockallen** [comment]
Hmm... maybe this is related: https://twitter.com/leastprivilege/status/555383167470026752

**Comment by brockallen** [comment]
So can we close this issue?

**Comment by gaspode44** [comment]
I haven't been able to get an answer to this from any F# experts - my gut feel is that its a bug in F# or the  F# compiler is simply incompatible with results of ILMerge - I also couldn't think of a nice way to have a version in nuget thats not merged and that lists the dependent packages - would perhaps be too confusing for new users

**Comment by brockallen** [comment]
Ok, thanks for the update.
