### ISSUE TITLE
InMemoryAuthorizationCodeStore.GetAsync removes item from store

### ISSUE THREAD

**Issue by appetere** [IdentityServer/Thinktecture.IdentityServer3#763]
The GetAsync method removes an item from the cache when it is requested, instead of just getting it:

    namespace Thinktecture.IdentityServer.Core.Services.InMemory
    {
      public class InMemoryAuthorizationCodeStore : IAuthorizationCodeStore
      {
        [...]
        public Task<AuthorizationCode> GetAsync(string key)
        {
            AuthorizationCode code;
            if (_repository.TryRemove(key, out code))
            {
                return Task.FromResult(code);
            }

            return Task.FromResult<AuthorizationCode>(null);
        }

I think the if statement should be:

            if (_repository.TryGetValue(key, out code))

**Comment by leastprivilege** [comment]
authZ codes are one time use only.

**Comment by brockallen** [comment]
Does this mean for the EF impl it will need to do the same? IIRC it does not currently.

**Comment by leastprivilege** [comment]
yea - we might need to change that - in any case - the authZ code needs to be removed "invalidated" after being used.

**Comment by appetere** [comment]
Ah ok, that makes sense now.  Thanks for clarifying.

**Comment by leastprivilege** [comment]
ok - the in-memory one is fixed.

no need for other code changes - idsrv calls remove on the store afterwards.
