### ISSUE TITLE
Handle idp acr_value when idp is IdentityServer

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/Thinktecture.IdentityServer3#767]
Such as only showing local login and no external providers.

**Comment by scottbrady91** [comment]
What's the value for doing this?

**Comment by brockallen** [comment]
We allow passing idp via acr_values to bypass HRD. I guess during development we missed a case where the idp was idsvr itself. So when we show the login page with idp of IdSvr we don't show any external providers. At least, that's my vague memory of what this was about.

**Comment by scottbrady91** [comment]
Thanks, I'll give it a go.

**Comment by scottbrady91** [comment]
idp value of IdSvr gives me an error. Any thoughts?

I am using the ws-fed whr value, but that shouldn't matter as this is identity server service stuff. It's also proven working for my external providers.

**Comment by brockallen** [comment]
Did you use this value? https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Constants.cs#L41

**Comment by scottbrady91** [comment]
Yeah, tried that. No luck (sorry about the delay).
