### ISSUE TITLE
Can you direct me to the extension point for adding custom scopes to the UserInfoEndpoint?

### ISSUE THREAD

**Issue by kalanbates** [IdentityServer/Thinktecture.IdentityServer3#781]
I want custom scopes configured in IdentityManager to be available on the identity tokens distributed by IdentityServer.  I've got IdS.MR running along with the Clients.[Javascript Implicit Client] and Clients.[SampleWebApi].  Inside my admin panel for IdM, I created a user with claims 
```
{name.first, 'K. Alan'}
{name.last, 'Bates'}
{foo, 'bar'}
```
I am wanting these custom claims to be returned in any identity token granted by my server, but when I run through an example, I see nothing but the stock claims returned.

On inspection, I see that ```GetClaimsFromAccount``` is loading the claims I expect, but they all get scrubbed out of the returned result because the only item in the requestedClaimTypes collection coming through the ```GetProfileDataAsync``` Endpoint is "sub."  

I traced back through the IdentityServer source to ```Core.ResponseHandling.UserInfoResponseGenerator``` upward and I see that the UserInfoEndpointController seems to only pass down claims with a Claimtype of ```Scope```

So my question is this:  Is this where I should be looking to push my custom claim types into my local implementation?  If so, am I looking at a custom build of IdentityServer's source to manipulate the requestedClaimTypes that get processed by the UserInfoEndpoint or is there some existing articulation point I'm not seeing that would allow me to push these requirements into IdentityServer without directly modifying your code?

**Comment by leastprivilege** [comment]
Check the docs

https://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/overview/terminology.html
https://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/configuration/scopesAndClaims.html

**Comment by JesseKlaasse** [comment]
I have the exact same problem as @kalanbates , and the documentation doesn't explain it for me. Can anyone point me in the right direction?

**Comment by leastprivilege** [comment]
open a new issue.

**Comment by sabby62** [comment]
@JesseKlaasse @kalanbates Did you guys manage to get this working ?
@leastprivilege @brockallen Is there a way of doing this ?

**Comment by JesseKlaasse** [comment]
Hi Sarfraz,

I managed to get it working:
https://github.com/IdentityServer/IdentityServer3/issues/1621

Cheers,
Jesse.
