### ISSUE TITLE
Refresh token does not update claims

### ISSUE THREAD

**Issue by RaulMo7** [IdentityServer/Thinktecture.IdentityServer3#784]
Hello friends.

In advance I apologize for my translation is not my native language.

I have the following problem or maybe I'm doing something wrong.

I wonder if it is possible that when you call the refresh token endpoint of the Claims are also updated.

My scenario is as follows:

I have a claim role that is updated at any time of application for any user, the problem is that when I try to recover the claim has yet updated after the above information, such as:

  _accountService.RemoveClaim (userId, "Viewer");
_accountService.AddClaim (userId, "Admin");

var currentUser = controller.User as ClaimsPrincipal;
             Debug.Assert (currentUser = null, "currentUser = null!"!);
             role var = ((currentUser.Identities.First ()
                 .Claims.Where (C => c.Type == Thinktecture.IdentityServer.Core.Constants.ClaimTypes.Role)
                 .Select (C => c.Value)) First ().);
            
             UserRole UserRole;
             UserRole.TryParse (role, out UserRole);

  // UserRole is equal to "Viewer"

This is a bug or am I doing something wrong?

I appreciate your help.

**Comment by leastprivilege** [comment]
Yes - that's a todo and missing right now - not sure if this will make it into the release next week (unlikely).

**Comment by RaulMo7** [comment]
Thanks, I'll pending.

**Comment by brockallen** [comment]
Closing because #573
