### ISSUE TITLE
MVC Authentication Sample

### ISSUE THREAD

**Issue by sportingdurutti** [IdentityServer/Thinktecture.IdentityServer3#798]
Hi
I've tested the MVC Authentication sample successfully but have some questions regarding the implementation of the flows used:
1 - The Client (MVC Web App) is authenticating using OpenIDConnect    (app.UseOpenIdConnectAuthentication) and on successfull authentication it gets both an id_token and an access_token. The flow used here is the Implicit flow. 
2 - The API is then called using both Client Credentials or the Access Token received in the authentication handshake (UserCredentials). In both cases the Client Credential Flow is used.

My questions are
1 - The first handshake is all about authenticating the user and have an id_token exchanged for claims that after will be used to protect the Actions in the MVC Client (Authorization Manager),  in fact the same approach used in WSFed with Claims Based Authentication. Why is the MVC Web App using the Implicit Flow? Is this a design choice (as i assume that in order to authenticate using OpenID Connect one needs to choose some OAuth Flow)?
2 - You also get an Access Token on the authentication Handshake. The Access Token is the used to call the API. 
a) How do i know if that specific Access Token is valid to allow the MVC Client to access the API (there is no explicit consent on the flow)? 
b) What is the following line doing "client.SetBearerToken(token)"?
c) Shouldn't be required some transformation for the Access Token delivered on the first handshake to the MVC Web App with another Acces Token granted from the MVC Web App to access the API on behalf of the user? Or the fact that we received an Access Token on the authentication handshake can be used as a Client Assertion that allows the MVC Client to access the API on behalf of the user?
d ) What kind of OAuth flow is this? It's defined as "Client Credentials"...
Best regards

**Comment by brockallen** [comment]
1) Implicit is used when you don't need code or hybrid for refresh tokens.
2a) The authorization response has the scopes granted.
2b) This sets the Authorization header with the token.
2c) I don't understand the question
2d) Read the spec.

**Comment by sportingdurutti** [comment]
As I undeestood
1) You've used Impliict as now Refresh TOken is needed
2a) Setting the scope tells that the token is for that API...(of course...)
2c) As such the Token you got is already valid for the API...
2d) ANd the either you use it as an "Act-As" token or you get another "On-behalf" (the MVC Client) access token to call the API ...
Sorry I'm still a newbie...

**Comment by brockallen** [comment]
All correct except for 2d. I guess I didn't understand your question 2d before. That sample is using implicit flow, I believe -- check the client configuration in IdentityServer. But I still think it's a good idea for you to read the spec.
