### ISSUE TITLE
Logout from ADFS

### ISSUE THREAD

**Issue by dubscott** [IdentityServer/Thinktecture.IdentityServer3#800]
When a user authenticates with ADFS and then tries to sign out from the client, their browser ends up on the ADFS sign-out page. I would like them to stay on the IdSrv logout page with the link back to the client. This works as expected when authenticating with Google or as an internal user (I'm sending id_token_hint from the client on logout request). 
I can see in Fiddler that the logout view is rendered but the result is a 302 redirect to the ADFS server.
Is this by design with ADFS or am I missing something? I'm using the RC source code from nuget but can't find how that redirect is happening`
The signout from the external provider probably still needs to happen, so is there a way to get back to the IdSrv3 logout page?

**Comment by dubscott** [comment]
Thanks for prompt reply. Is it possible to not log the user out of ADFS? What would be the repercussions of doing this? 
I tried setting the SignOutWreply property of the WsFederationAuthenticationOptions object and even though the wreply value was present in the URL when signing out, there was no redirection.
I don't know if this is unrelated, but the ADFS sign-out page has an iframe with source `https://my_id_svr.com/core/connect/token?wa=wsignoutcleanup1.0` and this results in a 405 error as the TokenEndpointController has no GET method. ADFS is configured with /core/connect/token as the WS-Federation Passive endpoint.

**Comment by brockallen** [comment]
Right -- the Katana middleware does not implement that part of the WS-Fed spec. I just asked them recently to finally implement it (but no reply): https://github.com/aspnet/Security/issues/43#issuecomment-70909158

As for not logging them out of ADFS -- well, I don't know your environment. You'd have to think about it and decide for yourself. Usually the requirement is that once they user wants to logout, then they get logged out everywhere (barring any incomplete implementations of the protocol).

**Comment by dubscott** [comment]
ok, for now I'll ignore that 405 error in the iframe.
If I wanted to leave my users logged into ADFS, is this an option out of the box? Are there any examples? 
Some more digging around the wreply at sign-out revealed ADFS will redirect if the wreply is the same as the configured Ws-Fed endpoint. In my case, it is `https://my_id_srv.com/core/connect/token`. This endpoint does not accept a GET request so the redirect fails. Is this a piece of fuctionality that's missing from IdentityServer? Or should I be using a different endpoint?
Thanks

**Comment by brockallen** [comment]
How you interact with ADFS is up to you in how you configure the WSFed Katana middleware.
