### ISSUE TITLE
PromptMode = "select_account"

### ISSUE THREAD

**Issue by evilgamr** [IdentityServer/Thinktecture.IdentityServer3#801]
Hello,

We look forward to support multiple "accounts" associated with a single login. The user tipically selects the desired account when signing in to one of our applications and this selection is retained when connecting to another of our applications. In some cases the account to be used is "pre-selected" or "suggested" using a querystring parameter and in some other cases the account selection is forced despite of already existing a previous selection.

We expect to handle the selected account using a claim in id and access tokens.

I've read about the "select_account" prompt mode in the OpenID Connect specification and found it is not supported in Identity Server v3.
Do you have plans to implement a basic support for it? Do you have further information about its intended usage?

**Comment by brockallen** [comment]
We don't have built-in support for this right now. You might be able to do this yourself, though, between a custom user service and view service.

**Comment by evilgamr** [comment]
We have already tried with this, but we are stuck trying to change the selected account when connecting to a second application. The custom user service is not hit because authentication is already done, and we dont want the user to do a full login again (login and password)

**Comment by brockallen** [comment]
We do support prompt=login, which will show the login screen. Maybe that works well enough for you?

**Comment by coreyperkins** [comment]
I'd like to use prompt=select_account. This case made the release notes for 1.0.0. I use a custom view service to inject my own views. Auth is configured like so:

app.UseOpenIdConnectAuthentication(new Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationOptions {
                Authority = string.Format("{0}/identity", hostSetting),
                ClientId = "client-ig",
                RedirectUri = string.Format("{0}/acct/auth", hostSetting),
                ResponseType = Thinktecture.IdentityServer.Core.Constants.ResponseTypes.IdToken,
                SignInAsAuthenticationType = "Cookies"                
            });

How would I go about configuring this so that my users have to pick the account each time?

Thanks!
