### ISSUE TITLE
Enhancement at the login page - PRG

### ISSUE THREAD

**Issue by johnkors** [IdentityServer/Thinktecture.IdentityServer3#803]
As a user
When I try to login in the login page
And I get validation errors on the subsequent page load
And I hit F5
I don't want to get "Confirm form resubmission" message from the browser

![image](https://cloud.githubusercontent.com/assets/206726/5861010/03e4ae84-a266-11e4-8a96-86aeb0ff86df.png)

If possible, implementing the PRG pattern would solve this.

**Comment by brockallen** [comment]
If we did a redirect on this, then we'd lose the entered username. I don't see us changing this, unless you have an example of some other app out there that handles this smoothly.

**Comment by johnkors** [comment]
For MVC, I believe the most common (or simplest) way to achieve this is using TempData which survives a redirect. Not sure how to achieve the same effect for Web API controllers thou (TempData is prob a MVC thing).

**Comment by brockallen** [comment]
Well, that's done as a cookie. I don't think we need anymore cookies for now... maybe once we're on ASP.NET 5 something like this might be slightly easier.

**Comment by johnkors** [comment]
Okay, another approach is to let this POST be able to return JSON if a request was done via AJAX (and the login failed). That way we could avoid it alltogether and just wire the error msg ourselves clientside (Angular).

```
        [Route(Constants.RoutePaths.Login)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IHttpActionResult> LoginLocal(string signin, LoginCredentials model)
```

I haven't tried it, but seeing as this Controller is using the ```PreventUnsupportedRequestMediaTypes``` attribute - JSON is not available atm ?

**Comment by brockallen** [comment]
Maybe next version once razor can be used.

That attribute is to prevent unexpected inputs and side effects (for security reasons).
