### ISSUE TITLE
UserService is instantiated twice

### ISSUE THREAD

**Issue by michaeldotknox** [IdentityServer/Thinktecture.IdentityServer3#804]
We're using the release candidate for IdentityServer and I've noticed an issue with the instantiation of the user service; it appears to be instantiated twice.  Here is the relevant code in my startup.cs:
```
var factory = new IdentityServerServiceFactory
            {
                ClientStore = new Registration<IClientStore>(typeof(DefaultClientStore)),
                ScopeStore = new Registration<IScopeStore>(typeof(DefaultScopeStore)),
                UserService = new Registration<IUserService>(typeof(SimpleUserService)),
                ClaimsProvider = new Registration<IClaimsProvider>(typeof(SimpleClaimsProvider)),
            };
```

The SimpleUserService class is very simple, a very stripped down version of my real user store:
```
public class SimpleUserService : IUserService
{
    public SimpleUserService()
    {
    }

    public Task<AuthenticateResult> PreAuthenticateAsync(SignInMessage message)
    {
        throw new System.NotImplementedException();
    }

    public Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message)
    {
        return Task.FromResult(new AuthenticateResult(username, username));
    }

    public Task<AuthenticateResult> AuthenticateExternalAsync(ExternalIdentity externalUser, SignInMessage message)
    {
        throw new System.NotImplementedException();
    }

    public Task SignOutAsync(ClaimsPrincipal subject)
    {
        throw new System.NotImplementedException();
    }

    public Task<IEnumerable<Claim>> GetProfileDataAsync(ClaimsPrincipal subject, IEnumerable<string> requestedClaimTypes = null)
    {
        throw new System.NotImplementedException();
    }

    public Task<bool> IsActiveAsync(ClaimsPrincipal subject)
    {
        throw new System.NotImplementedException();
    }
}
```
In this example, the constructor for the SimpleUserService is called, then the constructor for the DefaultScopeStore, then the constructor for the SimpleUserService again.

Is this expected behavior?

**Comment by leastprivilege** [comment]
Yes - that's normal.

**Comment by brockallen** [comment]
Yep. Docs explain this: https://thinktecture.github.io/Thinktecture.IdentityServer.v3.Documentation/docs/advanced/customServices.html

**Comment by michaeldotknox** [comment]
So a colleague pointed out that I may not have been clear when I explained the issue.  This happens on every call into the Token endpoint, not on start up.  This means that the user service is created twice for every call, every time someone requests a token.  If I create a singleton, it obviously does not happen (which I would expect), but it seems odd that for every call that the user service (and any of its dependencies) would be created exactly twice.  That potentially could be a lot of memory and/or processing overhead.
Unless I am missing something.  You guys know far more about this than I do.

**Comment by brockallen** [comment]
Generally this won't be a huge issue since the CG is optimized for short lived Gen0 objects, but you do have a point -- it needs to be configurable. We'll do this post-RTM: #810.
