### ISSUE TITLE
Explicit enum values

### ISSUE THREAD

**Issue by ManuelRauber** [IdentityServer/Thinktecture.IdentityServer3#808]
It would be nice if all the enum values could get explicit values, so they will not change when reordering. I'm currently using them to build the Identity Server Admin UI and map directly to the original enum values. 
If they ever change, it could get a bit messy. :)

**Comment by brockallen** [comment]
I've now set them all explicitly. I set them to what their current default values would be set by the compiler. 

Can you think of any reason to have them not use the value `0`? IOW, set the first one at `1` and the next one at `2`, etc?

**Comment by ManuelRauber** [comment]
I would rather suggest to do it as the compiler does, so it would not break current running systems. 

re your question: Sometimes I use "0" for "Unknown" value, so you have to explicitly set it to > 0 for an actual value. But I think we are fine here with the compiler default values. 

Thanks!
