### ISSUE TITLE
Post RTM: Solution for being able to authenticate users from trusted domains outside idsrv domain.

### ISSUE THREAD

**Issue by s093294** [IdentityServer/Thinktecture.IdentityServer3#809]
So the main feedback that I got from up management on our current solution with Identity Server is that they dislike that they have to go to idsrv to enter local account information. In all other aspects its been possible for me to hide idsrv by acr_values for idp hints. 

Main feedback was they wanted the signup and login page to be more like facebook. Accept username + password for login and if not authenticated also show a form for registration.

I seen a few people talking about embeded idsrv as a iframe also, to me this sounds like them trying to do a solution for the same "problem" that i describe above. 

I havent been able to find anything in the specs that would allow me to create this experience. 
I touched the topic of possible, from a trusted domain do a authorization post to idsrv with username and password in acr_values and then in the PreAuthenticate do the login based on these. To me this sounds like a valid solution. As long as some kind of xsrf and only posts from trusted domains are allowed. 

I am bringing this up to discuss it for after RTM if its something that can be found a better solution for. I atleast think I wont be the first tech guy being questioned by there bosses if we can do it like this.

**Comment by brockallen** [comment]
Have the registration system generate a nonce and put in the registration DB. Then use acr_values and pass the nonce to IdSvr. Use PreAuthenticate to verify the nonce in the DB to know the user, delete the nonce from the DB, and log the user in.

**Comment by s093294** [comment]
Cool. That solves the extra step of authentication in the registration process.  

Any commen on when a returning user then comes and want to enter username,password on our main portal page other than possible passing them with acr_values also.

**Comment by brockallen** [comment]
Hmm, not sure that's a good idea. I think Dom already told you this was a bad idea.
