### ISSUE TITLE
Question: Claims transformation and first time registration for third party Id Server.

### ISSUE THREAD

**Issue by pavanputhra** [IdentityServer/Thinktecture.IdentityServer3#816]
Right now Identity Server 3's flow is as follows. (AFAIK)

1. When client needs to authenticate user, client sends request to authorization endpoint.
2. Identity Server shows username and password form.
3. User enters proper credentials and token are passed back to client.

I want to modify flow as follows.

1. When client needs to authenticate user, client sends request to authorization endpoint.
2. Identity Server shows username and password form along with the link to third party OAuth servers, example Google, Facebook.
3. If username and password are entered, normal flow will continue as specified above. Flow ends here.
4. If third party OAuth link is clicked, for example, Google, user is authenticated via Google and token is given back to Our Identity Server.
5. If user is first time visitor he/she will be redirected to registration form which asks few more data or else continue to step 6.
6. Using nameidentifier claim specified in Google's token, previously registered data (claims) of user is fetched from database. New token is generated from our Identity server and given to client ( Equivalent of claims transformation of WS-Federation )

My question is:

Is there a mechanism currently in Thinktecture Identity Server v3 for the modified flow. If so how can I achieve it? If no then, I want to build such extension to Thinktecture Identity Server v3, can you guys help me by providing appropriate guidance?

**Comment by leastprivilege** [comment]
sure - check the samples for custom user service.

**Comment by pavanputhra** [comment]
I went through examples. If user is unregistered, I would like to get users profile info and register automatically. If am using Google as Id Provider, i need to get info from ` https://www.googleapis.com/plus/v1/people/userId`. If am not wrong I would need `access_token` to fetch more info. How can I get access to `access_token` in following method?

```csharp
public Task<AuthenticateResult> AuthenticateExternalAsync(ExternalIdentity externalUser, SignInMessage message)
        {
            if (externalUser.Provider == "Google" && firstTimeUser)
            {
                //TODO get profile info.
            }
            return Task.FromResult<AuthenticateResult>(null);
        }
```

**Comment by leastprivilege** [comment]
You need to configure the google middleware to ask for the scopes that you are interested in.

**Comment by pavanputhra** [comment]
I tried adding scopes as follows, but both options returns only `urn`, `name`, `first_name`, `family_name` and `email` claims. I need `gender` and `birthday` as well.

```csharp
        private static void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
        {
            var googleAuthOption = new GoogleOAuth2AuthenticationOptions
            {
                AuthenticationType = "Google",
                Caption = "Sign in with Google",
                SignInAsAuthenticationType = signInAsType,

                ClientId = ConfigurationManager.AppSettings["GoogleAuthClientId"],
                ClientSecret = ConfigurationManager.AppSettings["GoogleAuthClientSecrete"]
            };
            googleAuthOption.Scope.Add("openid");
            googleAuthOption.Scope.Add("profile");
            googleAuthOption.Scope.Add("email");
            app.UseGoogleAuthentication(googleAuthOption);
        }
```


```csharp
        private static void ConfigureIdentityProviders(IAppBuilder app, string signInAsType)
        {
            var googleAuthOption = new GoogleOAuth2AuthenticationOptions
            {
                AuthenticationType = "Google",
                Caption = "Sign in with Google",
                SignInAsAuthenticationType = signInAsType,

                ClientId = ConfigurationManager.AppSettings["GoogleAuthClientId"],
                ClientSecret = ConfigurationManager.AppSettings["GoogleAuthClientSecrete"]
            };
            googleAuthOption.Scope.Add("https://www.googleapis.com/auth/plus.me");
            googleAuthOption.Scope.Add("https://www.googleapis.com/auth/plus.login");
            googleAuthOption.Scope.Add("https://www.googleapis.com/auth/plus.profile.emails.read");
            app.UseGoogleAuthentication(googleAuthOption);
        }
```

**Comment by leastprivilege** [comment]
Maybe you need to handle a notification - this is MS code - maybe ask in the OWIN room on Jabbr.

**Comment by brockallen** [comment]
All set on this issue, or still questions?

**Comment by pavanputhra** [comment]
No questions. Issue didn't got solved. As I get the solution I will post it here.

**Comment by brockallen** [comment]
I'll close this since it's not an IdentityServer issue. Once you find out the Katana issue, please feel free to follow up here.
