### ISSUE TITLE
implementing support for ASP.NET SQL Membership

### ISSUE THREAD

**Issue by erickrivas** [IdentityServer/Thinktecture.IdentityServer3#817]
I'm unable to upgrade to ASP.NET Identity any time soon. How easy would it be to add support for ASP.NET SQL Membership?

**Comment by leastprivilege** [comment]
Not hard - check the docs.

**Comment by erickrivas** [comment]
OK, thank you. Will look at the docs and perhaps add a pull request for ASP.NET SQL Membership support. :  BTW, IdentityServer looks awesome, what a time saver and done right.

**Comment by leastprivilege** [comment]
No need to PR - we'd rather prefer you would put the membership support in your own repo - and maintain it ;) We will link to it from our docs.
