### ISSUE TITLE
Injecting IClientStore and MessageCookie<SigninMessage> to MVC controllers

### ISSUE THREAD

**Issue by rklachko** [IdentityServer/Thinktecture.IdentityServer3#819]
In my IDS host I implemented some custom behavior, mainly around "registration" and "forgot my password" features. I implemented custom user service, custom view service and more. Inside my MVC controllers I want to use the client store, and I want to use the SigninMessage from the cookie.

Before the RC release I was able to inject the Client Store by registering it with the MVC container like this:
```
builder.Register(c => HttpContext.Current.GetOwinContext().Environment.ResolveDependency<IClientStore>()).AsSelf().InstancePerRequest();
```
But now the ResolveDependency has became Internal and can't be used like that.

About the SigninMessage. Before the RC I could get it like this:
```
var cookie = new MessageCookie<SignInMessage>(HttpContext.GetOwinContext().Environment, _options);
var signInMessage = cookie.Read(model.Signin);
```
But now I can't do it, because MessageCookie constructors became internal as well.

With the latest RC I tried a different way to register it with the MVC container:
```
var scope = HttpContext.Current.GetOwinContext().Get<ILifetimeScope>(Constants.OwinEnvironment.AutofacScope);
builder.Register(c => (IClientStore)scope.Resolve(typeof(IClientStore))).AsSelf().InstancePerRequest();
builder.Register(c => (MessageCookie<SignInMessage>)scope.Resolve(typeof(MessageCookie<SignInMessage>))).AsSelf();
```
This failed with the error: "No owin.Environment item was found in the context."

I then tried to resolve my needed classes directly inside the controller actions:
```
var scope = HttpContext.GetOwinContext().Get<ILifetimeScope>(Constants.OwinEnvironment.AutofacScope);
var signInMessageCookie = (MessageCookie<SignInMessage>)scope.Resolve(typeof(MessageCookie<SignInMessage>));
```
But some inconsistency with Autofac versions prevents this from working, LifetimeScope from the Owin Context fails to cast to ILifetimeScope.

Any ideas how to achieve the injection of the ClientStore and MessageCookie (or signin message) to my MVC controllers? A sample would be very helpful.

**Comment by rklachko** [comment]
Maybe #614 should help me with this?

**Comment by brockallen** [comment]
I'm not clear on why you'd need to inject or pass the signin message to your controllers -- that's certainly not something we've designed for. If you want registration controllers, then put those into a (logically) separate application from IdentityServer. We didn't design for our server to intermingle with other application frameworks. It can run in the same host, that's fine, but not at the framework level.

**Comment by B3nCr** [comment]
@brockallen  I know this is reviving an old question but I'm trying to get my head around the new user registration flow. Do you mean do registration in a completely different website (i.e. the app that begain the auth request) or do you mean do it in a separately mapped section of the same application using app.Map type partitioning? The custom user sample seems to have the registration view in the same logical application as identity server.

**Comment by brockallen** [comment]
I think all I was saying was that you can run your "stuff" next to IdSvr in the same host.

**Comment by B3nCr** [comment]
Yeah but host might have meant host server or host process or host IIS.

**Comment by brockallen** [comment]
OWIN host

**Comment by B3nCr** [comment]
Okay so if I'm hosting in IIS, which I am, it's perfectly acceptable to add
my "stuff" in the same Visual Studio web project and IIS web application
but I should try to keep it separate from the IdentityServer application,
presumably that means by mapping it with it's own route prefix and giving
it it's own config.

I'm still a little confused though about how I'd use the user service from
my registration controller. I saw something that suggested using it to do
some pre-authenticate after registration so you don't have to register then
sign in.

**Comment by brockallen** [comment]
You'd not use the user service. Rather you'd use the same identity management library or database from your registration pages.
