### ISSUE TITLE
Consent page

### ISSUE THREAD

**Issue by imperugo** [IdentityServer/Thinktecture.IdentityServer3#822]
Hi, 
I've updated to the RTM my project and now it seems that the user must allow the scopes after login.

With the previously beta it was not mandatory, in fact I didn't get this page before. To exclude this I've implement my IConsentService in this way:

```csharp
public class BmwConsentService : IConsentService
	{
		public Task<bool> RequiresConsentAsync(Client client, ClaimsPrincipal subject, IEnumerable<string> scopes)
		{
			return Task.FromResult(false);
		}

		public Task UpdateConsentAsync(Client client, ClaimsPrincipal subject, IEnumerable<string> scopes)
		{
			return Task.FromResult(0);
		}
	}
```

Is this the best way to do that?
Thanks

**Comment by leastprivilege** [comment]
No.

Set RequireConsent on the Client to false.

**Comment by imperugo** [comment]
Cool.
Thx
