### ISSUE TITLE
Question: Windows Authentication

### ISSUE THREAD

**Issue by sherland** [IdentityServer/Thinktecture.IdentityServer3#823]
My goal is to authenticate users with Windows Authentication instead of username/password (on IIS). 
How would you recommend this integrated in IdentityServer?

(There is some info about how to configure IIS at http://www.asp.net/aspnet/overview/owin-and-katana/enabling-windows-authentication-in-katana - but I assume the identity will have to be picked up somewhere in IdentityServer)

**Comment by leastprivilege** [comment]
Testing this out is still on our todo list. Before that I cannot say for sure what needs to be done.

Try configuring Windows auth (no anonymous access) and handle the PreAuthenticateAsync in the UserService (that's where I would start)

**Comment by leastprivilege** [comment]
I did some research - and adding support for native Windows auth will require some changes. For now using ADFS (or a mini WS-Fed based Windows Auth STS) would be the workaround.

**Comment by sania13** [comment]
We are very much interested in that feature ( native Windows auth  ) also. Thank you.

Any rough estimates when it might be available?

**Comment by tracsorenson** [comment]
This feature +1 for me too!

**Comment by sania13** [comment]
Would be nice to have Windows Authentication similar to this example in 'ASP.NET MVC 5 Mixed Authentication"

https://github.com/MohammadYounes/MVC5-MixedAuth

**Comment by sherland** [comment]
Do you know about any mini WS-Fed based Windows Auth STS? - Preferably one that use owin and that can be embeded into the same site...

**Comment by leastprivilege** [comment]
I would have to write it first.

**Comment by sherland** [comment]
Is that a promise? ;-)

**Comment by leastprivilege** [comment]
no that's saying I would need to write that. And I don't have time for it right now. Unless you wanna pay me for it ;)

**Comment by sherland** [comment]
That could be an option - depending on what we get for which price, and when we get it...
The best would of course to for this to be part of, or easily integrated into IdentityServer whith minimal configuration. 

(The problem is that we are installing a beta of our application at a customer site next Wednesday, and we have to verify that authentication is working some time before that...)

**Comment by leastprivilege** [comment]
you can contact me here:

dbaier@leastprivilege.com

**Comment by sherland** [comment]
I sent you an email.

**Comment by sania13** [comment]
Anything updates on this feature? ... or you have any tips or suggestions how to implement it?

**Comment by leastprivilege** [comment]
I worked on a small Windows token to JWT converter. Works fine. - I will open source in a couple of weeks.

**Comment by sania13** [comment]
Would it be implemented as Windows Authentication OR Local Authentication (if not part of Local Domain)?

**Comment by leastprivilege** [comment]
yes

**Comment by ggoebel** [comment]
leastprivilege++: has the windows token to jwt converter been open sourced and checked in to this github repo?

**Comment by leastprivilege** [comment]
No. Not yet.

**Comment by kebonarjee** [comment]
@leastprivilege Do you have any advice on how to modify an existing openid connect relying party to use the WindowsAuthenticationService ?

**Comment by leastprivilege** [comment]
You would add it to IdSrv as an external idp (use the WsFed middleware).

**Comment by kebonarjee** [comment]
Thanks for such a quick reply! (and the software of course)

**Comment by ggoebel** [comment]
leastprivilege++: Any ETA on an open source release of your small Windows token to JWT converter?

**Comment by brockallen** [comment]
@ggoebel it's here: https://github.com/IdentityServer/WindowsAuthentication

**Comment by ggoebel** [comment]
Thank you!
