### ISSUE TITLE
Reverse proxy redirect issue

### ISSUE THREAD

**Issue by stuartraines** [IdentityServer/Thinktecture.IdentityServer3#824]
Hi,

We have our relying party set up on the same domain as the identity server site, except that the relying party will run under https, whereas the relying party is only http.

We have a proxy that sits in front of these two sites and routes traffic accordingly. The site configuration is roughly:

Proxy - Both https (port 443) and http (port 80) bindings.
Relying party - http binding only (port 8000)
Identity Server - http binding only (port 8001)

Any requests that come into the proxy under SSL are rewritten to http port 8001, and rewritten to port 8000 for non-ssl requests.

We have configured the IdentityServerOptions.PublicHostAddress to the https binding, and we've configured the relying party with the public address, without the local port number.

On authenticating ourselves against the identity server, we're being redirected to the local port address of the relying party - :8000. This problem also occurs when accessing a restricted page within the identity server site itself, we end up on port 8001 after being issued a token.

I hope I've been clear enough, but please let me know if not. Are there any settings that we're missing?

**Comment by leastprivilege** [comment]
First update to RTM.

You need to configure both PublicOrigin and the client redirect URI to the host names as the browser would "see" them.

**Comment by stuartraines** [comment]
We're on RC at the moment, and we will update to RTM shortly. (Great work btw!) Where can I find the client redirect URI configuration?

**Comment by leastprivilege** [comment]
On the client class.

**Comment by stuartraines** [comment]
I thought those classes are only applicable if you're using OpenID or OAuth, which we're not?

**Comment by leastprivilege** [comment]
so what are you using?

**Comment by stuartraines** [comment]
We're using WS-Federation

**Comment by leastprivilege** [comment]
ah - you didn't mention that.

Well in that case it is called ReplyUrl.

**Comment by stuartraines** [comment]
Sorry :). We do have the reply url set to http://<our site domain>/ (as the browser should see it). 

Could it be anything to do with the WsFederationController - at the point it creates the WSFederationMessage, it uses the RequestUri, which includes the full request uri including port number. 

I'm clutching at straws here a bit.

**Comment by leastprivilege** [comment]
well - I guess you need to debug and test it - I haven't encountered that issue yet.

When you find the problem - you can open a PR.

Oh - and btw - having a RP on http is a really bad idea - then the tokens are sent over unsecured transport.

**Comment by stuartraines** [comment]
Ok, thanks for your help. It has been discussed to introduce SSL across the whole site, so thanks for the advice!

**Comment by stuartraines** [comment]
I found the issue in the end, it was down to how our proxy was set up. It was not rewriting the host name based on the origin request. This is now resolved.
