### ISSUE TITLE
Token duration

### ISSUE THREAD

**Issue by imperugo** [IdentityServer/Thinktecture.IdentityServer3#825]
Hi, 
I've a client application that use Hybrid Flow to authenticate users with a custom IUserService.
I wanna increase the duration of the token (basically I got a redirect to idsrv every 5 minutes).
What's the right property to do that?

**Comment by leastprivilege** [comment]
Once the client application has verified the id token - it is up to the app to manage the session lifetime (using the cookie middleware).

Set UseTokenLifetime to false on the OIDC MW to take over control.

**Comment by imperugo** [comment]
Hi @leastprivilege 
I think I did this:

```csharp
app.UseCookieAuthentication(new CookieAuthenticationOptions
			{
				AuthenticationType = "Cookies",
				CookieName = "mycookiename",
				CookieDomain = urlBuilder.Home.Domain
			});
```

and, for idsv:

```csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
			{
				Authority = securityConfig.IdentityServerEndpoint.ToString(),
				ClientId =Security.Constants.IdentityClients.AuthClientId,
				RedirectUri = urlBuilder.Account.Home.ToString(),
				SignInAsAuthenticationType = "Cookies",
				UseTokenLifetime = false,
				Scope = "openid profile roles email read write",
				ResponseType = "code id_token token",
```

What's wrong here?

**Comment by leastprivilege** [comment]
well - maybe set the cookie lifetime - looks good to me

**Comment by imperugo** [comment]
Lol.
I was thinking the cookie timeout was the same of the session, 20 minutes by default, probably I'm wrong. 

Let me try to increase that value.
