### ISSUE TITLE
Reference Token Validation throws exception

### ISSUE THREAD

**Issue by TD49** [IdentityServer/Thinktecture.IdentityServer3#826]
While we have successfully retrieved and validated self-contained JWT-based Access Tokens, I'm having issues validating a Reference Token type using the token validation endpoint (with the default in-memory ```TokenValidationStore```).

Request to the validator (using a fake ref token for this post):  
```https://myidsvr3/core/connect/accesstokenvalidation?token=2fc954023e5f71286ac5d018e301f8f7 GET```

It fails with a System.NullReferenceException when adding claims to the ClaimsIdentity, starting here:  https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Services/Default/DefaultCustomTokenValidator.cs#L78

Stacktrace snippet:
```
ExceptionType: "System.NullReferenceException"
StackTrace: " at System.Security.Claims.ClaimsIdentity.SafeAddClaims(IEnumerable`1 claims) at System.Security.Claims.ClaimsIdentity..ctor(IIdentity identity, IEnumerable`1 claims, String authenticationType, String nameType, String roleType, Boolean checkAuthType) at System.Security.Claims.ClaimsIdentity..ctor(IIdentity identity, IEnumerable`1 claims, String authenticationType, String nameType, String roleType) at Thinktecture.IdentityServer.Core.Services.Default.DefaultCustomTokenValidator.<ValidateAccessTokenAsync>d__4.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Services\Default\DefaultCustomTokenValidator.cs:line 78 
```
Note that, for the above example, there are no custom claims or anything special being added or used with the Client.  The token was originally retrieved through an RO grant type request. We're using IdSvr3 RTM released yesterday.  Any ideas?

**Comment by TD49** [comment]
Client details:
```C#
new Client
{
    Enabled = true,
    ClientName = "CustomApp",
    ClientId = "customapp",
    ClientSecrets = new List<ClientSecret> { new ClientSecret("customsecret".Sha256())},
    AccessTokenType = AccessTokenType.Reference,
    AccessTokenLifetime = 300,
    RefreshTokenUsage = TokenUsage.OneTimeOnly,
    RefreshTokenExpiration = TokenExpiration.Absolute,
    AbsoluteRefreshTokenLifetime = 86400, // one day
    SlidingRefreshTokenLifetime = 43200,
    Flow =  Flows.ResourceOwner
}
```

**Comment by leastprivilege** [comment]
have you debugged it?

**Comment by leastprivilege** [comment]
i just tried to repro it. works for me.

Try with the RO flow sample from the Clients solution (sample repo together with the core source code repo) and see if that works for you when you switch the token type to reference.

**Comment by TD49** [comment]
Yes.   

I was off by one line earlier, the Claims in the ```TokenValidationResult``` at https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Services/Default/DefaultCustomTokenValidator.cs#L78 are populated.   

When it attempts to validate the access token in async is where it loses track here https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Validation/TokenValidator.cs#L161.   I can't debug any further, as it then jumps to the Logger to log the exception listed in the earlier stacktrace above.

**Comment by TD49** [comment]
Ok, just caught your comment about the samples repo.  I'll give that a try.

**Comment by leastprivilege** [comment]
As I said - download the source code and the client repo and debug it.

**Comment by TD49** [comment]
You're correct, I couldn't repro using the IdSvr3 Core host from the source code repo (master).     

The only difference on our setup is that we're using a custom user service to validate credentials, but that shouldn't cause our issue as a reference token is still being issued.  The validation endpoint is able to trap it when the reference token is expired or invalid (with the "invalid_token" response).   Plus I can see the claims.    From the earlier stacktrace, I take it somehow a custom claim is being added that it can't process...  I'll keep digging, at a loss for the moment.

**Comment by leastprivilege** [comment]
Well - maybe you IsActiveAsync implementation does not return true...?

**Comment by TD49** [comment]
Nope, I verified it returns true on debug.   

However, I just noticed we had a custom ```IClaimsProvider``` type still registered that was forgotten during testing.  Removing that registration to use the default provider "fixes" the problem, but I want to check the logic within the custom type to see if adding custom claims is causing this issue.   Shouldn't take long...

**Comment by TD49** [comment]
Ok, the custom ```IClaimsProvider``` type had dev code that was adding a NULL claim to the claims list.  If the custom user service didn't add a "MyCustomClaim", then the claims provider can't find it and ends up adding a NULL claim per the logic below:

```C#
public override async Task<IEnumerable<Claim>> GetAccessTokenClaimsAsync(ClaimsPrincipal subject, Client client, IEnumerable<Scope> scopes, ValidatedRequest request)
    {
        var claims = await base.GetAccessTokenClaimsAsync(subject, client, scopes, request);

        var newClaims = claims.ToList();
        newClaims.Add(subject.FindFirst("MyCustomClaim"));   // BAD!

        return newClaims;
    }
```
So when the token is validated, it balks on that NULL.   Not a very informative exception, but it's accurate.  So a simple dev fix for this scenario:

```C#
        // newClaims.Add(subject.FindFirst("MyCustomClaim"));   // BAD!
        var newClaim = subject.FindFirst("MyCustomClaims"); 
        if (newClaim != null)
            newClaims.Add(newClaim);
```
So this isn't a bug with IdSvr, but just something to watch out for when messing with custom claims in the provider...
