### ISSUE TITLE
Identity Server Configuration

### ISSUE THREAD

**Issue by sportingdurutti** [IdentityServer/Thinktecture.IdentityServer3#827]
Hi
I´ve been playing with the samples and manage to
1 - Host Ientity Manager on IIS
2 - Host Identity Server on IIS
Identity manager is configured to use both ASPnetIdenity and membershipreboot (i have cheked that two difrent databases are created)
For Identity Server i could only configure with ASPnetIdenity as with the membershipreboot configuration the code is looking for some .mdf file in AppData folder wich is missing
1 - What is the correct config for Identity Server in order to use the same membershipreboot config as the one used in Identity Manager?
2 - Can i also use some database configuration for clients and scopes (not only for user management and authentication) as the samples i have seen are using an Inmemory Config?

**Comment by johnkors** [comment]
Implement IUserService, IClientStore and IScopeStore. The documentation is here: http://identityserver.github.io/Documentation/docs/

**Comment by leastprivilege** [comment]
We also have a repo with EF based implementations.

**Comment by sportingdurutti** [comment]
Ok, i've managed to configure both Identity Manager and Identity Server to use ASPnetIdenity (hosted on IIS in diferente URL's). 
1. Do i still need to configure Identity Manager in Identity Server like
appBuilder.Map("/admin", adminApp =>
            {
                var factory = new IdentityManagerServiceFactory();
                //factory.Configure("MyIdentityDb");
                adminApp.UseIdentityManager(new IdentityManagerOptions()
                {
                    Factory = factory
                });
            });
or its enough to use in Identity Server something like
            var idSvrFactory = Factory.Configure("IdSvr3Config");
            idSvrFactory.ConfigureUserService("MyIdentityDb");
and the use idSvrFactory in IdentityServerOptions ?
2. When logging in with a invalid credentials i get "Error: Invalid username or password" which means that Identity Server is connecting to MyIdentityDb. However when i use a valid user created in Identity Manager and with valid credentials i get "There was an unexpected error". Any Ideai?
3. Whe using MembershipReboot instead on both Identity Manager and Identity Server a new database is created with a new schema. But i always get "Error: Invalid username or password" using both a valid or invalid credentials (username & password). Any Ideai? When using InMemory for authenticating users on Identity Server it works ol

**Comment by brockallen** [comment]
1) You can configure IdMgr anyplace you want. In fact, you don't even have to use it. It's separate from IdSvr.

2) Enable logging to see what's going on.

3) Again, try logging to see the error.
