### ISSUE TITLE
Owin env removed from the IViewService

### ISSUE THREAD

**Issue by mynkow** [IdentityServer/Thinktecture.IdentityServer3#829]
What is the reason to remove the Owin env from the IViewService => https://github.com/IdentityServer/Thinktecture.IdentityServer3/commit/d132f6d4927ccd44ff4f6b5db39369101977943a

I guess because there is OwinEnvironmentService to use instead, right?

**Comment by leastprivilege** [comment]
You can now inject the OwinEnvironmentService into any of your classes. This gives you the environment.
