### ISSUE TITLE
WelcomeController + WsFederationController have same routes

### ISSUE THREAD

**Issue by rayph** [IdentityServer/Thinktecture.IdentityServer3#830]
We are using IdSrv + WsFederation. It seems the introduction of the WelcomeController with RoutePrefix of "" is resulting in a match for multiple controllers

I.e.: "Multiple controller types were found that match the URL"

Any chance we can make the routes more configurable or avoid this type of conflict?

(For now we modified the route prefix for the WelcomeController in a snapshot of the code and everything else works as it had before the update)

**Comment by leastprivilege** [comment]
Check the sample from the samples repo - it has both a welcome page and ws-fed - and is working. What's different in your project?

https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/tree/master/source/SelfHost%20(InMem%20with%20WS-Fed)

**Comment by rayph** [comment]
We are using SystemWeb/IIS instead of Self Host, would this cause the problem?

**Comment by leastprivilege** [comment]
Well - give it a try and let us know.

**Comment by rayph** [comment]
Self Host seems fine, but in a web context the 2 controllers match the same route for some reason, the WsFed plugin is mapped to /core the same way as the sample code. It might have something to do with Autofac scopes so will look into this further . I would be interested to know if anyone else has this problem.

**Comment by leastprivilege** [comment]
Wsfed is on /wsfed by default. We will also investigate.

**Comment by brockallen** [comment]
Are you referencing IdentityServer and the WS-Fed plugin as source code, or via NuGet assemblies? It'ld be best if you use IdentityServer as NuGet assemblies.

**Comment by leastprivilege** [comment]
We can't repro the issue. Could you please answer Brock's question and show use you startup as well.

**Comment by brockallen** [comment]
I just re-tested this in IIS (not just the IIS Express host) and I can't repro the issue.

**Comment by rayph** [comment]
I'm currently reference the RTM source code in the solution rather than the nuget packages, not sure how this on it's own would affect route registrations though. 

Startup extract: 
            app.UseAutofacMiddleware(AutofacConfig.Start());
            app.UseAutofacMvc();
            app.Map(
                "/core",
                coreApp =>
                    { 
                              .... factory setup ....
                    }; 
           var settings = { ... };
           app.ConfigureWsFederation(settings); 


In AutofaqConfig.Start: 
          var builder = new ContainerBuilder();
          ... register MVC bits (no web api or owin stuff here)...
          DependencyResolver.SetResolver(new AutofacDependencyResolver(container));

**Comment by leastprivilege** [comment]
you are doing:

app.ConfigureWsFederation(settings);

but must be 

coreApp.ConfigureWsFederation(settings);

**Comment by rayph** [comment]
that line actually wraps the UseWsFederationAuthentication, since we the server acting as a RP to itself for the admin pages.

**Comment by leastprivilege** [comment]
maybe just simplify all that and make sure you are really using the right appbuilder which must be the same one where you called UseIdentityServer on.

Also use the nuget instead of the source code and see if that makes a difference.

**Comment by rayph** [comment]
Interestingly, using the package as would normally be done doesn't cause this problem at all. 
I guess I expected it to behave the same way having the actual RTM source code there...
Thanks for helping, this was(is) a bit confusing.

**Comment by brockallen** [comment]
Yep, I'd suggest to stick with the NuGets.
