### ISSUE TITLE
Custom Login: Use Thinktecture in background

### ISSUE THREAD

**Issue by sandeepgaikwad** [IdentityServer/Thinktecture.IdentityServer3#831]
I have been working on Thinktecture Identity server v3 for some days now.
So far I could deploy Thinktecure Identity server v3, configure custom database to be used by the Identity server, configure MembershipReboot for identity management.
I can also authenticate client apps and redirect these apps to Thinktecture Identity server login page.
I have a question: Instead of directing to Identity server login page, I want to use my own (custom) login page and use Thinktecture Identity server in background, is this possible? if yes, kindly direct me to appropriate examples, i.e. when user hits my custom login page "submit" button, user credentials should be authenticated and claims should be loaded.

**Comment by leastprivilege** [comment]
You can use the resource owner credentials flow for that (check the docs/samples). But you won't get SSO with other applications. For SSO the redirect is required.

**Comment by sandeepgaikwad** [comment]
Thanks for your quick feedback.
Yes, I could do that with resource owner flow, but I want SSO.
In that case, where we need redirect, how can we put a "Forget Password" link on the login page?

**Comment by sandeepgaikwad** [comment]
Never mind, I could achieve that using IdentityServerOptions->AuthenticationOptions and add link for "Forgot Password" using LoginPageLinks.
One question regarding this: What is the significance of the url parameter "signin" (with an alphanumeric value) which gets automatically tagged to the href param?

**Comment by brockallen** [comment]
The signin is described in the docs.
