### ISSUE TITLE
Getting firstname and lastname as claims

### ISSUE THREAD

**Issue by theythinkimmexican** [IdentityServer/Thinktecture.IdentityServer3#836]
Hi,

I have Idsv3 set up wth MembershipReboot and IdentityManager configured to adminster users. When creating a new user there are fields for firstname and lastname on the properties tab. So far I have been unable to figure out how to get these sent as claims. I have added roles and other claims which are being send but from the properties tab the only data that appears to be coming in as a claim is the email address.

Is there a way to get the firstname and last name from here or do they need to be added as seperate claims? (like in the 'Getting Started' tutorial)

Thanks

**Comment by brockallen** [comment]
The claims that are provided in tokens from IdentityServer are controlled by the scopes. Check the docs on scopes and claims: https://identityserver.github.io/Documentation/docs/configuration/scopesAndClaims.html

**Comment by theythinkimmexican** [comment]
Maybe my description wasn't very good. I'm aware of using scopes to get claims and I've set up a 'name' scope that returns the given_name and family_ name claims. 

What I mean is whether there's a way to hook up the First Name and Last Name fields on the Properties tab of the UI to be provided as claims for given_name and family_name or whether these need to be added explicitly as claims (in the claims tab).

I think the answer is that they need to be added explicitly, but this seems to make the First Name and Last Name fields on the UI a bit pointless if they are not being used for any claims.

**Comment by johnkors** [comment]
The profile scope includes all the name claims. Why create your own?

**Comment by brockallen** [comment]
So you're asking why you don't get a `name` claim? It's because the user service doesn't automatically create a `name` claim from the first and last names.

**Comment by Pugglewuggle** [comment]
It would appear that the MembershipReboot code doesn't get or return the given_name and family_name claims or anything other than defined manually in the GetClaimsFromAccount() function. I had to add these in manually using reflection to get the values for the FirstName and LastName properties from the MembershipReboot.Config.CustomUser object passed in and then add the claims for each of these manually. Any further pointers would be very helpful. Is this how it should work?
