### ISSUE TITLE
Password change is effective only after process recycle

### ISSUE THREAD

**Issue by rklachko** [IdentityServer/Thinktecture.IdentityServer3#837]
After changing a user account password (using the IDM) attempting to to log-in with the new password fails, until I recycle the process. 

I'm hosting in IIS using MR + EF, I did not use "ConfigureUserServiceCache".

Is there some kind of a User Accounts cache by default? Or can you suggest another reason for this behavior?

**Comment by rklachko** [comment]
After upgrading all packages from RC to RTM (And making required code adjustments that follow) this issue did not reproduce again. Either it was a bug in the RC or I previously did something wrong and fixed it somehow while upgrading to the RTM.
Feel free to close the issue after you review it. Thanks!

**Comment by RaulMo7** [comment]
I have the same problem still occurs, I updated all packages but still the same bug, you recommend?

**Comment by brockallen** [comment]
Are you injecting the user service as a singleton? Perhaps it's getting cached data from the DB.

**Comment by RaulMo7** [comment]
I have this configuration using StructureMap       

   For<DefaultMembershipRebootDatabase>().Use(() => new DefaultMembershipRebootDatabase());
            For<IUserAccountRepository>().Use<DefaultUserAccountRepository>();

**Comment by brockallen** [comment]
I have no idea what those APIs do. It looks like you're customizing IdentityServer via the source code, which we can't support. We can only support customization to IdentityServer via the documented extensibility points when you're referencing the deployed NuGet.

**Comment by RaulMo7** [comment]
I'm using identity server from nuget, i'm not customizing nothing

**Comment by brockallen** [comment]
Like I said, I don't know what those APIs are -- I've never seen them before. Anyway, my guess was that you're caching something in your user service.

**Comment by RaulMo7** [comment]
http://docs.structuremap.net/

**Comment by brockallen** [comment]
We don't use structure map, so that's your code (not IdentityServer's code).
