### ISSUE TITLE
Web API Auth'd but GetUserId() and GetUserName() extensions return null...

### ISSUE THREAD

**Issue by coreyperkins** [IdentityServer/Thinktecture.IdentityServer3#839]
I've tried multiple combinations of clients and scopes but I can't seem to hit on this one. I'm assuming it's a bug, but it's definitely possible it's a "me" issue. :)

I auth via open id (cookies) in mvc and via a bearer token in web api. Auth seems to be working fine, however, if I break in my API controller and call this.User.Identity.GetUserId() or this.User.Identity.GetUserName() I receive a null back.

            app.UseIdentityServerBearerTokenAuthentication(new Thinktecture.IdentityServer.AccessTokenValidation.IdentityServerBearerTokenAuthenticationOptions {
                Authority = string.Format("{0}/identity", ConfigReader.GetConfigValue("HostUrl")),
                AuthenticationType = "Bearer",
                AuthenticationMode = AuthenticationMode.Active,
                RequiredScopes = new[] { "read" }
            });

                new Scope
                {
                    Name = "read",
                    DisplayName = "Read data",
                    Type = ScopeType.Resource,
                    Emphasize = false,
                    IncludeAllClaimsForUser = true,
                    Claims = new List<ScopeClaim> {
                        new ScopeClaim(Constants.ClaimTypes.Name),
                        new ScopeClaim(Constants.ClaimTypes.Id)
                    }
                },

I am accessing my api controller via a js ajax call where I attach the bearer. It's worth mentioning again that I auth fine, I simply can't use the extension method to locate my user. I have to fall back to turning the access token into a JwtSecurityToken, strip out the sub, then locate the user via the UserManager that way.

**Comment by johnkors** [comment]
You have marked your Controller/action with the [Authorize] attribute, yes? Is User a ClaimsPrincipal type?

**Comment by johnkors** [comment]
also, are you using the built in ms claim type mapping, or have you removed it like so? https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/blob/master/source/Clients/SampleAspNetWebApi/Startup.cs#L15

**Comment by coreyperkins** [comment]
Yes, my User is a ClaimsPrincipal. Here's my actions signature with attributes.

[HostAuthentication(OAuthDefaults.AuthenticationType)]
[Authorize]
[Route("~/api/user")]
public HttpResponseMessage Get() { }

Sorry, I forgot to include in my post that I have this line above the app.UseIdentityServerBearerTokenAuthentication:

JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

I did come across another difference just now that could be the problem.

My app has a Global.asax.cs. That is where I configure the web api, like so: GlobalConfiguration.Configure(WebApiConfig.Register);

Because of that, I do not call 

app.UseWebApi(WebApiConfig.Register()); 

Could this be why?

Thanks!

**Comment by johnkors** [comment]
Then I guess create an extensionmethod to ClaimsPrincipal that fetches the "sub" and "name" from the Claims property of ClaimsPrincipal instead of using User.Identity.GetWhatever.

var principal = ClaimsPrincipal.Current;
var idClaim = principal.Claims.FirstOrDefault(c => c.Type == "sub");

**Comment by coreyperkins** [comment]
My co-worker found a pretty decent answer digging through the code that does exactly what you are suggesting.

In the Thinktecture.IdentityServer.Core.Extensions namespace there are tons of useful extensions. The one he found was GetSubjectId (public static string GetSubjectId(this IIdentity identity)).

End result: 

var user = UserManager.FindById(this.User.GetSubjectId());

He also pointed out that I was barking up the wrong tree by wanting to use the name and nameidentifier claims because they aren't in the Open Id spec.

Thanks!

Corey

**Comment by johnkors** [comment]
"name" is in the standard. http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

Glad it worked out :)

**Comment by coreyperkins** [comment]
Ah! Thanks for the correction. We were focused on -> http://openid.net/specs/openid-connect-basic-1_0.html#IDToken

**Comment by brockallen** [comment]
All set then (can we close)?

**Comment by coreyperkins** [comment]
Yes sir, thanks very much!
