### ISSUE TITLE
IdentityServer 3 not returning custom claims

### ISSUE THREAD

**Issue by mmisztal1980** [IdentityServer/Thinktecture.IdentityServer3#840]
Hi there,

First and foremost - congrats on releasing IdentityServer v3. I really love what you've done, I've already managed to create my own IdentityServer, using MembershipReboot as the storage backend, with some additional customizations like custom views etc. - again - love what you've done.

The server appears to be working fine - I'm having three issues with custom claims though :

- In one of my clients, I've added a custom claim (type = 'clientType')- I understand that this claim should be returned from the server whenever a user authenticates using this client? I do not see it being returned (the client is using a Hybrid Flow)

- In IdentityManager I've added a custom claim to one of my users  - it's not being returned at all

- In my server's InMemoryScopeStore, I've defined a Scope which has custom ScopeClaims - I do not see them being returned, nor do I know how to fill their values

I'd apreciate any hints or explanations :)

Best regards,and again - congrats!

**Comment by brockallen** [comment]
Ensure you're asking for just id_token and have configured the scopes (and scope claims) and that you're client is requesting those scopes.

**Comment by coreyperkins** [comment]
I don't have a straight answer for you as I am still dabbling myself, however, I think you could learn a lot by implementing a custom claims provider in your identity factory and overriding some of it's methods. Last night I started digging in to understand a similar problem and it's quite helpful. I just have a ways to go before I know enough to answer your question. :)

**Comment by leastprivilege** [comment]
Client claims only go into access tokens (not id tokens). And are sent by default only using client credentials flow (unless you set the AlwaysSendClientClaims flag).
