### ISSUE TITLE
limiting or protecting CSP Report Endpoint?

### ISSUE THREAD

**Issue by devblaz** [IdentityServer/Thinktecture.IdentityServer3#842]
Hi,

I have concerns about the CSP Report Endpoint. Although i see the importance of CSP and understand the working, I am afraid that a hacker might attack the webserver by sending extreme large and very many CSP Reports to the CSP Report Endpoint.

What are your thoughts about this?

**Comment by leastprivilege** [comment]
You can turn it off on the endpoint options

**Comment by devblaz** [comment]
Ofcourse, i know. Thanks anyway.

But for anybody with the option turned on, wouldn't he be somewhat
vulnerable?
I just tested a little and just alone the application logfile can get
really huge if i post a few hundred big CSP Reports to the endpoint.

Maybe is truncating the report data already enough.


On 29 January 2015 at 12:00, Dominick Baier <notifications@github.com>
wrote:

> You can turn it off on the endpoint options
>
> Sent from my iPhone
>
> > On 29.01.2015, at 09:42, devblaz <notifications@github.com> wrote:
> >
> > Hi,
> >
> > I have concerns about the CSP Report Endpoint. Although i see the
> importance of CSP and understand the working, I am afraid that a hacker
> might attack the webserver by sending extreme large and very many CSP
> Reports to the CSP Report Endpoint.
> >
> > What are you're thoughts about this?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/842#issuecomment-72006601>
> .
>



-- 
 ☻/
/ ▌  Groetjes, Blazzie
 / \

**Comment by leastprivilege** [comment]
@brockallen turn off by default? truncate data?

**Comment by brockallen** [comment]
We could log the CSP errors someplace different, thus preventing the normal events/logs from being saturated.

**Comment by leastprivilege** [comment]
somewhere different sounds like more complexity.

**Comment by brockallen** [comment]
So then the other idea is to do something more general to throttle spam-style attacks.
