### ISSUE TITLE
Username returns \x40 intead of @

### ISSUE THREAD

**Issue by Tronhus** [IdentityServer/Thinktecture.IdentityServer3#843]
Hi 
I have a custumviewservice that handel the login logout views. 
If i enter username ttt@praxis.dk and a wrong password, i get username ttt\x40praxis.dk. 

I have checked the viewmodel object and the username value is ttt\x40praxis.dk¢
![screen shot 2015-01-29 at 14 51 38](https://cloud.githubusercontent.com/assets/1876819/5958586/5d2a727a-a7c6-11e4-99f7-bb85f34a75c6.png)

**Comment by leastprivilege** [comment]
are you on v1?

**Comment by rklachko** [comment]
I had this Issue in the beta 4-1, should be fine after upgrading.
