### ISSUE TITLE
Can we host our Identity server 3 in http instead of https 

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#844]
I have tested Identity sever local in IIS  it works fine, when i am have uploaded  to the server in HTTP host  i am getting error like cryptography.dll access  denied error.
can i know the reason and is that possible to host Identity Server in HTTP Host instead of HTTPS.

**Comment by leastprivilege** [comment]
Well - posting a vague error message is not very helpful in diagnosing your problem.

IdSrv def works on IIS/SSL. Maybe clear your cookie cache.

**Comment by brockallen** [comment]
Sounds like this, maybe: https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/849#issuecomment-72239371
