### ISSUE TITLE
Access and Refresh Tokens stay valid

### ISSUE THREAD

**Issue by dontbesorry80** [IdentityServer/Thinktecture.IdentityServer3#848]
When the access token expires I use the refresh token to get a new access token. However after renewing the token, the old token begins to work again?

Then once it happens again, both the old access tokens work...

I assume this is not intended behaviour...??

**Comment by leastprivilege** [comment]
Could you describe the behavior you are seeing as detailed as possible (and which exactly which token types etc)

**Comment by dontbesorry80** [comment]
Yes of course:
These are the options for the client:
```
AccessTokenType = AccessTokenType.Reference,
AccessTokenLifetime = 300, //in seconds

SlidingRefreshTokenLifetime = 1296000, //in seconds = 15 days
RefreshTokenUsage = TokenUsage.OneTimeOnly,
RefreshTokenExpiration = TokenExpiration.Sliding
```
I'm using POSTMAN do do the testing:
Connecting to https://idsrvr/core/connect/token
this gave me
```
{
	"access_token": "02791d1ff4e1e6afd93376f417d605fe",
	"expires_in": 300,
	"token_type": "Bearer",
	"refresh_token": "246b827e98ce203e878a76bbeeccbe56"
}
```
After 5 mins I got;
```
{
	"Message": "Authorization has been denied for this request."
}
```
then using the grant_type of "refresh_token"
I refreshed the token and received
```
{
"access_token": "1378adacb7cc9ad24b5dbdf294722017",
"expires_in": 300,
"token_type": "Bearer",
"refresh_token": "7503c387aef9301c6cb86f09d9d85b7b"
}
```
However 
if I passed the original access_token as a Bearer Header eg.
Bearer 02791d1ff4e1e6afd93376f417d605fe
it would carry on working again for 5 mins. When it expires if I use the refresh token service again I have to use the new refresh token otherwise it says "invalid grant" however I can use any of the previous tokens and it will allow me to refresh. Then once again I can use any of the previous access tokens in the header of my requests.

Do you need any more information?

**Comment by leastprivilege** [comment]
Are you saying that refresh tokens can be used more than once to request a new access token?

That's hard to believe because of 
https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source%2FCore%2FServices%2FDefault%2FDefaultRefreshTokenService.cs#L142

Or are you saying that when requesting a new access token using a refresh token - the old access token can still be used? If yes - that would be expected since we don't invalidate access tokens on refresh token refresh.

**Comment by dontbesorry80** [comment]
Yes. I was saying the second case. I can start using the original access
token again when I have refreshed. If that is expected behaviour then we
are good to go.

However, if we never need to store a new access token, is there any point
of issuing a new one?

Or am I missing something?

**Comment by leastprivilege** [comment]
However, if we never need to store a new access token, is there any point
of issuing a new one?

I don't understand this sentence - access tokens have a finite lifetime. When an access token expires, you can use the refresh token to request a new one.

**Comment by dontbesorry80** [comment]
That's what I'm saying. When the access token expires and I request a new
one, the original starts to work again.. Both for API calls and for future
refresh calls.

Does that make sense?

Rob

**Comment by leastprivilege** [comment]
For refresh tokens you don't need an access token - just the refresh token. 

And no - an access token that has expired and stopped working - coming back to life would not make sense to me.

**Comment by leastprivilege** [comment]
i just added additional code that removes expired reference tokens completely from the store during validation. 

See if you can repro your behavior - the new code is on the dev branch/myget only so far.

**Comment by dontbesorry80** [comment]
OK. So if you don't need the access token  for a refresh, that solves that.
But the access token definitely comes back to life.

I will double check. Do you want access to my endpoint so you can confirm?

Rob

**Comment by leastprivilege** [comment]
no - but try to repro it.

**Comment by leastprivilege** [comment]
any update?

**Comment by dontbesorry80** [comment]
OK. I've just reproduced it. 

At 08:48am I Authorize with Identity Server
```
{
"access_token": "bcc315995c771ae0171949d1c5e72691",
"expires_in": 300,
"token_type": "Bearer",
"refresh_token": "cdadff0fba992d009cab249d6ce220d0"
}
```
Wait 5 mins then I get using
Authorization = Bearer bcc315995c771ae0171949d1c5e72691
```
{
"Message": "Authorization has been denied for this request."
}
```
Refresh the token and get
```
{
"access_token": "fcfae892ccfcdc1f6c0214dfe4fe677d",
"expires_in": 300,
"token_type": "Bearer",
"refresh_token": "7fffc0429968c2a9454d2a81390daea5"
}
```
Then call a protected API function and it succeeds using:
Bearer bcc315995c771ae0171949d1c5e72691
If I want another 5 minutes I get:
```
{
"Message": "Authorization has been denied for this request."
}
```
I can then refresh again receiving:
```
{
"access_token": "c21c91a20500327c6bd4c3c06bb7989b",
"expires_in": 300,
"token_type": "Bearer",
"refresh_token": "733cd51ea570b5933a4c228ccc838f2e"
}
```
Then the original header:Bearer bcc315995c771ae0171949d1c5e72691 starts to work again.

What else do you need me to do to repro?

**Comment by leastprivilege** [comment]
on which version are you? which token handle repo? single server or load balanced?

**Comment by dontbesorry80** [comment]
It's a single server and v4.0.30319

**Comment by leastprivilege** [comment]
which idsrv version? which token handle store?

**Comment by dontbesorry80** [comment]
I thought that was the Identity Server version? I read that of the Runtime Version on the referenced dll. The nuGet package just says 1.0.0-rc (pre-release)
I don't think I've implemented a token handle store? Is this the problem?

**Comment by leastprivilege** [comment]
Please update from the pre-release version to the latest nuget (v1.0.2) - then test again.

The default token handle store is in-memory only - that's fine for our tests - but not for production.

**Comment by leastprivilege** [comment]
v4 is probably your version of .net

**Comment by dontbesorry80** [comment]
you're probably right.. I'll upgrade and let you know.

**Comment by dontbesorry80** [comment]
So. I haven't yet installed the entity framework token store but just checked with the upgrade and the problem is solved! Great stuff.

**Comment by krishna1682** [comment]
Hi,
I am trying to do the slient renew and as per the requirement it has to stop renew after some time interval and its better to generate the new token on every renew.
I am using the below settings, but it is not generating the new token everytime and renewing the token with N no.of times.

Identity Server Settings:
AccessTokenLifetime = 240,
RefreshTokenExpiration = TokenExpiration.Absolute,
AbsoluteRefreshTokenLifetime = 600,
RefreshTokenUsage = TokenUsage.OneTimeOnly,

Client settings:
accessTokenExpiringNotificationTime: 120,
