### ISSUE TITLE
After  Deploying Identity Server 3 in website  i am Getting Access denied error in Cryptographic dll related issue

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#849]
This given below error occurs when i call CERT.load() function. (this issue occur only in the website not in on the local iis)

Access denied.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Security.Cryptography.CryptographicException: Access denied.

**Comment by brockallen** [comment]
Your web server identity does not have read access to the certificate private key.

**Comment by RajMondaz** [comment]
Where i need to make change for read access.

Because we can't change the permission in the go daddy server but in the local iis this is working fine..

**Comment by brockallen** [comment]
You do this via the mmc snapin -- check the msdn docs.

**Comment by leastprivilege** [comment]
dup of #854
