### ISSUE TITLE
Sample for Session Management Spec?

### ISSUE THREAD

**Issue by AdamDotNet** [IdentityServer/Thinktecture.IdentityServer3#851]
It looks like Session Management Spec has been implemented since RC. I hate to admit it, but I have no clue how to utilize it.

I've poured over the fairly robust documentation and the Samples repository but I just can't seem to find anything about using the /connect/checksession endpoint with corresponding iframes. Will the documentation be updated to include it? Will a sample be forth coming?

I'm using Owin OpenIdConnectAuthentication in Asp.Net MVC Implicit flow clients, if that helps. Although you don't own that project, do you know if there are helpers in that package to accomplish this? Do any of the Thinktecture Nugets have helpers?

Thanks for making this great product, and thank you for your time.

**Comment by brockallen** [comment]
We're still working on a sample that shows how to use it fully.

**Comment by AdamDotNet** [comment]
Thank you, I look forward to it!

**Comment by leastprivilege** [comment]
Wring repo. Use the sample repo.
