### ISSUE TITLE
After deploying Identity Server 3, i am getting access denied error how fix it..

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#854]
This Error is coming From start.cs file in this  SigningCertificate = Cert.Load() , when it tries to load this function i am getting error.

![work](https://cloud.githubusercontent.com/assets/10266752/5988724/7f11be70-a992-11e4-8e7d-2c7e636da3dc.png)

**Comment by brockallen** [comment]
Well, it's telling you don't have access. Maybe you can provide more context about where your cert is being loaded from.

**Comment by RajMondaz** [comment]
This below load function when i am  trying to access in startup.cs class it through this error , but  in the local iis it works fine but after deploy to the server (to the website) i am getting Access denied error..  how i can fix.

![image](https://cloud.githubusercontent.com/assets/10266752/5989565/77b53b3c-a9b2-11e4-80c4-ff395aeea8da.png)

![image](https://cloud.githubusercontent.com/assets/10266752/5989575/b74bbf46-a9b2-11e4-99fa-dc4c6aa97760.png)

**Comment by leastprivilege** [comment]
Sounds like it is some sort of limitation of your hosting environment. Our approach works in Azure Web Sites which is already pretty locked down. 

Best to contact the hosting provider.

**Comment by RajMondaz** [comment]
Hi  brockallen,

is there any way to  By Pass this methods.

if i am not calling this methods.

![image](https://cloud.githubusercontent.com/assets/10266752/5997245/ab6c31a6-aade-11e4-9343-b0c389236338.png)

 I am able get the consent screen 

![image](https://cloud.githubusercontent.com/assets/10266752/5997226/66da9bae-aade-11e4-9504-ff56857fad2e.png)
After that if click on yes then i am getting this below error 
![image](https://cloud.githubusercontent.com/assets/10266752/5997263/fa66f412-aade-11e4-8263-96cdadf29417.png)
Any way is there to By-pass this Issue..

**Comment by leastprivilege** [comment]
If you are not setting a cert - then obviously idsrv will hit an error when trying to sign the token.

You need a certificate.

**Comment by RajMondaz** [comment]
ok thank you..
