### ISSUE TITLE
Deriving from LogProvider

### ISSUE THREAD

**Issue by JamesReate** [IdentityServer/Thinktecture.IdentityServer3#855]
Hello,

I am trying to build an elmah LogProvider, but when I go to create a new class that inherits from `Thinktecture.IdentityServer.Core.Logging.LogProvider`, there isn't anything I can override or implement... I read the wiki at http://identityserver.github.io/Documentation/docs/configuration/logging.html but it just said to "derive from LogProvider".. 
Any guidance would be appreciated, I'll commit the code to the log providers

**Comment by JamesReate** [comment]
Looked at the source code and found some sample implementations.

Now, I noticed for example the Log4Net was built all using reflection fancy. If I am to contribute a logger for Elmah that is not built using reflection, ie. just straight reference to the library, would you accept it? Or do you want them all to follow that standard....

**Comment by leastprivilege** [comment]
The right approach would be to contribute to LibLog directly - https://github.com/damianh/LibLog

But yeah - it is not about being fancy - it is about being dependency free.

If you want to create an IdSrv contrib project let us know and we link to you from the docs.

**Comment by JamesReate** [comment]
Just checked out LibLog, looks like a cool approach, and I understand the need for dependency free - specially in a lib for the public. 
For tonight though, just gonna do a quicky mickey implementation to figure something out.
