### ISSUE TITLE
Welcome screen cannot be overridden with assets folder

### ISSUE THREAD

**Issue by svrooij** [IdentityServer/Thinktecture.IdentityServer3#857]
I like the way to override the DefaultViews as described in [your documentation](http://identityserver.github.io/Documentation/docs/advanced/customizingViews.html).
But it seems like I cannot override the welcome screen that way?
Is this correct? Or how should I do it?

And I wasn't completely happy with the consent screen, the buttons seemed weird on a small screen. Can I send a pull request with a new consent screen? 
![iPhone simulator screenshot of consent screen](https://cloud.githubusercontent.com/assets/1292510/5992005/08a92c9c-aa13-11e4-9523-2136c1cbe1b2.png)

Keep on the good work, I really like the new Identity Server, it is probably going to be a big part of the new API we'll be releasing to your students very soon.

**Comment by leastprivilege** [comment]
The welcome screen is fixed for the time being.

**Comment by svrooij** [comment]
Thanks for the quick response. Should I send a pull request for the consent screen?

**Comment by leastprivilege** [comment]
You can certainly open a PR to discuss the changes. Read the contribution guidelines first please.

**Comment by brockallen** [comment]
The welcome page is not really meant for end-users. It was added for developers while they're developing for IdentityServer.

**Comment by johnkors** [comment]
@svrooij Want to help translate IdSrv with a small PR? http://johnkors.github.com/IdentityServer3.Contrib.Localization

**Comment by fekberg** [comment]
@brockallen If it's intended for developers only, how do you recommend disabling the welcome screen when it's going to production?

**Comment by loctanvo** [comment]
@fekberg Setting the `EnableWelcomePage` to `false`? [Documentation](http://identityserver.github.io/Documentation/docs/configuration/identityServerOptions.html)

**Comment by fekberg** [comment]
@loctanvo Thanks, exactly what I was looking for!
