### ISSUE TITLE
Migration path from Katana OAuth server middleware to IdSv3

### ISSUE THREAD

**Issue by ycrumeyrolle** [IdentityServer/Thinktecture.IdentityServer3#859]
Is there any documentation for migrating from the Katana OAuth2 server middleware to the IdSv3 ?

**Comment by leastprivilege** [comment]
No. But they should be wire compatible. Give it a try.

We can help you out when there are questions - maybe you can write up the steps afterwards so we/you can publish it.

**Comment by leastprivilege** [comment]
any progress?

**Comment by ycrumeyrolle** [comment]
Nothing for the moment.
Unfortunatly, decision to migrate/upgrate is not on my own.

**Comment by leastprivilege** [comment]
ok no problem - will close this one.
