### ISSUE TITLE
MembershipReboot Integration Authentication Issues

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/Thinktecture.IdentityServer3#861]
Brock,

I have a fairly extensive solution based fundamentally on IdentityServer v3 and until today using ASP.NET Identity 2.0 for the user service/store. I have a fundamental need for multi-tenancy support and while there is a NuGet package to add it to Identity 2 and I could always roll my own I thought I would try MembershipReboot. The process was fairly straight forward to achieve a similar configuration that I had up and running in Identity and my seed method worked great when I spun it up having created a userAccountService and populating the database.

I thought I was good to go so I hit a control protected by the authorize attribute and using the username/pass I just seeded the database with I received a bad username and password. Since I am not sure where I should be looking first (Idv3 or MR), could you let me know where I should start looking for where the issue is occurring? I would prefer not to spend half a day looking into MR when it is more likely an issue with the configuration in Idv3 and viceversa. 

Thanks for you help and solid offerings.

Jim

**Comment by brockallen** [comment]
You can enable tracing/logging in MR -- it should give you lots of info into what happened.
