### ISSUE TITLE
EndSessionRequestValidator Log Non-authenticated as Warnings

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/Thinktecture.IdentityServer3#862]
Hi,

When a user logs out from an active RP session, but their idsvr cookie is expired I am getting the following event logged: "User is anonymous. Aborting logout."

I am using log4net, and have a logger that emails any ERROR level events.
Should this be an error or a Warning?

```c#
if (!subject.Identity.IsAuthenticated)
            {
                Logger.Error("User is anonymous. Aborting logout.");
                return Invalid();
            }
```

I also noticed that the way this message is logged is different from others in ValidateAsync.
Is it possible to have the post logout redirect URIs evaluated before returning Invalid(); ??
It would be handy to have the Redirect Link displayed regardless of the user being current. I'm not sure if this presents a security issue though. The post logout redirect uri value is still available in this method regardless of if the user is currently Authenticated.

**Comment by leastprivilege** [comment]
I changed the error to a warning. 

The issue is, if the user is logged out already, we cannot make sure that the login hint (and thus the post logout uri) "belongs" to that user. So it is not safe to do the redirect.

@brockallen thoughts?

**Comment by brockallen** [comment]
No redriect, IMO. We can still hit the logout page which will do all the cookie cleanup, but like you said -- we can't validate that the user matches the id_token.

**Comment by parkinsona** [comment]
Thanks for updating it to a warning :) 

Does the post logout uri belong to the user or to the RP?

If the user isn't authenticated, and you show the logout URI, what vulnerability is there? If they're redirected back to an RP, then that RP won't consider them logged in so I wouldn't think it would be a problem.

**Comment by leastprivilege** [comment]
Because you could send an arbitrary user (not even a user of identity server) a link to logout which redirect afterwards to some page the user might not even have a relationship with (aka phishing/spam).

**Comment by parkinsona** [comment]
I can see the vulnerability there.
However, identity server needs to be configured with the post logout uris. 
Not sure how a phishing/spam redirect link could be used if its not in the list of logout uris on idsvr.

Unless this scenario is what you mean...
- person A has access to RP1. 
- RP2 also uses idsvr but person A is not one of their users.
- RP2 wants to get everyone to visit their site, so they send person A a logout link with RP2's redirect.

**Comment by parkinsona** [comment]
Is it still a problem, if you have a valid id token?

This is what currently happens:
1. User logs in and id_token is added to RP's claims
2. Time out expires on both RP and idsvr.
3. User clicks the logout link
4. User is not authenticated with idsvr anymore, so no id_token validation happens, therefore no redirect uris.

Is it possible, to validate the id_token prior checking if the user is authenticated? It may be possible, that the user has expired in idsvr, but is still current in the RP. In this case, the id token would be available and can be sent through.

I hope that makes sense.

**Comment by leastprivilege** [comment]
yes. e.g.

**Comment by parkinsona** [comment]
Hey Dom, was there more to that message? Or were you just indicating that my example scenario was what you meant?

**Comment by leastprivilege** [comment]
we can think about that (distinguishing between expired vs non-expired id token).

**Comment by parkinsona** [comment]
Any more thoughts on this?
Also, which release will the warning change be added to?

**Comment by leastprivilege** [comment]
I released 1.1.1 yesterday.

Didn't have the time to think more about it.

**Comment by johnkors** [comment]
Similar request about Error => Warn for invalid refresh tokens. https://github.com/IdentityServer/Thinktecture.IdentityServer3/pull/892

**Comment by leastprivilege** [comment]
yea  ;) We'll get to that as well - right now I am doing paid work :)

**Comment by johnkors** [comment]
:D fair enough!

**Comment by parkinsona** [comment]
I did see the release for 1.1.1, but I wasn't sure if it was included. Still haven't worked out github's way of presenting things completely.

Thanks for the update.
Good to see someone is paying you :)

**Comment by johnkors** [comment]
@parkinsona You can check what is new in 1.1.1 vs 1.1.0 using the tags:

https://github.com/IdentityServer/Thinktecture.IdentityServer3/compare/1.1.0...1.1.1

**Comment by leastprivilege** [comment]
@parkinsona I can't remember all the details - could you write that up in a feature request. thanks.

**Comment by parkinsona** [comment]
@leastprivilege , I have raised this as a new issue.
https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/964

Wasn't sure how to mark it as a feature request.
I guess we can close this one now.
