### ISSUE TITLE
MembershipReboot and Roles

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/Thinktecture.IdentityServer3#865]
Brock,

Disclaimer: The current configuration was working as expected under Identity 2.x and the behavior I am seeing is a result of switching to MembershipReboot and I am confident I am missing a claim or scope somewhere.

I have fully migrated the project I am working on from Identity 2.x to MembershipReboot and I am really enjoying it. Now that the tenancy issue is resolved, I noticed some odd behavior and I am sure I am doing something wrong. 

I am seeding my database with a user and then adding claims to that user: 

`userAccountService.AddClaim(user.ID, "role", "authserver.administrator");`

That populates the database as expected.

As before, I am using UseOpenIdConnectAuthentication in my MVC front end (Idv3 is hosted in WebAPI).

```
Authority = CloudConfigurationManager.GetSetting("OpenConnectAuthority"),
                ClientId = "authserver",
                Scope = "openid profile roles authserver.management",
                RedirectUri = CloudConfigurationManager.GetSetting("OpenConnectRedirectUri"),
                ResponseType = "id_token token"
```

My scope is seeded with:

```
new Scope
            {
                Enabled = true,
                Name = "roles",
                Type = ScopeType.Identity,
                Claims = new List<ScopeClaim>
                {
                    new ScopeClaim("role")
                }
            },
new Scope
            {
                Enabled = true,
                Name = "authserver.management",
                Description = "Ability to access the auth server api.",
                Type = ScopeType.Resource,
                Claims = new List<ScopeClaim>
                {
                    new ScopeClaim(Thinktecture.IdentityServer.Core.Constants.ClaimTypes.Name),
                    new ScopeClaim(Thinktecture.IdentityServer.Core.Constants.ClaimTypes.Role)
                }
            }
```

I get redirected as expected and have dropped into the debugger in the following places with the following results:

**Idv3 Custom Identity Token Claims Provider: Task<IEnumerable<Claim>> GetIdentityTokenClaimsAsync**

*Results: No role claims*

**Idv3 Custom Access Token Claims Provider: Task<IEnumerable<Claim>> GetAccessTokenClaimsAsync**

*Results: Role claims present: {role: authserver.administrator}*

**Idv3 Custom MembershipRebootUserService: IEnumerable<Claim> GetClaimsFromAccount**

*Results: Role claims present: {role: authserver.administrator}*

After all of that, in my SecurityTokenValidated notification I access the AuthenticationTicket and all roles claims are missing. 

Do you have any idea where they could be dropping on the ground? The diagnostics log shows them in the access token but I lose them on the redirect (it seems).

**Comment by brockallen** [comment]
Maybe because in the client it's using ClaimTypes.Role for the role claim type, not "role". IOW, see what we do in our MVC samples using OIDC to create a new claims identity passing the "name claim type" and "role claim type" params.

**Comment by jlegan** [comment]
Brock,

I may have introduced the issue when I migrated the Idv3 implementation from the MVC app to the WebApi in the same solution. I was still using the implementation from the sample but I understand why that would not work (I was a bit too close to it at the time). However it does bring up an interesting question. 

In the SecurityTokenValidated event I can get the roles in question by calling the UserInfo endpoint  by leveraging the UserInfoClient (sp?) that is provided in IdentityModel.Client I believe. This allows me to grab the user roles in the same way they are grabbed in the example where you are calling into an API on behalf of a user. 

In my case I will have an MVC app that will need both an access token (to call an API) as well as access to those roles on the client side to do validation (UI constraints, etc...). What is the preferred method of getting them? Should I be calling the UserInfo end point immediately after the user authenticated or should I decrypt the access token that already has them?

I figured all of this out when I spun up a sample angular app based in part on your sample and realized that both my access token and identity token still looked correct. The issue was solution in the UseOpenIdConnectAuthentication implementation.

**Comment by brockallen** [comment]
Sort of, but the other way around. In the MVC app, you need to tell the ClaimsIdentity to *not* use "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" as the role type and instead use "role". See this for an example:

https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/blob/master/source/MVC%20Authentication/EmbeddedMvc/Startup.cs#L78

**Comment by jlegan** [comment]
Thanks Brock, I will test tomorrow and report back.

**Comment by jlegan** [comment]
Brock,

The example you linked is precisely how I already have it implemented:

```csharp
                        // create new identity and set name and role claim type
                        var nid = new ClaimsIdentity(
                            id.AuthenticationType,
                            Thinktecture.IdentityServer.Core.Constants.ClaimTypes.GivenName,
                            Thinktecture.IdentityServer.Core.Constants.ClaimTypes.Role);
```

Below is the current implementation of my OpenIdConnect implementation. I guess my question boils down to whether or not it is expected behavior to need to call the the UserInfo endpoint after obtaining a token and id_token and whose access token already contains the roles or if there a more preferable way to do so (i.e. decrypt the access token)?

```csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = CloudConfigurationManager.GetSetting("OpenConnectAuthority"),
                ClientId = "authserver",
                Scope = "openid profile roles authserver.management",
                RedirectUri = CloudConfigurationManager.GetSetting("OpenConnectRedirectUri"),
                ResponseType = "id_token token",

                SignInAsAuthenticationType = "Cookies",
                UseTokenLifetime = false,

                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    
                    AuthenticationFailed = async n =>
                    {
                        var x = n.Exception;
                    }
                    ,SecurityTokenValidated = async n =>
                    {
                        var id = n.AuthenticationTicket.Identity;

                        var givenName = id.FindFirst(Thinktecture.IdentityServer.Core.Constants.ClaimTypes.GivenName);
                        var familyName = id.FindFirst(Thinktecture.IdentityServer.Core.Constants.ClaimTypes.FamilyName);
                        var companyName = id.FindFirst(AuthServer.Identity.Constants.ClaimTypes.CompanyName);
						
                        // create new identity and set name and role claim type
                        var nid = new ClaimsIdentity(
                            id.AuthenticationType,
                            Thinktecture.IdentityServer.Core.Constants.ClaimTypes.GivenName,
                            Thinktecture.IdentityServer.Core.Constants.ClaimTypes.Role);

                        // get userinfo data
                        var userInfoClient = new UserInfoClient(
                            new Uri(n.Options.Authority + "/connect/userinfo"),
                            n.ProtocolMessage.AccessToken);

                        var userInfo = await userInfoClient.GetAsync();
                        userInfo.Claims.ToList().ForEach(ui => nid.AddClaim(new Claim(ui.Item1, ui.Item2)));

                        nid.AddClaim(givenName);
                        nid.AddClaim(familyName);
                        nid.AddClaim(companyName);

                        // keep the id_token for logout
                        nid.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
                        nid.AddClaim(new Claim("access_token", n.ProtocolMessage.AccessToken));

                        Log.Debug(string.Format("{0} {1} logged in.", givenName, familyName));
						
                        n.AuthenticationTicket = new AuthenticationTicket(
                            nid,
                            n.AuthenticationTicket.Properties);
                    },
                    RedirectToIdentityProvider = async n =>
                    {
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token").Value;
                            n.ProtocolMessage.IdTokenHint = idTokenHint;
                        }
                        else if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.AuthenticationRequest)
                        {
                            n.ProtocolMessage.AcrValues = string.Format("tenant:{0}", "multi.tenant.test");
                        }
                    }
                }

            });
```

**Comment by brockallen** [comment]
The next thing I'd check is what claims are in `n.AuthenticationTicket.Identity`. I really can't tell if the claims are being sent or if the claim type is just being mismatched.

**Comment by johnkors** [comment]
I thought this line solved these kinds of issues..?

https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/blob/master/source/MVC%20Authentication/EmbeddedMvc/Startup.cs#L33

**Comment by jlegan** [comment]
@johnkors That was my understanding as well and in fact I have that in place, immediately below the UseOpenIdConnectAuthentication.

@brockallen Here is the state of the claims at each step:

**Idv3 Custom Identity Token Claims Provider in WebAPI: <Task> GetIdentityTokenClaimsAsync**
```
{sub: 07df869d-8e48-4543-9341-064dc7d33bb1}
{amr: password}
{auth_time: 1423081403}
{idp: idsrv}
{sub: 07df869d-8e48-4543-9341-064dc7d33bb1}
```
**Idv3 Custom Access Token Claims Provider in WebAP: <Task> GetAccessTokenClaimsAsync**
```
{client_id: authserver}
{scope: openid}
{scope: profile}
{scope: roles}
{scope: authserver.management}
{sub: 07df869d-8e48-4543-9341-064dc7d33bb1}
{amr: password}
{auth_time: 1423081403}
{idp: idsrv}
{role: api.customer.manager}
```
**Idv3 Custom MembershipRebootUserService in WebAPI: IEnumerable GetClaimsFromAccount**
```
{sub: 07df869d-8e48-4543-9341-064dc7d33bb1}
{updated_at: 1423099339}
{tenant: cp.Company}
{preferred_username: FirstName}
{email: FirstName@Company.com}
{email_verified: false}
{role: api.customer.manager}
```
**UseOpenIdConnectAuthentication in MVC App**
```
{nonce: 635586781234970900.MmMyNmMzZWEtOTlmZS00YTdjLTgwZGMtODYzN2E0ZmQ3N2YyNWI2MWZhZGUtZWRjZS00OWFkLTk5NjYtZThlYWNiN2Y4NDVm}
{iat: 1423081453}
{at_hash: y-sZvuml-jvdLWFwGxL6_g}
{sub: 07df869d-8e48-4543-9341-064dc7d33bb1}
{amr: password}
{auth_time: 1423081403}
{idp: idsrv}
{family_name: LastName}
{given_name: FirstName}
{company_name: Company}
{iss: https://127.0.0.1:21465}
{aud: authserver}
{exp: 1423081786}
{nbf: 1423081486}
```

From my Angular app my token content is (different request):

**Identity**
```
{
  "nonce": "14721611962372287",
  "iat": 1423081916,
  "at_hash": "gZDsjd3lGXVWU2TIc_hsRQ",
  "sub": "4564b982-76d6-4a67-a797-6e2eb3130ea5",
  "amr": "password",
  "auth_time": "1423081911",
  "idp": "idsrv",
  "family_name": "LastName",
  "given_name": "FirstName",
  "company_name": "Company",
  "iss": "https://127.0.0.1:21465",
  "aud": "ngClient",
  "exp": 1423082216,
  "nbf": 1423081916
}
```
**Access**
```
{
  "client_id": "ngClient",
  "scope": [
    "openid",
    "profile",
    "email",
    "authserver.management"
  ],
  "sub": "4564b982-76d6-4a67-a797-6e2eb3130ea5",
  "amr": "password",
  "auth_time": "1423081911",
  "idp": "idsrv",
  "role": [
    "authserver.administrator",
    "global.administrator"
  ],
  "app_specific": "app_specific_value",
  "iss": "https://127.0.0.1:21465",
  "aud": "https://127.0.0.1:21465/resources",
  "exp": 1423085516,
  "nbf": 1423081916
}
```

**Comment by johnkors** [comment]
Tried moving it to the very top of your startup.cs? All the samples do that.

**Comment by jlegan** [comment]
@johnkors I have tried both ways but I thought the original samples I based this off of had them at the bottom but either way, would that make sense given what I am seeing? In MembershipReboot I am creating a UserClaim of type "role" and value "authserver.administrator". 

`userAccountService.AddClaim(user.ID, "role", "authserver.administrator");`

Unless there is some magic occurring under the hood and my "role" is being transformed into "http://schemas.microsoft.com/ws/2008/06/identity/claims/role", there should be no mapping required as far as I understand the claims flow.

I think the root of the issue is that there is no roles claims being returned from the UseOpenIdConnectAuthentication request, though they exist in the access token in the ProtocolMessage.AccessToken and can be retrieved by making a call to the userinfo endpoint:

```
var userInfoClient = new UserInfoClient(
                            new Uri(n.Options.Authority + "/connect/userinfo"),
                            n.ProtocolMessage.AccessToken);
```

**Comment by jlegan** [comment]
@brockallen @johnkors Guys I have to apologize. I am not sure how my unit test failed before, likely because of an unrelated change, but adding the flag to force the identity scope clam for inclusion solved the problem. I had tested it previously so I am not entirely sure where the disconnect was. The exercise however was invaluable and I have a much better understanding of the underlying system as a result. Thank you both for your time.
