### ISSUE TITLE
Error AccessTokenValidationEndpoint multiple request 

### ISSUE THREAD

**Issue by RaulMo7** [IdentityServer/Thinktecture.IdentityServer3#867]
Hello guys.

I have a problem running multiple request, the validation token endpoint generates an exception like this:

{"The connection was not closed. The connection's current state is connecting."}

I've been looking at forums and find that the problem is that is not correctly closed a connection, I find in the forums:

http://geekswithblogs.net/TimH/archive/2008/09/09/asp.net-sql-server-error-the-connection-was-not-closed.-the.aspx

I appreciate your help.

Thanks

**Comment by brockallen** [comment]
I think we're going to need more information.

**Comment by RaulMo7** [comment]
I'm storing the tokens in database tokens by reference, users are stored using membership reboot.

I have an application which launches angular multiple requests, for example invokes a 3 services while using the same access token example:

- Service1, Service2, Service3

I'm doing a debug one of the examples of identity server using the same settings we have in our project to analyze in depth what happens, I've put a try-catch in the endpoint AccessTokenValidationController in the GET "/// <returns> Claims if token is valid </ returns> "

I add a breakpoint in the catch to see what happens and I returned the error mentioned above:

{"The connection was not closed. The connection's current state is connecting."}

This only happens when multiple request invoked simultaneously.

U need more information?

**Comment by RaulMo7** [comment]
Now, i have this error:

{"There is already an open DataReader associated with this Command which must be closed first."}

**Comment by RaulMo7** [comment]
![debugidentityserver](https://cloud.githubusercontent.com/assets/7596164/6032069/d53909ce-abd2-11e4-9dfb-b1e5aa6cf426.png)

**Comment by brockallen** [comment]
How are you setting up your EF code?

**Comment by RaulMo7** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BrockAllen.MembershipReboot;
using BrockAllen.MembershipReboot.Ef;
using Thinktecture.IdentityServer.Core;
using Thinktecture.IdentityServer.Core.Extensions;
using Thinktecture.IdentityServer.Core.Models;
using Thinktecture.IdentityServer.Core.Services;
using Thinktecture.IdentityServer.MembershipReboot;

namespace Thinktecture.IdentityServer.Host.Config
{
    public class UserServiceCustom : IUserService
    {
        #region Attributes

        private readonly MembershipRebootUserService<UserAccount> _membershipUserService;
        private readonly UserAccountService<UserAccount> _userAccountService;

        #endregion

        #region Constructor

        public UserServiceCustom(UserAccountService userAccountService)
        {
            _membershipUserService = new MembershipRebootUserService<UserAccount>(userAccountService);
            _userAccountService = userAccountService;
        }

        #endregion

        #region Implementations of IUserService

        public Task<AuthenticateResult> PreAuthenticateAsync(SignInMessage message)
        {
            return _membershipUserService.PreAuthenticateAsync(message);
        }

        public Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message = null)
        {
            UserAccount account;
            if (_userAccountService.AuthenticateWithUsernameOrEmail(username, password, out account))
            {

                var subject = account.ID.ToString("D");

                return Task.FromResult(new AuthenticateResult(subject, username));
            }

            if (account != null)
            {
                if (!account.IsLoginAllowed)
                {
                    return Task.FromResult(new AuthenticateResult("Account is not allowed to login"));
                }

                if (account.IsAccountClosed)
                {
                    return Task.FromResult(new AuthenticateResult("Account is closed"));
                }
            }

            return Task.FromResult<AuthenticateResult>(null);
        }

        public Task<AuthenticateResult> AuthenticateExternalAsync(ExternalIdentity externalUser, SignInMessage message)
        {
            return _membershipUserService.AuthenticateExternalAsync(externalUser, message);
        }

        public Task SignOutAsync(ClaimsPrincipal subject)
        {
            return _membershipUserService.SignOutAsync(subject);
        }

        public Task<IEnumerable<Claim>> GetProfileDataAsync(ClaimsPrincipal subject, IEnumerable<string> requestedClaimTypes = null)
        {
            return _membershipUserService.GetProfileDataAsync(subject, requestedClaimTypes);
        }

        public Task<bool> IsActiveAsync(ClaimsPrincipal subject)
        {

            return _membershipUserService.IsActiveAsync(subject);

        }

        #endregion

        #region Private methods

        protected virtual string GetDisplayNameForAccount(Guid accountId)
        {
            var acct = _userAccountService.GetByID(accountId);

            var name = acct.Claims.Where(x => x.Type == Constants.ClaimTypes.Name).Select(x => x.Value).FirstOrDefault();
            if (name == null) name = acct.Claims.Where(x => x.Type == Constants.ClaimTypes.Name).Select(x => x.Value).FirstOrDefault();
            if (name == null) name = acct.Username;

            return name;
        }



        public static IUserService Configure()
        {
            var db = new DefaultMembershipRebootDatabase();
            var userRepository = new DefaultUserAccountRepository(db);
            var userAccountService = new UserAccountService(new MembershipRebootConfiguration(), userRepository);
            return new UserServiceCustom(userAccountService);
        }

        #endregion
    }
}

**Comment by RaulMo7** [comment]
My problem is this method IsActiveAsync, will be doing a bad setup?

**Comment by brockallen** [comment]
I take it you solved your problem?

**Comment by RaulMo7** [comment]
My temporary solution is to return always true in this method IsActiveAsync which when parallel requests shows the error mentioned above.

I await if fixed in the next version :(

**Comment by brockallen** [comment]
So what does your `Registration<IUserService>` look like? It feels like you might be using a singleton and not a new instance per request.

**Comment by RaulMo7** [comment]
var factory = new IdentityServerServiceFactory();
                    var svcFactory = new EntityFrameworkServiceFactory("IdSvr3Config");

                    svcFactory.ConfigureClients(Clients.Get());
                    svcFactory.ConfigureScopes(Scopes.Get());

                    factory.RegisterConfigurationServices(svcFactory);
                    factory.RegisterOperationalServices(svcFactory);

                    factory.CustomGrantValidator =
                        new Registration<ICustomGrantValidator>(typeof(CustomGrantValidator));

                    //var userService = new Thinktecture.IdentityServer.Core.Services.InMemory.InMemoryUserService(Users.Get());

                    var userService = UserServiceCustom.Configure();

                    factory.UserService = new Registration<IUserService>(resolver => userService);

**Comment by leastprivilege** [comment]
Yes you are using a singleton - make sure it is thread safe. Or switch to per-request instance creation.

**Comment by brockallen** [comment]
And check the docs on registering services: https://identityserver.github.io/Documentation/docs/advanced/customServices.html

**Comment by RaulMo7** [comment]
Thanks, I will test it

**Comment by RaulMo7** [comment]
Thanks guys, done!!!!!!
