### ISSUE TITLE
Value cannot be null exception after upgrade

### ISSUE THREAD

**Issue by mikethedarv** [IdentityServer/Thinktecture.IdentityServer3#868]
I just upgraded the following projects:

- IdentiyServer3 (from beta4 -> 1.0.2)
- .MembershipReboot (from beta4 -> 1.0.0)
- .EntityFramework (from beta4 -> 1.0.0)

After making the necessary code updates and running the automatic migrations for each, everything seems to be working well locally.  However after deploying to development hosted on Azure, I get the following yellow screen of death for any IdSvr endpoint.  
![screenshot](https://cloud.githubusercontent.com/assets/6820608/6036534/2c4c96f4-abfb-11e4-84a9-13ee03275230.png)

Any subsequent requests gives me the generic "A message has occurred" as shown in the second screenshot until I reset IIS.
![screenshot2](https://cloud.githubusercontent.com/assets/6820608/6036538/34741262-abfb-11e4-9275-fa0cd7b4e5c0.png)

The logs in the event viewer and azure diagnostics don't seem to contain any information that isn't in the YSOD.  I'm out of ideas what it could be or why it's working locally and not on Azure.

Any ideas or help is greatly appreciated!

**Comment by mikethedarv** [comment]
Very strange, but because I've needed to get this working, I've since pulled down the source, added them to my solution, removed the NuGet packages and referenced the thinktecture projects locally from my app's projects.  Once I got everything to build, I deployed and viola, works perfectly.  I'll try and dig deeper in to why this behavior is happening when I get a free chance.

**Comment by brockallen** [comment]
Ok, we'll close for now. Open a new issue if there's something new to report.
