### ISSUE TITLE
EnableHttpLogging causes anti forgery token verification error during partial log in.

### ISSUE THREAD

**Issue by kylesonaty** [IdentityServer/Thinktecture.IdentityServer3#871]
I have a partial log in where we migrate users accounts.

```csharp
 [HttpPost]
 [ValidateAntiForgeryToken]
 public async Task<ActionResult> Index(UsernameToEmailInputModel model)
```
and the **@Html.AntiForgeryToken()** is in the view and inside the form.

If the logging options are setup in the IdentityServerOptions has HTTP logging enabled 
```csharp
LoggingOptions = new LoggingOptions { EnableHttpLogging = true }
```

I will receive a generic error stating that **The required anti-forgery form field “__RequestVerificationToken” is not present Error in user Registration**

If I remove the anti forgery token from the view and the controller I get
**“This method or property is not supported after HttpRequest.GetBufferlessInputStream has been invoked.”**

**Comment by brockallen** [comment]
Mind checking something for me? Remove the `[ValidateAntiForgeryToken]` and see if you get *any* of your inputs in your MVC action method. I suspect you will not.

**Comment by brockallen** [comment]
So BTW, I have feeling this is an issue between WebAPI and ASP.NET -- WebAPI is consuming the entire request buffer (for the logging) and then outside of Web API (meaning ASP.NET) something's now broken/gone in the buffer.

**Comment by kylesonaty** [comment]
If I remove the ```[ValidateAntiForgeryToken]``` I get this error
**“This method or property is not supported after HttpRequest.GetBufferlessInputStream has been invoked.”** and it never makes it to the method.

**Comment by brockallen** [comment]
Right -- so we need to discuss, but I don't think there's much we can do. This is the two frameworks fighting each other.

**Comment by leastprivilege** [comment]
not much we can do here. Unless someone has an idea. closing for now.
