### ISSUE TITLE
UserInfo and others drop Claim ValueType

### ISSUE THREAD

**Issue by mryandot** [IdentityServer/Thinktecture.IdentityServer3#872]
Id tokens include non-string claims correctly, but the UserInfo Endpoint (and possible others) return claims as strings.  The simplest example is `updated_at`; when included in the id token, it appears as a number (`"updated_at": 1423073070,`), but when retrieved from the UserInfo endpoint, it appears as a string (`"updated_at": "1423073070",`).

This appears to be because UserInfo calls the ToClaimsDictionary extension in Core/Extensions/ClaimListExtensions.cs, which then calls a private GetValue method for each claim.  That method is hardcoded to handle the `address` claim, but returns all other claim values as strings, instead of parsing the value according to the CalimValueType.

**Comment by leastprivilege** [comment]
better? 

https://github.com/IdentityServer/Thinktecture.IdentityServer3/commit/5f3f32b66f27860c9a14363917c10daacdf52ff3

**Comment by mryandot** [comment]
It works for the claims I'm using.

That said, the OpenID standard allows for JSON Object and JSON Array values for custom claims; right now they're only properly encoded for the "address" claim because it's a hard-coded exception.  Is there a way to extend the logic to work for custom claims as well, perhaps using a new ClaimValueType, co-opting a current value, or attempting a JSON parse if it's wrapped in {} or [] characters?

Also, I can post this as a separate issue if you'd like, but the situation is reversed for the `address` claim; UserInfo serializes it correctly as a JSON Object, but the IdToken serializes it as a string that happens to contain a JSON object (assuming I'm reading the spec correctly and they should both act the same).

### UserInfo
```Javascript
  "address": {
    "street_address": "One Hacker Way",
    "locality": "Heidelberg",
    "postal_code": 69118,
    "country": "Germany"
  },
```
### IdToken
```Javascript
  "address": "{ \"street_address\": \"One Hacker Way\", \"locality\": \"Heidelberg\", \"postal_code\": 69118, \"country\": \"Germany\" }",
```

**Comment by leastprivilege** [comment]
Well - the ultimate issue is that the .net claims model only supports strings - and so does the JWT token handler (besides some special cases). As long as we use that there will always be a problem.

That said - i don't like complex types as claim values at all - been there (e.g. in the original .NET claim implementations where the value was an object). Creates complexity and versioning problems. keep it simple ;)
