### ISSUE TITLE
‘JavaScript Implicit Client – TokenManager’ does not use AngularJs 

### ISSUE THREAD

**Issue by sania13** [IdentityServer/Thinktecture.IdentityServer3#873]
Your Sample ‘JavaScript Implicit Client – TokenManager’ does not use AngularJs anymore to make requests. Any particular reason you removed that and switched to plain JavaScript?

**Comment by johnkors** [comment]
reactconf


;)

**Comment by brockallen** [comment]
Because using it was distracting. The point of the sample was to show the bare bones code to get and use token(s).

**Comment by sania13** [comment]
Thank you for your quick reply. AngularJs is very popular and getting a lot of attention from the dev community. To have IdentityServer sample working with AngularJs would definitely boost popularity of your product.

**Comment by brockallen** [comment]
Sorry, it's not our job to teach people how to build angular apps.
