### ISSUE TITLE
Nuget package for core classes.

### ISSUE THREAD

**Issue by pavanputhra** [IdentityServer/Thinktecture.IdentityServer3#877]
Suppose I am writing Client App where I want to refer to `ClaimTypes.Email` in `Thinktecture.IdentityServer.Core` namespace then I would like to install nuget package without needing owin dependency.

Or

Suppose I am implementing `IScopeStore` interface in separate class library project (Repository Pattern) then I would like to install nuget package without needing owin dependency.

Is there a nuget package which contains only core classes without owin dependency.

**Comment by brockallen** [comment]
No -- they're all defined in the core IdSvr assembly/NuGet as of now.

**Comment by leastprivilege** [comment]
Have you ever had a look at owin.dll? From all the dependencies you have - this is the one of your least concern ;) And this is our **only** dependency.

The claimtypes are also in the Thinktecture.IdentityModel.Client nuget package if that helps (and are really just the standard claim types defined in the spec plus a few extra ones - http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims)
