### ISSUE TITLE
Registration workflow

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/Thinktecture.IdentityServer3#878]
Now that I have settled into a design for my implementation, one key workflow tasked has yet to be vetted and I was curious on recommendations for implementation. High level overview:

Idv3 is hosted in a web api that uses MembershipReboot for its user store. The same API exposes end points for user account registration, claims manipulation, client management and several other functions. 

The question pertains to new account registration. The user registration end point will be restricted to a specific (trusted) client. After a call is made to the API to register the user, what is an acceptable way to then authenticate that user? The correct answer may be that there is not one since email verification will be enabled in the multi-tenant environment and simply returning the UserId (Guid in the case of MembershipReboot) and storing it in the calling app and later syncing it up with the matching subject claim may be sufficient however that then requires the calling app to be the implementer of the email verification process and thus would receive the necessary tokens. 

This seems like a fairly common scenario in a scalable STS implementation whose scope is broader than a single application.

**Comment by brockallen** [comment]
Lots of questions like this in the issue tracker history -- search for them. ALso, look at the custom user service project in the samples repo.
