### ISSUE TITLE
ICache Delete

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/Thinktecture.IdentityServer3#884]
Was the lack of a delete method on the interface intentional? I was getting around to cache this week and looked at both the default (which defaults to a rather "safe" 5 minutes) and the redis contrib project (which set them to 30 mins for users and 2 hours for clients and scopes) and was surprised to not a delete in the interface. 

The scenarios where I think it would be critical include:

- Changing client secret (removing old, adding new).
- Disabling a client
- Disabling a scope

In any one of those scenarios I would want to remove the existing cache entry and have it repopulated on the next retrieval. Yes, you still have tokens out there and need to mitigate those concerns as well but I would think that preventing new requests coming in with stale secrets or disabled objects would also be desirable.

**Comment by brockallen** [comment]
Within IdentityServer we don't change client secrets, disable clients, or disable scopes.

**Comment by jlegan** [comment]
Meaning? Clients secrets can be expired prematurely or even removed
entirely if there is reason to believe they have been leaked, clients can
be enabled or disabled and scopes can be enabled or disabled, can they not?
I am not implying that idv3 has the implementation of these concepts but
the classes support enablement and disablement and client secrets is simply
a collection. Since there is a cache implementation wired into the system
does it not make sense to expose the ability to remove items in these
cases? I am not worried about implementing it myself, more with
understanding what you meant and what I might be missing.

**Comment by brockallen** [comment]
My point is that the administration of IdentityServer is separate from the engine itself. So if/when the admin changes those values, IdSvr isn't involved. You do raise a point that we need to consider how to handle it, but in what we have no there's no point for a Delete.

**Comment by jlegan** [comment]
Understood. In the scenario I am dealing with there are two types of
clients: those created by us for our mobile apps, front ends and
intraservice communication. The other is for our clients whom are vetted
and have been granted rights, managed through scopes to add, remove and
update the clients they require to perform work themselves or delegate it
to a trusted third party. While caching certainly is desired functionality,
the implementation must be responsive enough to changes. I am comfortable
with implementing my own redis implementation and keeping the ttl
relatively low (5mins) which is reasonable. I agree that a delete does not
necessarily fit in the way ICache is implemented but a way to refresh or
flag it as stale would go a long way to making it much more flexible.

**Comment by brockallen** [comment]
Yea, that's how we envisioned this iteration of the cache working.

**Comment by jlegan** [comment]
Thanks Brock, as always.
