### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dandresini** [IdentityServer/Thinktecture.IdentityServer3#885]
Hello Dominick,
I would use Intentity Server to allow other companies to use my "Web Api". Notification should be made at Server level, from a PHP page or ASPX or MVC or other Web Api. What solution could be useful?
Each company may use all or part of the web api.
Thanks in advance.

**Comment by brockallen** [comment]
Yes, you can use IdentityServer to issue tokens to other companies for your APIs, but I don't quite follow the "notification should" comment.

**Comment by dandresini** [comment]
Excuse me, I want to explain that the call to the Web Api  can be made at server level (PHP page or ASPX or MVC or other Web Api). Every Company may use all or a part of web api. I seen Code Flow Examples and I want Know if is the right solution for my project.

**Comment by leastprivilege** [comment]
Either implicit for code flow - depends on your client architecture.
