### ISSUE TITLE
Token Revocation in 1.1 (latest stable nuget) - 404 Response

### ISSUE THREAD

**Issue by TD49** [IdentityServer/Thinktecture.IdentityServer3#886]
Using IdSvr3 latest nuget (stable) build 1.1, we noted you now support token revocation per https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/421.     

So we can already retrieve an access (reference) token and a refresh token.  However, when passing it into the new revoke endpoint, it returns a 404 - Not Found.     We followed the doc here: http://identityserver.github.io/Documentation/docs/endpoints/revocation.html 

Request:
```
POST https://localhost:44555/core/connect/revoke HTTP/1.1
Authorization: Basic dGVzdGNsaWVudDpzZWNyZXQ=

token=978239f6f1f0cefb4ed42c0450572ca4&token_type_hint=refresh_token
```

Response:
```HTTP Error 404.0 - Not Found```
```The resource you are looking for has been removed, had its name changed, or is temporarily unavailable```

The authorization is the Client id/secret used to originally retrieve the tokens. I confirmed the ```EnableTokenRevocationEndpoint``` is set to true in the IdSvr's ```EntityOptions``` on Startup.   Also re-verified the correct IdSvr 1.1 bits are referenced.    Before I begin removing the stable nuget build and pull in the bits with PDB from Git for debug, can you confirm whether this endpoint is truly active yet?

**Comment by TD49** [comment]
Also, the endpoint doesn't appear in discovery...  we enabled token, userinfo and revoke endpoints, but only saw this:
```
"token_endpoint": "https://localhost:44305/identity/connect/token",
"userinfo_endpoint": "https://localhost:44305/identity/connect/userinfo",
```
I understand all endpoint options are defaulted to true, but for our testing and this example I've set them explicitly as follows (part of the ```IdentityServerOptions``` snippet in Startup):
```C#
Endpoints = new EndpointOptions
{
    EnableCspReportEndpoint = false,
    EnableCheckSessionEndpoint = false,
    EnableEndSessionEndpoint = false,
    EnableAuthorizeEndpoint = false,
    EnableTokenEndpoint = true,
    EnableUserInfoEndpoint = true,
    EnableClientPermissionsEndpoint = false,
    EnableTokenRevocationEndpoint = true
},
```

**Comment by leastprivilege** [comment]
See the clients sample (CodeFlowClient) - it is working there.

**Comment by TD49** [comment]
Sample failed with same 404 when using our IdSvr host.   Also failed when we added the token revoke request to the RO sample client (as we're using RO grant primarily).     I'll need to debug (replace the nuget build with a direct reference to master Core for the PDB's), find out why our host won't expose that endpoint.

**Comment by TD49** [comment]
The client sample uses ```/revocation``` instead of ```/revoke```, but still getting a hard 404 response from the sample host with the master build of IdSvr3.  Note that I'm making raw HTTP calls now to test (see request sample in my first post above, it still applies only now going to IdSvr's core host).  Debug never hits the ```RevocationEndpointController``` POST endpoint at all.  Note that I'm trying to revoke a refresh token obtained from the same host (through RO grant using the ```roclient``` client).

**Comment by RaulMo7** [comment]
change url for: connect/revocation

**Comment by TD49** [comment]
Yes, thank you, good timing.  We also caught this looking at the samples just now.  The docs need correcting:  http://identityserver.github.io/Documentation/docs/endpoints/revocation.html

Also, we had an issue with ```EnableTokenRevocationEndpoint``` was being reset to ```false``` elsewhere in our custom host, but not a bug with IdSvr.   Problem resolved.

**Comment by brockallen** [comment]
Docs are now fixed. Thx.
