### ISSUE TITLE
authentication works correctly in iis express, but keeps on throwing 401 unatuhorized when hosted in iis

### ISSUE THREAD

**Issue by dagimf** [IdentityServer/Thinktecture.IdentityServer3#887]
Ok so i tried hosting the simplest oauth sample and the identity server both on iis, i have enable cors on the simplest oauth sample. So when i test the api using the javascript implicit client, on iis express it works flawlessly, it gets the token then when the token is sent the web api chacks the token and authorizes the javascript client. the problem happens when i move the javascript imlicit client, the identity server, and the simple oath web api is hosted on iis, the javascript brings back the token correctly but when the token is sent to the web api it always return 401 unauthorized. So is there any configuration i have to add in order to run it on iis. i have made sure that anonymous authentication is the only enab;ed authentication mode. Any help or pointer is deeply appreciated.

**Comment by leastprivilege** [comment]
Should work the same in IIS.

**Comment by crammer** [comment]
I think you need to add the certificate on your machine.

**Comment by dagimf** [comment]
i have added it to the trusted people folder for my local machine, plus the weird part is i get the token correctly, and the accesstokenvalidation does not require a certificate right since it get the key from the authorities well known configuration address? Ok so will be trying this on another machine, to see if the problem is with my device.

**Comment by henninga** [comment]
Did you get this working?
I've set up a webapi on iis and it keeps returning 401's but in iisexpress it works correctly.

**Comment by TheGiggler** [comment]
I'm having the exact problem.

Working great on local IIS, but on IIS 8, the bearer token is never parsed (I have tracing enabled) and 401 is always returned.

I've tried all sorts of IIS configuration tweaks to no avail.

Here's my setup in code:

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = idServerUrl,
                ValidationMode = Thinktecture.IdentityServer.AccessTokenValidation.ValidationMode.ValidationEndpoint,
                
                RequiredScopes = new[] { "sampleApi" }
            });

            app.UseResourceAuthorization(new SFL.Security.WebApi.ThinktectureResourceAuthorizationManager());
 
...

            config.Filters.Add(new AuthorizeAttribute());
            app.UseWebApi(config);


Thanks for any and all guidance!

**Comment by leastprivilege** [comment]
I am pretty sure this is a SSL problem when the IIS process tries to contact the token validation endpoint.

**Comment by henninga** [comment]
Is there any way I can debug that or get logs to prove/disprove that theory?

**Comment by henninga** [comment]
@leastprivilege You were right. I disabled https on idserver and everything worked out ok

**Comment by leastprivilege** [comment]
Which is of course not the right way of fixing it ;)

**Comment by henninga** [comment]
I know. This is only on my local dev machine. This will be configured differently in production environments
