### ISSUE TITLE
Add Owin Middleware to Thinktecture and support DI containers

### ISSUE THREAD

**Issue by v-vairam** [IdentityServer/Thinktecture.IdentityServer3#888]
Currently there is no support for Add Owin Middleware to Thinktecture and support DI containers natively. Need OwinMiddleware support for identity server where rout mapping can happen natively instead of Map().

**Comment by brockallen** [comment]
I don't follow the comments about "Add Owin Middleware" or "Map". Can you elaborate on your questions?

As for complaints for the DI system - search the closed issues. There are several threads that explain it.
