### ISSUE TITLE
AntiForgeryToken not working the provided samples

### ISSUE THREAD

**Issue by sandeepgaikwad** [IdentityServer/Thinktecture.IdentityServer3#891]
I am using Thinktecture Identity server 3. 
I am trying to implement  [ValidateAntiForgeryToken] in my application and am referring the MVC Authentication project provided in the  samples.
But the sample itself is not working for ValidateAntiForgeryToken.
AntiForgery configuration in the sample app is : AntiForgeryConfig.UniqueClaimTypeIdentifier = Constants.ClaimTypes.Subject;

But when I decorate a controller action method (e.g. home/logout), as follows
 [ValidateAntiForgeryToken]
        public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut();
            return Redirect("/");
        }

The sample app returns exception with below message:
The required anti-forgery cookie "__RequestVerificationToken" is not present.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Web.Mvc.HttpAntiForgeryException: The required anti-forgery cookie "__RequestVerificationToken" is not present.

**Comment by brockallen** [comment]
This sounds like a MVC issue, not an IdSvr issue. It also sounds like you are missing a Html.AntiForgeryToken in the <form>

**Comment by sandeepgaikwad** [comment]
Yes, I was missing that,
Thanks for pointing out
