### ISSUE TITLE
IdentityServer 3 with ADFS in SPA

### ISSUE THREAD

**Issue by githubpushp** [IdentityServer/Thinktecture.IdentityServer3#893]
I am building a multitenant SPA witha Emberjs. Some of the tenants will signin with ADFS whereas others will use the application auth framework (AspIdentity).

I've been running the 'JavaScript Implicit Client - Simple' sample and have ADFS and IdentityServer running on the same machine. As part of the ADFS configuration in IdSrv I have replaced below with my adfs and rp values. I've configured relying party as javascript app url in adfs. Does it need to be IdSrv url ?

![image](https://cloud.githubusercontent.com/assets/367399/6107271/4403d724-b08f-11e4-9463-7f0d0f0d3698.png)

The problem is that I am able to reach the adfs signin page and successfully signin but not able to get token & claims back to the javascript client. Wanted to know what kind of adfs/IdSrv configuration will make this work.

Here are the url's for my setup - 

IdSrv - https://localhost/IdentityServer/
Client - https://localhost/javascriptclient/

**Comment by leastprivilege** [comment]
the return URL in ADFS must be pointing back to IdSrv.

**Comment by githubpushp** [comment]
Thanks Dominick,

Still having trouble. After signin to adfs the redirection (rather post) happens to IdSrv but here is what I get

![image](https://cloud.githubusercontent.com/assets/367399/6123475/3b240d14-b129-11e4-9b94-5660305661f4.png)

Below is my configuration - 

In Code - 
![image](https://cloud.githubusercontent.com/assets/367399/6123549/014d075c-b12a-11e4-9e0f-6c987a12517e.png)

In ADFS I have the relying party trust setup - 
![image](https://cloud.githubusercontent.com/assets/367399/6123613/a4207ef0-b12a-11e4-8799-0b8b9a8da7c6.png)

Do I need to do anything else ?

**Comment by johnkors** [comment]
@githubpushp We got it working like described here: #901

**Comment by mschulz531** [comment]
I have a question about the return URL in ADFS must be pointing back to IdSrv...what is the correct format of this URL?

I have app.fabrikam.com for my application, idsrv.fabrikam.com, and sts.fabrikam.com configured.
sts.fabrikam.com is my adfs server.

For the Relying Part Trust that I have configured on the ADFS server, what is the correct value of the WS-Federation Passive Endpoint value?  Here's what I have:

https://idsrv.fabrikam.com/   POST   default-true

Is this correct or should it be something else?

**Comment by johnkors** [comment]
Did it work with ```https://idsrv.fabrikam.com/ ``` as a callback uri in ADFS? Not sure if I'm correct, but I'm guessing the callback should be an URL not conflicting with anything else, so ```https://idsrv.fabrikam.com/anythingherenotusedbyanyotherrouteinidsrv```

**Comment by leastprivilege** [comment]
Resolved?
