### ISSUE TITLE
"Big name" users of Thinktecture.IdentityServer3?

### ISSUE THREAD

**Issue by jnpwly** [IdentityServer/Thinktecture.IdentityServer3#894]
I am integrating OAuth 2.0 with an existing WebAPI 2 API, and have plumped for using Thinktecture's IdentityServer.v3, a decision about which I'm pretty happy. However, out of curiosity's sake, I'm wondering if there are any "big name" users of this component?

**Comment by leastprivilege** [comment]
Yes. But most of the time this is under nda.

**Comment by jnpwly** [comment]
Thanks, @leastprivilege ;)
