### ISSUE TITLE
Questions related to SPA with no backend

### ISSUE THREAD

**Issue by mikkark** [IdentityServer/Thinktecture.IdentityServer3#899]
We are implementing an application using Angular (no web server) + WebAPI and Identity Server. We are currently planning to use the implicit flow (client requests for token + id_token). I have a few questions.

1) What is essentially the purpose of the /endsession end point. The code in the controller seems to do very little. I think in my scenario "logging out" really just means emptying the access_token property in our Javascript model, right?

2) Isn't it right to say that the access token life span dictates the session length in the browser? Since we can not store a refresh token in the client (see question 3 too) we can only ask the user to log in again when the access token expires.

3) I would probably get the kind of flow I want if IdentityServer sent the SPA a refresh token in a secure, http-only cookie instead of using a URL fragment. This way I could ask the IdentityServer for an access token and the IdentityServer would get the refresh token from the cookie. This would probably need some extending/modifying in the IdentityServer code. What are your thoughts about this, do you see it would be feasible and doable?

Thanks in advance.

**Comment by johnkors** [comment]
1) Single Sign Out
2) and 3) This sample shows how you may achieve that. https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/tree/master/source/OAuthJS/JsImplicitOAuthLibraryDemo

**Comment by mikkark** [comment]
Thanks for a quick response. I understand now where I went off the right track: I stared at the refresh token as something you need to use when getting a new access token. Sure it is meant for that but more on the server side and for very long expiration times. The method described in the sample you referred me to is so simple and fits our scenario perfectly. It even comes with lots of ready-made JS code to handle the tokens :) Thank you!
