### ISSUE TITLE
How to connect Identity server 3 with MembershipReboot

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#903]
1.How to connect Identity server 3 with the MembershipReboot
2. what is difference between Membership-reboot and identity Manager

**Comment by khushalpatel1981** [comment]
Check identityserver sample project and their implementation on Vimeo 

-----Original Message-----

**Comment by RajMondaz** [comment]
ya ,i saw that but that video they have released in the initially but now Identity server 3 is updated and  Membership Reboot also changed i am not able to go through that because of so many changes..

**Comment by khushalpatel1981** [comment]
Have you checked samples project they have implementation for that 

-----Original Message-----

**Comment by RajMondaz** [comment]
ya, i have checked that in that they are connecting to the Identity server 3 and in that they will be having the predefined user i need to get the user from the MembershipReboot..

**Comment by eaba** [comment]
Look at the membershipreboot sample or you study the aspidentity sample.
