### ISSUE TITLE
User Import Registration Workflow Question

### ISSUE THREAD

**Issue by ltraus** [IdentityServer/Thinktecture.IdentityServer3#904]
So, going through everything in the examples ive worked with resource owner flow, implicit and hybrid.  I've actually found i may go with FormPost.

I have an existing user base, that i want to maintain with an existing logon flow, but want to do the addition of.

- Form Post
- Claims Transformation Callback.

That way i can somewhat maintain the existing workflow.

But i'm struggling seeing how i could do the following.

- Registration workflow against the idsrv.

Other then building my own implicit flow for a client to register users through an api and update/passwords etc; I'm not sure how to do this exactly.

When the user has been logged in through the idsrv i would assume that i would be managing the passwords through the self service via idsrv, but ultimately i need to maintain the 2 seperate flows.

Is there a direction you could shove me in or an example about the user registration workflow and user management that i'm just blanket missing?

**Comment by ltraus** [comment]
I also have the use of Identity Manager in there as well.  Which i plan to restrict to support for a specific company role.

**Comment by brockallen** [comment]
I don't totally understand the question, but 1) IdentityServer issues tokens and it does not do user-registration or use self-service of profile and passwords, and 2) If you want registration, etc, then build a new client application for that. This registration app should be able to update the database that IdSvr uses for its users.

**Comment by ltraus** [comment]
Well actually you kind of answered my ill written question anyway.

We need a way to bulk export users, an api seems the only way, i wondered for a while if i could leverage the identity manager.

But, ultimately based on your response ill head towards a (2).

And it will give us a way for our current client application to;

- update a password
- register a user

**Comment by brockallen** [comment]
Yep, that's how many of our clients are doing it.

**Comment by ltraus** [comment]
My brains turned to mush :) thanks.  Off to the next example :+1:
