### ISSUE TITLE
Upgrading from beta to 1.1.0

### ISSUE THREAD

**Issue by mstrong64** [IdentityServer/Thinktecture.IdentityServer3#905]
Is there documentation on what has changed from the beta and how to implement code that used to work? I'm hitting issues with (at least) the following:

Lots of calls to ResolveDependency which is now internal e.g:

`var tokenValidator = Request.GetOwinContext().Environment.ResolveDependency<TokenValidator>();`

Accessing cookies:

`var cookie = new MessageCookie<SignInMessage>(Request.GetOwinContext().Environment, _opts);`

A number of missing properties on `Client`, and `ClientSecret` is now a list. I suppose I can just ignore the missing properties?

I was also using the `StringExtensions` but I just wrote my own version for the ones I was using. 

Thanks.

**Comment by brockallen** [comment]
We only have the issue tracker and source control to indicate changes up and until release. If we internalized something that used to work it's because we decided it needed to be locked down for a reason. If you have a more specific question, then ask away.

**Comment by mstrong64** [comment]
OK thanks Brock. I'm working through the issues today.

**Comment by mstrong64** [comment]
In my MVC controllers I need to get access to (for example) the `IdentityServerOptions`. Using the beta version I was using:

`var _opts = Request.GetOwinContext().Environment.ResolveDependency<IdentityServerOptions>();`

What is the recommended way to do this now?

**Comment by brockallen** [comment]
You can inject the OwinEnvironmentService as a ctor param -- it has the environment dictionary.

**Comment by brockallen** [comment]
Oh sorry, you can also inject the Options too.

**Comment by mstrong64** [comment]
OK so I must be doing something wrong. System.Web.Mvc is creating my controller and is expecting a parameterless constructor. How do I get around this? I basically want to add registration functionality to IdSrv. Here is my controller's constructor:

`public LocalRegistrationController(IdentityServerOptions opts, MyUserManager userManager)`
       ` {`
           ` _opts = opts;`
           ` _userManager = userManager;`
        `}`

**Comment by johnkors** [comment]
Seems you are already using some kind of IoC framework already for MyUserManager. How about registering it there?

**Comment by mstrong64** [comment]
Sorry, that wasn't very clear. By "registration" I mean add a new user to the database, not registering classes with an IoC framework. 

I have an MVC project that is hosting IdSrv and I want to add some web pages for registering new users.

**Comment by johnkors** [comment]
.. and for this you need the IdentityServerOptions for some reason, and you want it to be injected into an MVC controller outside Idsrv. What I was proposing was registering IdentityServerOptions in whatever IoC framework you're already using (presumption on by part seeing as you already inject something into a MVC Controller, namely your ```MyUserManager```).

**Comment by mstrong64** [comment]
Yes, I need this outside the IdSrv, but I'm not currently using any IoC framework in the MVC part. `MyUserManager` is registered with IdSrv and gets injected correctly for providing my custom services to IdSrv. The constructor I included is not being called by MVC, but it is an example of what I'd like to happen. Brock mentioned injection via a ctor param so I gave it go :)

I'm new to Owin, IoC, IdSrv and OIDC so code examples are very helpful :)

**Comment by johnkors** [comment]
Yeah, so this issue tracker is not the best for learning all those concepts. If I were you, I would try to learn those core concepts before going into the deep end implementing a project utilizing all of those. Or ask ThinkTecture for consulting :)

**Comment by mstrong64** [comment]
Point taken, and I am doing lots of reading between asking questions :) My main point is that I had all this working well with the beta version of IdSrv, but since upgrading, a number of methods have been hidden. This thread is about how to achieve the same functionality I had before.

**Comment by brockallen** [comment]
Yea, I'm not sure what you're doing in MVC. If MVC won't hand you the ctor params you want then you should configure the DI system there. If we marked something as internal in RTM then we had a reason :)

**Comment by mstrong64** [comment]
Yes, I expect there were good reasons so I'm refactoring the code to do things differently. So far so good. I'll close this thread and open another if I have something specific. Cheers.
