### ISSUE TITLE
Logout Confirmation Not Displayed When PostLogout Redirect Matches

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/Thinktecture.IdentityServer3#906]
A while back I noticed that my logout confirmation page had disappeared, and it takes me directly to the "you are logged out" page.

At the time it was ok, but I may be required to show the confirmation page.
So, I looked into how to turn it back on.

I tried, EnableSignOutPrompt, but this was already set to true.
I alos tried a few other things as well. I went back to the sample code, and eventually found something.

I found out that if I come from a page that matches the PostLogoutRedirectUri, then the confirmation page will not be loaded. 

Is this by design?

**Comment by brockallen** [comment]
If you're already signed out (due to timeout/inactivity) then we just show what you're seeing. Also, if you pass the id_token_hint to the end session endpoint then we also do the same. We only allow the post logout URL if an id_token_hint is sent (as per the spec).

**Comment by parkinsona** [comment]
The user was not timed out.

And I am definitely sending through the id_token_hint.

Does that mean, the confirmation page will never show if the id_token_hint is sent through?

**Comment by leastprivilege** [comment]
If a valid id token hint is passed - the confirmation page will not show (as per spec)

**Comment by parkinsona** [comment]
Thanks for the info guys. 
This works for me. If I need a confirmation, I can always put it in the RP.
