### ISSUE TITLE
Creating authorization code in PreAuthenticateSync causes too many redirect error

### ISSUE THREAD

**Issue by v-vairam** [IdentityServer/Thinktecture.IdentityServer3#907]
Recieved following error when connecting from client using IMplicity: "has resulted in too many redirects. Clearing your cookies for this site or allowing third-party cookies may fix the problem. If not, it is possibly a server configuration issue and not a problem with your computer."

 public virtual Task<AuthenticateResult> PreAuthenticateAsync(SignInMessage message)
        {
            var result = new AuthenticateResult("bob", "bob");
            return Task.FromResult(result);
            //return Task.FromResult<AuthenticateResult>(null);
        }

**Comment by v-vairam** [comment]
The Unit test path also does not validate this code path condition:
Thinktecture.IdentityServer.Tests.Validation.TestUserService

**Comment by brockallen** [comment]
Is "bob" a matching subject identifier in the user store?

**Comment by v-vairam** [comment]
yes, same as in InMemoryUser list from examples

**Comment by brockallen** [comment]
That's your bug then -- the first param to the `AuthenticateResult` is the subject identifier. "bob" is just the username. That user's subject value is "88421113".

**Comment by brockallen** [comment]
Did this fix it for you?

**Comment by v-vairam** [comment]
this is what I have customized and actually it did not work without those additional claim types or the default InMemorUser construct. it worked without PreAuthenticateSync:
new InMemoryUser{Subject = "bob", Username = "bob", Password = "bob", 
                    Claims = new Claim[]
                    {
                        new Claim(ClaimTypes.Name, "bob"),
                        new Claim(ClaimTypes.Upn, "BobSmith@email.com"),
                        new Claim(ClaimTypes.Email, "BobSmith@email.com"),
                        new Claim(ClaimTypes.GivenName, "Bob"),
                        new Claim(ClaimTypes.Expiration, UserService.ConvertDate(DateTime.Now.AddHours(1))),
                        new Claim(ClaimTypes.Surname, "Smith"),
                    }
                }
