### ISSUE TITLE
Instead of loading Predefined user list to the InMemoryUser ,How we can take single record from database based on is username and Password to this paricular record we have to authenticate.

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#908]
Below functions, we are calling from start-up class in idsrv3 in this we are loading all the predefined user information like users ,clients and scopes 

There is no need to load the all user list to idsrv3 because if we are having 1 lakh users we have to load all the users instead of this while lo-gin i need to take particular user information when he is doing login based the that user name and password we can  authenticate using this user information.

![image](https://cloud.githubusercontent.com/assets/10266752/6148737/fa325ab6-b229-11e4-8699-f432cf748660.png)

Instead of loading all the  user Details  to InMemoryUser like below example , we can take particular user info based user name and password from the data base.

![image](https://cloud.githubusercontent.com/assets/10266752/6148696/b5dbae6c-b229-11e4-88a7-415429e0b83b.png)

**Comment by brockallen** [comment]
The in-memory user collection is simply for testing purposes. We don't expect people to do this in production scenarios. Instead we'd expect you to define a user service, as documented here:

https://identityserver.github.io/Documentation/docs/advanced/userService.html

**Comment by RajMondaz** [comment]
For this user Services whether we have to use Membership Reboot.?

**Comment by RajMondaz** [comment]
ok thanks.
