### ISSUE TITLE
Can a client use ResourceOwner and ClientCredentials flows simultaneously?

### ISSUE THREAD

**Issue by soliveira** [IdentityServer/Thinktecture.IdentityServer3#911]
Hi I'm implementing an API that require both Client Authentication and User Authorization, however not all endpoints require a user logged in. For this situation the client uses client credentials flow. For authenticating a user the client needs the resource owner flow. 

Can this be done using a single client?
thks

**Comment by brockallen** [comment]
All the API cares is that it gets a token with the right scope. The other claims in the token might vary based upon how it was obtained, but sure this is possible. For APIs that don't need that, then they allow calls without a token (IOW, they don't use `[Authorize]`).

**Comment by leastprivilege** [comment]
A client can only use one flow (aka grant type). You'd need to create two clients for that.

**Comment by leastprivilege** [comment]
I will add that feature - see #915
