### ISSUE TITLE
Set Authentication Cookie to persistent for preauthenticate

### ISSUE THREAD

**Issue by jageall** [IdentityServer/Thinktecture.IdentityServer3#913]
The scenario we have to support is reset password. 

The user resets their password which sets a cookie. the remember me option is stashed inside the cookie along with sub and username.

The preauthenticate method uses the cookie to generate an AuthenticateResult, but there is no way to pass the remember me value back to the AuthenticationController so it can be used when it issues the authentication cookie

**Comment by jageall** [comment]
From @brockallen  via gitter:

the thing to consider is that for the normal login, the user could check the checkbox but also the AuthenticateResult might have a value
so i'd have to think about what rules we'd want to deal with conflicting values
and perhaps it's too complicated, so then we might not want to allow it

**Comment by jageall** [comment]
looking at the other methods, I don't think that AuthenticateResult is a great place to put it, the only time it really makes sense to set it is the preauth method. Some other options might be

**Comment by VictorBlomberg** [comment]
We have a similar scenario where this would be really useful. The rules proposed above seems great.

**Comment by brockallen** [comment]
Perhaps a `PreAuthenticateResult` where this can be set. Certainly a breaking change.

**Comment by jageall** [comment]
PreAuthenticateResult would be much clearer than adding a parameter.  Are feature requests that are breaking changes likely to get pushed to a 2.x release?

**Comment by leastprivilege** [comment]
Since we are using SemVer - yes.

**Comment by rayph** [comment]
Just adding weight to this one, I think it's a good feature and was just hunting around for a way to do this. Looking forward to the enhancement!

**Comment by brockallen** [comment]
James, would this help you out? https://github.com/IdentityServer/Thinktecture.IdentityServer3/commit/349e4bc84a2cf32513ef7d6d137bf7fa78a5c09d

**Comment by jageall** [comment]
It would, although setting that cookie is what i was doing before. I
actually ran into it as a problem because the session_state wasn't being
returned when doing that, so this with #1017 would solve the problem for
me. And this way looks like it would be a minor version bump rather than
major which would mean i got it sooner :D

**Comment by brockallen** [comment]
Yes, I'm working on the session state issue now.
