### ISSUE TITLE
Refresh tokens lost on reboot?

### ISSUE THREAD

**Issue by LorryMoller** [IdentityServer/Thinktecture.IdentityServer3#914]
Are refresh tokens lost when Identity server is rebooted? I don't see a column for them in the database (are they just in-memory?), and the refresh tokens already issued to clients don't seem to work after I update idsrv3 and redeploy (even when the db is left intact). 

(I am using beta 3 if that matters)

**Comment by brockallen** [comment]
The docs indicate you need a persistent store for those. The defaults used by the sample host are in-memory only.

**Comment by LorryMoller** [comment]
I am using entity framework membership reboot for persistence; is there a hook in there that gets called when a refresh token is created? 
I'm not sure where the docs you're mentioning are located, I can't see it in any of the EF Membership reboot docs (or the identityserver docs)

**Comment by brockallen** [comment]
MR is for the user data. The EF repo I'm talking about is this one:

https://github.com/IdentityServer/Thinktecture.IdentityServer3.EntityFramework

**Comment by LorryMoller** [comment]
Ok thanks! I don't see any docs for that but it gets me started.

**Comment by brockallen** [comment]
Also look at the EF project in the samples repo.

**Comment by LorryMoller** [comment]
Thanks again. And now I see the link to the refresh token store under the service factory stuff (http://identityserver.github.io/Documentation/docs/configuration/serviceFactory.html)

**Comment by Pugglewuggle** [comment]
This really should be better documented. For a .NET Foundation project, this is the worst documented one I've seen. I've watched all of the videos on Vimeo and read tons of documentation. I've worked on this for a month. This is the first mention I've seen of how to accomplish this. It almost seems as if somebody wants consulting $$$ instead of just writing decent documentation!
