### ISSUE TITLE
Allow Client Credentials flow for any client

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/Thinktecture.IdentityServer3#915]
E.g. allow Code Flow + Client Creds, or Resource Owner + Client Creds 

without having to create two separate clients.

**Comment by johnkors** [comment]
+1! :)

**Comment by jlegan** [comment]
That would be great, I just ran into this last night!

**Comment by johnkors** [comment]
What about hybrid?

**Comment by leastprivilege** [comment]
"Any" :)

**Comment by soliveira** [comment]
Great thks

**Comment by s093294** [comment]
Great, no more adding two clienets. 

almost 1000 issues back we did talk about it :) https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/79

**Comment by snothub** [comment]
Can you provide an example for how to use this? I keep getting "Client not authorized for client credentials flow" when attempting to run code below. Do I have to change the client configuration somehow?

            var client = new OAuth2Client("https://myidsrv/core/connect/token, "ro-client", "secret");
            var result = client.RequestClientCredentialsAsync("read").Result;

**Comment by johnkors** [comment]
Yep, I believe this will do it. 

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Models/Client.cs#L79

**Comment by snothub** [comment]
Takk @johnkors :)

**Comment by brockallen** [comment]
A word of caution about using this feature -- it should only be used for confidential clients. If you use this for a public client, and are expecting the server side to use the client credentials to obtain an access token for a more restricted scope, then an attacker can forge a request from the public client for that more restricted scope and that access token might be exposed via the user agent redirects.
