### ISSUE TITLE
Redirect URL Issue

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#916]
In the Below example my redireact url is http://abc.in  

![image](https://cloud.githubusercontent.com/assets/10266752/6189828/9afab9ee-b3c3-11e4-9065-5abcd81bed13.png)

if i am trying login with WWW like http://www.abc.in at that time after redirect from idsrv  it is not matching the url and giving the error

![image](https://cloud.githubusercontent.com/assets/10266752/6189875/12ffc48e-b3c4-11e4-95ee-a7f5d4d1cd9f.png)

**Comment by omanaev** [comment]
I am having the same problem as well. The TempCookie is set in the client code and is received by the identity server however it is not sent back when the post back occurs. The client code expects the TempCookie to be present in the call back to get the state and nonce.

   private async Task<IEnumerable<Claim>> ValidateIdentityTokenAsync(string token, string state)
        {
........................................

	        var result = await Request
                .GetOwinContext()
                .Authentication
                .AuthenticateAsync("TempCookie");
	        
            if (result == null)
	        {
		        throw new InvalidOperationException("No temp cookie");
	        }

**Comment by brockallen** [comment]
Well, that's in the client application -- you'd need to debug the cookie a bit more at the HTTP level to get some more information.

**Comment by omanaev** [comment]
The problem is the cookie is not sent by the server in the call back. The HTTP trace shows the TempCookie present in the first GET request going to the server. The POST from the server to the client site (call back) does not have the TempCookie. However the client clearly expects it. What kind of information should I look for in the HTTP request?

**Comment by brockallen** [comment]
The temp cookie is set by the MVC client application to hold the state and nonce -- this is the temp cookie you are asking about, correct? IdentityServer has nothing to do with this cookie, so you just need to debug why the cookie is not kept within the application.

**Comment by omanaev** [comment]
But isn't it the Identity Server that invokes the HTTP POST to the client site?
This method is called when the client site receives the HTTP POST coming from the identity server
  [HttpPost]
        public async Task<ActionResult> SignInCallback()

In this case the client site acts as server to the Idenity server. Am I missing something here?

**Comment by brockallen** [comment]
The only thing I can think of is that the site that the cookie is being issued to is different than the site that IdSvr is posting back to -- check that the scheme, host, etc. are all the same. From where I sit it's very hard to tell what the problem is.

**Comment by omanaev** [comment]
Yes, the sites are, of course, different. Site 1 (client site www.usersite.com) wants to use Site 2 (www.identityserver.com). Are you saying for this to work properly client sites and the identity server must belong to the same domain but running on different ports?

**Comment by brockallen** [comment]
No, I meant the client app -- is it somehow being accessed via a different hostname than the redirect origin? IOW, same machine, but the browser doesn't recognize that it's the same (since it's got 2 different mapped DNS entries).

**Comment by omanaev** [comment]
Yep, you got it. 
The browser connects to the localhost (client site)
When the localhost serves as the client site and the callback occurs via the IP address, the cookie disappears. If I point the browser to the actual IP of the client host, it works.
Appreciate your help!

**Comment by krishna1682** [comment]
I am having Similar issue, but happing only few machines. Do we need to do any browser settings?
