### ISSUE TITLE
Name claim not included in ResourceOwner flow

### ISSUE THREAD

**Issue by mmisztal1980** [IdentityServer/Thinktecture.IdentityServer3#918]
I've got a resource owner flow client, after making a ```client.RequestResourceOwnerPasswordAsync``` call, I'm getting the following token below.

I've noticed that the name claim is not present in the token. How should I proceed in order to ensure that it is included?

eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJjbGllbnRfaWQiOiJ0ZXN0UmVzb3VyY2VPd25lckNsaWVudCIsInNjb3BlIjpbImFwaV9hY2Nlc3MiLCJvcGVuaWQiLCJyb2xlcyJdLCJzdWIiOiI4ODQyMTExMyIsImFtciI6InBhc3N3b3JkIiwiYXV0aF90aW1lIjoiMTQyMzg0OTQ1MSIsImlkcCI6Imlkc3J2IiwiaXNzIjoiaHR0cDovL2Nsb3VkLXRlY2hub2xvZ2llcy5uZXQiLCJhdWQiOiJodHRwOi8vY2xvdWQtdGVjaG5vbG9naWVzLm5ldC9yZXNvdXJjZXMiLCJleHAiOjE0MjM4NTMwNTEsIm5iZiI6MTQyMzg0OTQ1MX0.JlgN07qoia7s-nt990VCAqoWKMMpTOlVIziqwtkGqiviUFJBmgifBjL46-CtA2vk3aJk1LqsvVyujBrTHNNs_scyDh-6g2fovxID_tnCrP-xTrYwV4MkhPI95JTQt4zs8n5v061eohJy1-p-zdSDjnuGxgpihHP-1lHQTL1ZlruEOhvMLuiPzoFNzMzAuzRA68LZlqvjaMsaaANXDJJuW8PZfDfZ3zwJTYIyB2i_VpaaM4xybaBsnteqJN8nI1Nh9fW7Y-lbCZ0Pyq3OYr3yGJ-B2JJT3PRcaMEpClfaVOckAAg47xBcTi1bi2RUjJzUXl8t-PKFUVtv7q0vOAgC6w

**Comment by brockallen** [comment]
Read up on scopes and claims:
https://identityserver.github.io/Documentation/docs/configuration/scopesAndClaims.html

**Comment by mmisztal1980** [comment]
Ok, so you're trying to tell me that I should have a custom scope with the "name" scope-claim? Is that it?

**Comment by brockallen** [comment]
The docs told you that (not me) :) 

I was just trying to nudge you (and others) at the docs as much as possible.

**Comment by mmisztal1980** [comment]
Thanks Brock :) much apreciated :)
