### ISSUE TITLE
Cached IdentityServerHost Value

### ISSUE THREAD

**Issue by CHog** [IdentityServer/Thinktecture.IdentityServer3#919]
Constants.OwinEnvironment.IdentityServerHost is currently cached to be the first scheme and host that hits the IdentityServer.

This value is later used for setting the address of scripts or redirects.  My issue is that when I have a server that uses different names (internal network vs external), the first scheme/host is cached, and if I use the other, to hit the server, I am given the cached address.

Your IdentityServerBasePath is set up on each request, which is what I would like.  The following change gave me this ability:
var request = ctx.Request;
var localPublicOrigin = publicOrigin;
if (localPublicOrigin.IsMissing())
{
	localPublicOrigin = request.Uri.Scheme + "://" + request.Host.Value;
}

Is there any way, or reason that this couldn't be done?

**Comment by brockallen** [comment]
Don't we set the host on every request into the OWIN environment?

**Comment by CHog** [comment]
You have two variables.
your code does:
ctx.Environment.SetIdentityServerHost(publicOrigin);               ctx.Environment.SetIdentityServerBasePath(ctx.Request.PathBase.Value.EnsureTrailingSlash());

publicOrigin is set in the Options or is set automatically off the first request to the server.

**Comment by brockallen** [comment]
Oh yes, I am seeing it clearly now (I guess that's what I get for being clever with the captured local variable).

Ok, I can change it to not do the caching.

**Comment by brockallen** [comment]
Ok, done on dev.

**Comment by CHog** [comment]
Thank you!
