### ISSUE TITLE
Method Not Allowed trying to get Identity Server to work

### ISSUE THREAD

**Issue by kkfrosty** [IdentityServer/Thinktecture.IdentityServer3#921]
Downloaded the IdentityServer3 zip from github.

Opened the source solution in Visual studio.  Changed the web properties to use IIS and called the virtual directory IdSrv.

I changed the Cert.Load() method to load the certificate used on my IIS website.

I opened the "Simplest" OAuth2 walk through solution.  I changed the Uri for both instances of the OAuth2Client to my URL.

On the server host project, I added the Scopes, Clients and users from the "Simplest" project.

I step into the simplest project and the call to client.RequestClientCredentialsAsync returns a response and the HttpErrorReason is Method Not Allowed.

Thus there is no token and and the rest fails. I'm just looking for any type of basic documentation, samples etc how to get this server setup and just one example to work.  I've spent about a week now digging around.

FYI.  The exact same thing happens, if I use the Apis web project in the sample.

**Comment by leastprivilege** [comment]
The main source repo and the client sample solution are designed to work together as-is. Maybe give this a try. IIS is more picky when it comes to trailing slashes than IIS Express. Maybe that's a problem.

**Comment by kkfrosty** [comment]
Thanks Dominick,

 

The sample itself, I just unzipped loaded in Visual Studio and tried to run and get the exact same problem.

 

There are no trailing slashes.  I’ve tried them with.

 

        static void Main(string[] args)

        {

            var response = GetClientToken();

            CallApi(response);

 

            response = GetUserToken();

            CallApi(response);

        }

 

        static void CallApi(TokenResponse response)

        {

            var client = new HttpClient();

            client.SetBearerToken(response.AccessToken);

 

            Console.WriteLine(client.GetStringAsync("http://localhost:14869/test").Result);

        }

 

        static TokenResponse GetClientToken()

        {

            var client = new OAuth2Client(

                new Uri("https://localhost/IdSvr"),

                //new Uri("https://localhost:44333"),

                

                "silicon",

                "F621F470-9731-4A25-80EF-67A6F7C5F4B8");

 

            return client.RequestClientCredentialsAsync("api1").Result;

        }

 

        static TokenResponse GetUserToken()

        {

            var client = new OAuth2Client(

                new Uri("https://localhost/IdSvr"),

                //new Uri("https://localhost/connect/token"),

                //new Uri("https://localhost:44333"),

                "carbon",

                "21B5F798-BE55-42BC-8AA8-0025B903DC3B");

 

            return client.RequestResourceOwnerPasswordAsync("bob", "bob", "api1").Result;

        }

I’m developing on Windows 8.1, Visual Studio 2013 Ultimate with all the latest updates.

**Comment by leastprivilege** [comment]
I said the clients sample solution from the samples repo.

https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/tree/master/source/Clients

Together with our original unmodified main repo source.

Once you got that working - you can start having a look which of your modifications broke it.

**Comment by kkfrosty** [comment]
I am using those samples.

 

For the samples, the URL is https://localhost:44333/connect/token

 

In trying to guess what a URL would work with the framework sample hosted in IIS, the connect/token got removed.

 

So instead of a not found, you apparently get Method Not allowed.

 

The sample is back to the way it was.  

 

Now how do you figure out what Uri is need to connect properly to the server host?

 

https://localhost/IdSvr/connect/token doesn’t work.

 

I’m starting to think the host project in the Server source solution doesn’t map routes or something.

 

Again it appears Method Not Allowed is a result of not being about to map to a controller method.

**Comment by leastprivilege** [comment]
No - the source repo uses

https://localhost:44333/core/connect/*

**Comment by leastprivilege** [comment]
Also the start page has a link to the discovery document - this has all the other URLs.

**Comment by kkfrosty** [comment]
Thanks Dominick,
This code fixed the issue.
 static TokenResponse GetClientToken()
        {
            var client = new OAuth2Client(
               // new Uri("https://localhost:44333/connect/token"),
                new Uri("https://localhost/IdSvr/core/connect/token"),
                "silicon",
                "F621F470-9731-4A25-80EF-67A6F7C5F4B8");

            return client.RequestClientCredentialsAsync("api1").Result;
        }

A token comes back now.
