### ISSUE TITLE
Custom View Service + Linking Logins

### ISSUE THREAD

**Issue by coreyperkins** [IdentityServer/Thinktecture.IdentityServer3#923]
I have been successfully using the first release over the past couple of weeks. I have created custom view and injected them with a custom view service, everything is working great!

My question here is regarding linking logins. I have experience with the standard .net usage of oauth 2 for linking logins, however, I am not quite sure how to accomplish that with idsrv. I really like the view service and I don't want to lose it and the ability to use the logic idsrv has built in surrounding it. Otherwise, I would fallback to the standard .net usage of oauth 2 to allow for linking logins.

I also thought about forking the code to allow for linking logins. I have explored it quite a bit and I think it could be done, but with my limited experience I'd rather save that for a final option.

Any suggestions? Or perhaps I missed something along the way?

Thanks,

Corey

**Comment by brockallen** [comment]
I guess I don't follow... where do you want to link the logins? You want to link an external login to something in IdSvr?

**Comment by coreyperkins** [comment]
I want to link multiple external logins to a single user account.

I let idsrv manage all of the login-related pages my app sees by implementing my own IViewService and setting it on the IdentityServerServiceFactory.

Since idsrv manages these pages I am looking for the best way to create a "Manage" page that will allow the user to go in and add several external logins to their account.

When creating a new mvc app in VS there are methods provided to support this but I am not sure how best to mimic this functionality when allowing my app to login via idsrv.

// ManageController.ManageLogins (from a new mvc app)
// The call to GetExternalAuthenticationTypes() will return my idsrv configuration rather than a list of external providers that I have configured within idsrv.
var otherLogins = AuthenticationManager.GetExternalAuthenticationTypes().Where(auth => userLogins.All(ul => auth.AuthenticationType != ul.LoginProvider)).ToList();

// Other supporting methods (from a new mvc app)
ManageController.LinkLogin
ManageController.LinkLoginCallback

The idsrv "LoginViewModel" has some info available that would allow me to construct such a page (AdditionalLinks and ExternalProviders). If those collections were available for the "ClientPermissionsViewModel" I could possibly use it to create what I am after.

I will create some code asap and post it to better show what I'm shooting for.

Thanks!

**Comment by brockallen** [comment]
So this app is like a self-service app for users to manage their accounts. I'd model it as a separate app to IdSvr that updates the same DB IdSvr uses. And when a user needs to login, it trusts IdSvr as the IdP. And yes, you'll have to make the pages share the same look & feel. Not sure how to make that easier.

**Comment by coreyperkins** [comment]
Good deal. Thanks.

Question answered, closing.
