### ISSUE TITLE
AntiXssLibrary bringing in System.Web as a transitive reference.

### ISSUE THREAD

**Issue by damianh** [IdentityServer/Thinktecture.IdentityServer3#925]
As a dependency free dll, we don't want a dependency on System.Web.

![image](https://cloud.githubusercontent.com/assets/57436/6215490/7afd1728-b601-11e4-93d1-622ca06422d4.png)

There is also a reference to System.Web.Extensions which is probably undesirable too.

**Comment by leastprivilege** [comment]
@blowdart is that needed?

**Comment by blowdart** [comment]
The reference? Yes, if you're using the nuget package - it's there because of the config support. You could compile up your own version, dropping that, or if you're on .net 4.0+ just use the built in version and use config to swap it out.

**Comment by brockallen** [comment]
Where's the ASP5 version? We'll just grab that one instead... *grin*

**Comment by blowdart** [comment]
It's being gutted and redone for 5 and will be the *only* encoder in 5.

**Comment by thefringeninja** [comment]
It appears to be used in ~~6~~ 3 places, just for safely htmlencoding strings.

**Comment by thefringeninja** [comment]
Is there a reason to use AntuXssLibrary instead of https://msdn.microsoft.com/en-us/library/ee388364(v=vs.110).aspx?

**Comment by thefringeninja** [comment]
https://github.com/IdentityServer/Thinktecture.IdentityServer3/pull/934

**Comment by brockallen** [comment]
Is there a reason to use AntiXssLibrary instead of https://msdn.microsoft.com/en-us/library/ee388364(v=vs.110).aspx? @blowdart

**Comment by blowdart** [comment]
That link 404s for me.

**Comment by brockallen** [comment]
Bizarre -- it was there yesterday evening.

**Comment by brockallen** [comment]
I think it was this one: https://msdn.microsoft.com/en-us/library/system.net.webutility.htmlencode%28v=vs.110%29.aspx

**Comment by blowdart** [comment]
Ah that. Ok, so that will use the configured encoder. By default it's the simple exclusion encoder, but you can use config to swap in the .NET 4.0+'s version of AntiXSS to get the exclusion based approach.

Your decision on if this is what you want of course.

**Comment by leastprivilege** [comment]
IOW - the one in AntiXss is more robust than the "the simple exclusion encoder" - so we rather wanna stay with the one we have.

**Comment by leastprivilege** [comment]
@thefringeninja maybe you can extract the relevant source code from anti xss?

**Comment by thefringeninja** [comment]
I believe the license for it is Ms-PL. If that's ok with everyone I don't
see why not

On Tue, Feb 17, 2015 at 6:36 PM, Dominick Baier <notifications@github.com>
wrote:

> @thefringeninja <https://github.com/thefringeninja> maybe you can extract
> the relevant source code from anti xss?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/925#issuecomment-74712332>
> .
>



-- 
Sent from my regular computer
http://twitter.com/thefringeninja
http://www.thefringeninja.com/

**Comment by leastprivilege** [comment]
Will you work on that?

**Comment by thefringeninja** [comment]
One other thing. Do you want the entire thing or just the part that has to do with html encoding? It has css encoding, url encoding and something called `LdapDistinguishedNameEncode`

**Comment by leastprivilege** [comment]
Only the ones we use. Thanks!

**Comment by leastprivilege** [comment]
OK - we internalized it. thanks Joe!
