### ISSUE TITLE
Preauthenticate_sync causes error 

### ISSUE THREAD

**Issue by v-vairam** [IdentityServer/Thinktecture.IdentityServer3#926]
PS: the earlier issue I created got closed. reopening the issue.
Received following error when connecting from client using IMplicity: "has resulted in too many redirects. Clearing your cookies for this site or allowing third-party cookies may fix the problem. If not, it is possibly a server configuration issue and not a problem with your computer."

public virtual Task PreAuthenticateAsync(SignInMessage message)
 {
 var result = new AuthenticateResult("bob", "bob");
 return Task.FromResult(result);
 //return Task.FromResult(null);
 }

this is what I have customized and actually it did not work without those additional claim types or the default InMemorUser construct. it worked without PreAuthenticateSync:
new InMemoryUser{Subject = "bob", Username = "bob", Password = "bob", 
                    Claims = new Claim[]
                    {
                        new Claim(ClaimTypes.Name, "bob"),
                        new Claim(ClaimTypes.Upn, "BobSmith@email.com"),
                        new Claim(ClaimTypes.Email, "BobSmith@email.com"),
                        new Claim(ClaimTypes.GivenName, "Bob"),
                        new Claim(ClaimTypes.Expiration, UserService.ConvertDate(DateTime.Now.AddHours(1))),
                        new Claim(ClaimTypes.Surname, "Smith"),
                    }
                }

**Comment by brockallen** [comment]
I just tried to reproduce it again and I cannot see the error/problem you describe. Enable logging in IdSvr to ensure it's working correctly. If the log shows IdSvr is working correctly, then my last guess is that your client app is simply re-triggering 401 and then you're going back to IdSvr, which issues the token, then back to the app, which re-triggers 401 -- see the loop?

**Comment by brockallen** [comment]
Any update?

**Comment by v-vairam** [comment]
I don't have it, I am not able to trace the 401 on the client. I am working on the different issue right now related to embedded identity server authentication. You may close this issue for now. Will open new one if I can provide the reproduce logic exactly.
Thanks

**Comment by brockallen** [comment]
Ok, thx for the update.
