### ISSUE TITLE
vNext build missing wwwroot folder

### ISSUE THREAD

**Issue by ryan1234** [IdentityServer/Thinktecture.IdentityServer3#928]
I had to create the `wwwroot` directory in the HostvNext project directory under the vNext branch. Is that expected? 

Also would it be ok to include a `"Microsoft.AspNet.Server.WebListener": "1.0.0-beta1"` reference in project.json as an option so we don't have to have IIS Express installed? =)

**Comment by ryan1234** [comment]
Staying away from vNext branch.

**Comment by CedricDumont** [comment]
just for info, I tried to install identityserver on vnext and wanted it to protect a web api (mvc6). I created a github project for that :  https://github.com/CedricDumont/vnext-playground/tree/master/idsrv3-vnext/idsrv3. Perhaps it can help people looking for the same. there is a readme file to test it in with fiddler

**Comment by ryan1234** [comment]
Thanks for the link! We ended up getting it to run on vNext but not without some difficulties. We had to wrap a bunch of OWIN middleware stuff and do crazy things like run on Mono 4.12. Waiting a bit for the new vNext security package to calm down. Too much churn with breaking changes.
