### ISSUE TITLE
[InvalidOperationException: IDX10803: Unable to create to obtain configuration when running idp and client site as sub sites within the same domain

### ISSUE THREAD

**Issue by v-vairam** [IdentityServer/Thinktecture.IdentityServer3#929]
running idp and client site within the same domain and app pool but different web application causes error in obtaining openid-configuration : "core/.well-known/openid-configuration"

web application: https://<mysite>
web application 2: https://<mysite>/idp/core (idp is the site within which core is "Mapped" to thinktecture sever.

web applicaiton 3: https://<mysite>/subsiteA/ is from where authentication is requested.

they all use the same app pool.
environment: running IIS8,

**Comment by johnkors** [comment]
Then you've done something wrong. This is what we do in Azure Web Sites.

**Comment by v-vairam** [comment]
does the x.509 cert has to be in store or can it be loaded from embedded resource as in the example?
can the SSL cert issuer be to the domain and x509 cert be to a different domain issuer

**Comment by v-vairam** [comment]
x509 is the test cert from sample.
I tried generated cert as well (but it is to idp.mydomainname.com not to domain.com.

**Comment by v-vairam** [comment]
when browsing to the url "https://mysite/idp/core/.well-known/openid-configuration" works and provides the JSON file
when running from the siteA "https://mysite/mysitea/" which requires authentication, the request fails.

**Comment by brockallen** [comment]
What fails? Are you having SSL trust issues?

**Comment by v-vairam** [comment]
Yes I am having SSL trust issues.
I went the route of not using SSL for now since the site is in dev:
"RequireSSL = false"

core is the identity server mapping:
"http://idp.mysite.com/core/"

The following scenario works:
http://sitea.mysite.com/ requests authentication. works correctly. (ClientId="clienta")

The following does not work:
http://idp.mysite.com/about (authorized) - using embedded authentication (ClientId="self") fails at this request: "http://idp.mysite.com/core/.well-known/openid-configuration" Error Message: IDX10803: Unable to create to obtain configuration

Both ClientID's are mapped with exact same configuration, difference is the clientid and RedirectUris
Flow = Flows.Implicit,
RequireConsent = false,
AllowRememberConsent = true


Also the following behavior was observed:
Behavior 1: Created a X509 cert enabled for Client & Server Authentication.
1.a. Loading the cert from Assembly Resource using the correct Password fails with error message "cryptographicException "system cannot find the file specified" while creating the instance of new X509Certificate2. 
1.b. However, it works when copying the cert to the bin folder and reading the file as a file resource.
Behavior 2: Using idsrvr.pfx file from sample. It works both as assembly embedded resource or as a file from the bin folder. new X509Certificate2(string.Format(@"{0}\bin\Config\idsrv3test.pfx", AppDomain.CurrentDomain.BaseDirectory), "idsrv3test");

Environment: IIS8 with LoadUserProfile Set to true for AppPool. (Also AppPool behaves the same way irrespective of user permissions on the folder with full control or Modify.)

Packages Loaded:
  <package id="Antlr" version="3.5.0.2" targetFramework="net451" />
  <package id="bootstrap" version="3.3.2" targetFramework="net451" />
  <package id="jQuery" version="2.1.3" targetFramework="net451" />
  <package id="jQuery.Validation" version="1.13.1" targetFramework="net451" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net451" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net451" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.0" targetFramework="net451" />
  <package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.3" targetFramework="net451" />
  <package id="Microsoft.Owin" version="3.0.0" targetFramework="net451" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.0" targetFramework="net451" />
  <package id="Microsoft.Owin.Security" version="3.0.0" targetFramework="net451" />
  <package id="Microsoft.Owin.Security.Cookies" version="3.0.0" targetFramework="net451" />
  <package id="Microsoft.Owin.Security.OpenIdConnect" version="3.0.0" targetFramework="net451" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net451" />
  <package id="Modernizr" version="2.8.3" targetFramework="net451" />
  <package id="Newtonsoft.Json" version="6.0.8" targetFramework="net451" />
  <package id="Owin" version="1.0" targetFramework="net451" />
  <package id="Respond" version="1.4.2" targetFramework="net451" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.0" targetFramework="net451" />
  <package id="Thinktecture.IdentityModel" version="3.6.1" targetFramework="net451" />
  <package id="Thinktecture.IdentityModel.Client" version="4.0.0" targetFramework="net451" />
  <package id="Thinktecture.IdentityModel.Core" version="1.4.0" targetFramework="net451" />
  <package id="Thinktecture.IdentityServer3" version="1.1.1" targetFramework="net451" />
  <package id="WebGrease" version="1.6.0" targetFramework="net451" />

**Comment by v-vairam** [comment]
packages:
id="Antlr" version="3.5.0.2" targetFramework="net451"
id="bootstrap" version="3.3.2" targetFramework="net451"
id="jQuery" version="2.1.3" targetFramework="net451" 
id="jQuery.Validation" version="1.13.1" targetFramework="net451" 
id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net451" 
id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net451"
id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net451"
id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net451" 
id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.0" targetFramework="net451"
id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.3" targetFramework="net451"
id="Microsoft.Owin" version="3.0.0" targetFramework="net451"
id="Microsoft.Owin.Host.SystemWeb" version="3.0.0" targetFramework="net451" 
id="Microsoft.Owin.Security" version="3.0.0" targetFramework="net451"
 id="Microsoft.Owin.Security.Cookies" version="3.0.0" targetFramework="net451" 
id="Microsoft.Owin.Security.OpenIdConnect" version="3.0.0" targetFramework="net451"
id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net451"
id="Modernizr" version="2.8.3" targetFramework="net451"
 id="Newtonsoft.Json" version="6.0.8" targetFramework="net451" 
 id="Owin" version="1.0" targetFramework="net451"
 id="Respond" version="1.4.2" targetFramework="net451" 
 id="System.IdentityModel.Tokens.Jwt" version="4.0.0" targetFramework="net451" 
id="Thinktecture.IdentityModel" version="3.6.1" targetFramework="net451" 
id="Thinktecture.IdentityModel.Client" version="4.0.0" targetFramework="net451"
id="Thinktecture.IdentityModel.Core" version="1.4.0" targetFramework="net451"
id="Thinktecture.IdentityServer3" version="1.1.1" targetFramework="net451"
 id="WebGrease" version="1.6.0" targetFramework="net451" 


web.config:
modules runAllManagedModulesForAllRequests="true"
add name="MvcCorsHttpModule"  type="Thinktecture.IdentityModel.Http.Cors.Mvc.MvcCorsHttpModule"

**Comment by brockallen** [comment]
I'm sorry but it's hard to debug your code dump. It's best for you to do some investigation and then ask very specific questions so we can help you.

My advice -- use SSL properly and get that working. Then the rest of the issues might get cleared up.

**Comment by v-vairam** [comment]
FIW: SSL was being used properly: Issue: there were IP translation issue(s) <gr>....
Thanks for your time anyways....

**Comment by khoainv** [comment]
I using sample app "MVC Authentication" EmbeddedMvc with IdentityServer3 but error.
Can you help me. very thanks

The remote name could not be resolved: 'login.ugroup.vn'
Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[WebException: The remote name could not be resolved: 'login.ugroup.vn']
   System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) +764
   System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) +78

[HttpRequestException: An error occurred while sending the request.]
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__0.MoveNext() +365

[IOException: Unable to get document from: http://login.ugroup.vn:8080/core/.well-known/openid-configuration]
   Microsoft.IdentityModel.Protocols.<GetDocumentAsync>d__0.MoveNext() +734
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.IdentityModel.Protocols.<GetAsync>d__0.MoveNext() +289
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__3.MoveNext() +915

[InvalidOperationException: IDX10803: Unable to create to obtain configuration from: 'http://login.ugroup.vn:8080/core/.well-known/openid-configuration'.]
   Microsoft.IdentityModel.Protocols.<GetConfigurationAsync>d__3.MoveNext() +1267
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.OpenIdConnect.<ApplyResponseChallengeAsync>d__c.MoveNext() +727
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.Infrastructure.<ApplyResponseCoreAsync>d__b.MoveNext() +380
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.Infrastructure.<ApplyResponseAsync>d__8.MoveNext() +494
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.Infrastructure.<TeardownAsync>d__5.MoveNext() +218
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +975
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +202
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +774
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +870
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +202
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13877064
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +193
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +96
   System.Web.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar) +116

**Comment by senj** [comment]
@v-vairam can you tell us what kind of ip translation issues?

**Comment by dpparekh** [comment]
Hello,

I am having similar issues as the person that started the thread.  The error message I am getting is:

**## IDX10803: Unable to create to obtain configuration from**

My setup is:

I have the identity server setup as a separate site in IIS using a specific IP address, with SSL using a self-signed certificate.  I have the MVC website (client) running on IISExpress using locally loading certificate provided in the MVC example.  Clients and Users are configured properly, but when the site (client) tries to connect to the Identity Server, I get the above error.

There seems to be SSL trust issues, but I am not sure how to resolve it.

Thanks.

**Comment by mdvd02** [comment]
How did you resolve the IP translation issue(s)?

**Comment by DoubleExposure** [comment]
This is a recurring issue for most of us. Can you guys please share your resolution to your problem? Thanks

**Comment by smcl** [comment]
I'm seeing this periodically too, it is nigh-on impossible to debug since it happens once in a blue moon. I am tempted to try to wrap these calls in a retry loop with a half-second delay or so. Otherwise I'm kinda stumped.
