### ISSUE TITLE
Nonce Validation Error on back button after initial login

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/Thinktecture.IdentityServer3#931]
Hi,

I get the below error message, when I perform the following actions:

1. Clear all cookies
2. Go to RP
3. Go to secured page in RP (Redirects to idsvr)
4. Login to Idsvr (Redirects to RP)
 5. Hit the back button in the browser.

```
IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null. A nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'.
```

I am thinking this is by design to avoid replay attacks. Is this correct?
If so, am I best to catch this exception in a CustomHandleErrorAttribute and redirect to an error page that presents a more user friendly message?

**Comment by johnkors** [comment]
Yeah, nonce = no more than once.

**Comment by parkinsona** [comment]
Thanks @johnkors .

I added the following to capture and return the user to a custom error page.

``` c#
    protected void Application_Error(object sender, EventArgs e)
        {
            //Handle nonce exception
            var ex = Server.GetLastError();
            if (ex.GetType() == typeof(OpenIdConnectProtocolInvalidNonceException) & HttpContext.Current.IsCustomErrorEnabled)
            {
                Server.ClearError();
                Response.Redirect("~/Error/NonceException");
            }

        }
```

**Comment by shyambhiogade** [comment]
i have fixed this problem by following the solution given at http://stackoverflow.com/questions/29502788/enabling-ssl-in-asp-net-mvc-5-app-results-in-openidconnectprotocolvalidator-issu

```
AuthenticationFailed = (context) =>
                    {
                        if (context.Exception.Message.StartsWith("OICE_20004") || context.Exception.Message.Contains("IDX10311"))
                        {
                            context.SkipToNextMiddleware();
                            return Task.FromResult(0);
                        }
                        return Task.FromResult(0);
                    }
```

**Comment by be4i** [comment]
Hey, what about after validation remembering the nonce cookie for 30 more mins ? like this

`public class OpenIdConnectAuthenticationPatchedHandler : OpenIdConnectAuthenticationHandler
    {
        private readonly ILogger _logger;

        public OpenIdConnectAuthenticationPatchedHandler(ILogger logger) : base(logger)
        {
            _logger = logger;
        }

        protected override string RetrieveNonce(OpenIdConnectMessage message)
        {
            if (message == null)
            {
                return null;
            }

            string nonceKey = GetNonceKey(message.Nonce);
            if (nonceKey == null)
            {
                return null;
            }

            string nonceCookie = Request.Cookies[nonceKey];
            if (nonceCookie != null)
            {
                var cookieOptions = new CookieOptions
                {
                    HttpOnly = true,
                    Secure = Request.IsSecure,
                    Expires = DateTime.Now.AddMinutes(30)
                };

                Response.Cookies.Append(nonceKey, nonceCookie, cookieOptions);
            }

            if (string.IsNullOrWhiteSpace(nonceCookie))
            {
                _logger.WriteWarning("The nonce cookie was not found.");
                return null;
            }

            string nonce = null;
            var nonceProperties = Options.StateDataFormat.Unprotect(Encoding.UTF8.GetString(Convert.FromBase64String(nonceCookie)));
            if (nonceProperties != null)
            {
                nonceProperties.Dictionary.TryGetValue("N", out nonce);
            }
            else
            {
                _logger.WriteWarning("Failed to un-protect the nonce cookie.");
            }

            return nonce;
        }
    }`
