### ISSUE TITLE
Local/External Authorization without View.

### ISSUE THREAD

**Issue by pavlo-p** [IdentityServer/Thinktecture.IdentityServer3#933]
Hi, I have spa application on AngularJS and I'm trying to add IdSvr3 to authorize users through local identity provider and externals as well. As far as I understood the best approach for JS client is to have implicit flow and after login button click user should be redirected to IdSvr page. But in this case I have to make redirect on some other url(which is not very user friendly) and cusomize views (but I already have all views implemented on my own application). I started to work with "password" flow and using Token endpoint to get tokens and looks like what I really want. Is there any way to implement external Authentication without using Authorize Endpoint and views customization? And could you please advise me which flow I should better use for my situation? Thanks in advance.

**Comment by brockallen** [comment]
You could always do a pop-up windows for the login -- check the OAuthJS sample.

And yes, you can use password flow if you want, but you lose some features (like SSO).

**Comment by pavlo-p** [comment]
The main thing that I don't understand is why we need to redirect user on other endpoint instead of just use some api to authenticate him?
Why we can't have SSO in case of password flow?

**Comment by pavlo-p** [comment]
And could you please, provide some guide or link of how to implement external login with password flow?

**Comment by brockallen** [comment]
Because of trust -- would you enter your twitter password into a non-twitter app? Read the spec (or some of our docs) for more details. And if you use the password flow you have to enter your credentials into each app you use -- that's not SSO.

We have many samples to get you started -- please try those first.

**Comment by pavlo-p** [comment]
Honestly, I've read all documentation and watched all samples and videos on IdSvr3, IdMgr, MR twice at least and some articles even more. I've also read almost everything in your and Dominic's blogs. As well as OpenID connect and OAuth2 spec. I debug almost each component and I understood each sample separately. But unfortunately I still can't get the whole picture of how can I embed IdSvr to my application. I'm just stuck with it.

**Comment by pavlo-p** [comment]
Could you tell me, please, is it possible somehow to add support of External Identity Providers if I want to use "Password" flow?

**Comment by brockallen** [comment]
Check the docs for the token endpoint: pass in a tenant param, and handle it in the user service.

**Comment by pavlo-p** [comment]
I've read docs for token endpoint. There is nothing there about it.

**Comment by leastprivilege** [comment]
Check the acr_values - these values get passed through to your user service - from there you can contact whatever external provider that you want (that also supports programmatic authentication).

**Comment by pavlo-p** [comment]
Thanks for response. But I still don't get it. If I send acr_values=idp:facebook for example anyway I'll step into AuthenticateLocalAsync but how can I perform external authentication here?
Thanks in advance.

**Comment by leastprivilege** [comment]
by writing code against your external provider of course.

**Comment by leastprivilege** [comment]
ah - and facebook, google etc don't allow that - they only support authentication via their login page. Kind of what Brock already told you at the beginning of the thread.

**Comment by pavlo-p** [comment]
So as far as I understood there is only one way to work with external IdP using IdSvr:
- customize views for authorization endpoint
- use code, implicit or hybrid flow
- implement UserService to properly check and store external data?
Thanks in advance.

**Comment by leastprivilege** [comment]
As stated before - it depends on the external providers - some allow programmatic access - e.g. ADFS - others require the use of the login page - e.g. Google, Facebook etc

In IdSrv you can do both.

**Comment by pavlo-p** [comment]
Thank you, Dominic, but unfortunately I still didn't get an answer (probably this is because I'm new in security at all). 
I'll try to rephrase my question and I'll very appreciate if you will have a time to answer on it: 
In case if I want to have all views on my site. So user goes to login page and see something registration form on left side and sign in form (with external providers buttons) on the right side. 
I don't want to have SSO at this point and want to use just "password" flow. 
To authenticate user locally I will send params(grant_type, username, password, client_id(in header), scopes list. After that I'll get a access_token which I can include in header of request to API and I'll be able to reach it. So the questions are:
- Can I get refresh_token in response as well?
- Does it makes sense to client_secret if I'll have to store on client side anyway which is not protected anyway?
- How can I do the same but if I want to authenticate with Facebook, Google, etc?
- Is it possible to do the same thing but with Hybrid flow without implementing ViewService?(I just want to have a possibility to store all front stuff in one place).

Thanks in advance.

**Comment by leastprivilege** [comment]
* Can I get refresh_token in response as well?
yes
*Does it makes sense to client_secret if I'll have to store on client side anyway which is not protected anyway?
client_secret is mandatory
* How can I do the same but if I want to authenticate with Facebook, Google, etc?
you need to redirect to google etc - they don't support password flow (you can pass the idp: in the acr_values to the authorization endoint) if you want to trigger that from your own sign in form
* Is it possible to do the same thing but with Hybrid flow without implementing ViewService?(I just want to have a possibility to store all front stuff in one place).
Hybrid flow is a redirect flow. That does not mean that you need to implement IViewService - there are other means of customizing views - check the docs.

**Comment by pavlo-p** [comment]
Thanks for response, Dominic. 
I've tried it but still have a problem. On the click to external IdP button I just redirect user to http://localhost:2/connect/authorize?client_id=roclient&scope=profile openid&response_type=code id_token token&acr_values=idp:Facebook&redirect_uri=http://localhost:1/
After that I see facebook login page and after authentication in facebook I have infinite loop because for some reason facebook redirects me to the same url that requested facebook but not to "http://localhost:1/" as I wrote in params. I debug this and found out that SignInMessage that created just doesn't contain the ReturnUrl value that I sent and instead of it it creates whole initial url and assign it to RedirectUrl. It happens at RedirectToLogin of AuthorizeEndpointController. Please, correct me if I do something wrong. 
Thanks in advance.

**Comment by leastprivilege** [comment]
I never used facebook auth - but the MVC walkthrough in the docs has step by step instructions for Google. Maybe try that first.

I will close this now.

**Comment by pavlo-p** [comment]
It is not the same. All examples are using views from IdentityServer but I've tried customize them and it is not possible for rich UI applications. Because a bunch of css and js should be loaded and it creates dependency on UI.
