### ISSUE TITLE
OpenId Connect With OAuth2.0

### ISSUE THREAD

**Issue by Sriram143** [IdentityServer/Thinktecture.IdentityServer3#936]
Hi,
I have an SPA. And I am Trying To Provide Single Sign On (ActiveDirectory/UserName Password From Oracle Database,Other Login)
What is The Best Way to Write The Application Using Thinktecture Identity Server v3 

I Have an Web Api Called CustomApi ( Web Api 2.0)
I Have an SPA Called CustomClient ( AngularJs App With MVC 5.2)
I HAve an STS Called Custom STS (Thinktecture Identity Server v3)

When The client Is trying to Access The CustomApi The User Need to Authenticate Using AD/UP fro Oracle/ Other Mechanism) when authentication Successful I want to generate Claims and generate Access token and access The CustomApi

How do i Handle The Single Sign On In Thinktecture?
Do i need to Write Custom Identity Providers/ Explain The Possible Ways of Configuration

**Comment by brockallen** [comment]
I'd suggest you start by reading the docs and doing the walk-thrus.
