### ISSUE TITLE
Difference Between These Two Projects

### ISSUE THREAD

**Issue by Sriram143** [IdentityServer/Thinktecture.IdentityServer3#938]
Thinktecture Identity Server v3 and Thinktecture Authorization Server?

I am trying to Write Provider. Which One I have to Use in Middleware Related to http://identityserver.github.io/Documentation/docs/configuration/identityProviders.html

**Comment by brockallen** [comment]
http://leastprivilege.com/2014/12/09/the-future-of-authorizationserver/
