### ISSUE TITLE
Infinite loop with local login disabled and only 1 external idp

### ISSUE THREAD

**Issue by michaelbeckersgit** [IdentityServer/Thinktecture.IdentityServer3#939]
Hi guys,

I have found a potential bug when identity server is configured with 'locallogin' disabled in the authentication options and only 1 external identity provider is configured.  You end up in an infinite loop and in the logs you find the exception:

"Thinktecture.IdentityServer.Core.ResponseHandling.AuthorizeInteractionResponseGenerator: User is logged in with local idp, but local logins not enabled."

Altough I'm using an external idp, this message looks odd.

Any feedback would be appreciated,
Regards,

**Comment by brockallen** [comment]
Ok, I can look into it.

**Comment by brockallen** [comment]
Can you provide detailed steps to reproduce? I just tried with the samples and I can't trigger what you're seeing.

**Comment by michaelbeckersgit** [comment]
You're right, that parameter was not set and defaulted to "idsrv", thanks a bunch for the quick response.

Regards,
