### ISSUE TITLE
Deploying identityserver to the GAC

### ISSUE THREAD

**Issue by michaelbeckersgit** [IdentityServer/Thinktecture.IdentityServer3#940]
Hi,

We would like to deploy the identity server assembly to the GAC, but the source is not strong named.
What is your opinion on this?

Remark: When we take in the code and strong name and compile it, we have a runtime error on the internalsvisible to the test assembly.  This can be changed of course, but I prefer to avoid it if possible.

Regards,

**Comment by leastprivilege** [comment]
We don't support the GAC and strong naming.

Why would you want to do that. You know that both technologies are deprecated.

**Comment by michaelbeckersgit** [comment]
Because all our assemblies are in the GAC, we have multiple web projects that are part of our enterprise product and use the same shared assemblies across. This makes the application more maintainable, but that is my honest opinion.

Deprecated, since when?

**Comment by leastprivilege** [comment]
The next version of .NET aka the CoreCLR and ASP.NET 5 will not have those concepts anymore.

We will not provide a strong named version of identity server - there are many discussions around the problems and merits of strong naming nuget packages. Just google for it.

**Comment by michaelbeckersgit** [comment]
Ok clear, thanks for the insight.
