### ISSUE TITLE
How to get the sub values from claims in the client side  

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#941]
how to assign sub value to the variable.

![image](https://cloud.githubusercontent.com/assets/10266752/6244343/55589290-b778-11e4-8c92-34dcc2c76407.png)

**Comment by brockallen** [comment]
This question is unrelated to IdentityServer. Please check the Microsoft forums of MSDN documentation for general .NET questions.
