### ISSUE TITLE
401 not authorized with No redirecting to login page after Publishing on IIS

### ISSUE THREAD

**Issue by mohammadhammod** [IdentityServer/Thinktecture.IdentityServer3#943]
Hi,
I've added thinktecture3 to an existing ASP.Net MVC application,  it works great with entity framework and oracle, everything is working perfect locally, when I add [Authorize] before a controller it redirects me to the login page, after successful login it redirects the user again to the original page, now the problem is this is not happening after publishing the site to IIS, when you try to access a page with  [Authorize] attribute it shows the 401 error page:
"HTTP Error 401.0 - Unauthorized
You do not have permission to view this directory or page."
with no redirecting to the login page at all , although I can navigate to the Authority url and login from there, and also I can open the pages with no Authorize attribute without any problems.
am I missing some config related to IIS ? I've checked the certificate,the client, the authority and the redirectUri, I think they are configured correctly.

Configuration Method : 
             LogProvider.SetCurrentLogProvider(new DiagnosticsTraceLogProvider());
            var idSvrFactory = Factory.Configure("IdSvr3Config");
            idSvrFactory.ConfigureCustomUserService("IdSvr3Config");

            appBuilder.Map("/identity", idsrvApp => idsrvApp.UseIdentityServer(new IdentityServerOptions
            {
                SiteName = "Embedded IdentityServer",
                SigningCertificate = LoadCertificate(),
                Factory = idSvrFactory
            }));

            appBuilder.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            appBuilder.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = "https://sims.tss.local/identity",
                ClientId = "mvc",
                RedirectUri = "https://sims.tss.local/",
                ResponseType = "id_token",

                SignInAsAuthenticationType = "Cookies"
            });

**Comment by brockallen** [comment]
The 401 is in IdSvr or in the MVC client app?

**Comment by mohammadhammod** [comment]
it is from the MVC application

**Comment by brockallen** [comment]
Well... sounds like some environmental issue. Normally a 401 triggers the redirect to login, but if your 401 is just showing the unauthorized page that sounds more like the OIDC middleware isn't triggering. So more of a MVC/Katana issue than an IdentityServer issue. Perhaps check in Jabbr -- lots of folks in there who can help with Katana.

**Comment by mohammadhammod** [comment]
it seems like there was an SSL certificate validation issue in the server (although I followed the exact steps in the documentation), this was causing an exception in the mvc application, so it ended up with a 401 unauthorized error, I don't know why it was 401 and not another error code. Anyway skipping the certificate validation with this code was enough to fix the problem "temporarily" :

            ServicePointManager.ServerCertificateValidationCallback =
                delegate(object s, X509Certificate certificate,
                    X509Chain chain, SslPolicyErrors sslPolicyErrors)
                { return true; };

of course this is very bad when deploying the site, it is just a hack for testing.
