### ISSUE TITLE
How to divide IdenityServer3 into 2 instances(one for Authentication and another for Authorization)

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/Thinktecture.IdentityServer3#944]
Hello,

I am new to this forum and to security and hope to get an answer as to the question above.

We intend to use an external WS federation Service for Authentifcation which is not yet available. Also my company wants to use an extra Authorisation Service for all our REST Services.So before having access to the production WS federation service I intend the following as interim solution for development phase:

-SelfHost (InMem with WS-Fed) (from IdentityServer3 Samples) as Ws federation surrogates for the later real WsFed.Service
-SelfHost (Minimal) (from IdentityServer3 Samples) as interim solution for a later full fleged company owned Authorization server.

Eventually the interim solution is to be replaced by the final solution as the following:
host the full thinktecture identity SErver 3 with Authorization database configured to use the real production WS Federation Service.

How can I setup the SelfHost (Minimal) Solution from the ID3 samples to use a SelfHost (InMem with WS-Fed) instance from the ID3 samples for Authentification?

Thank you very much for any hint!

David

**Comment by brockallen** [comment]
Given that IdentityServer is just middleware, you can load and configure as many instances as you want in the same (or different) hosting applications. You'd probably want to differentiate them by different paths in the URL (assuming they're on the same host).

**Comment by brockallen** [comment]
All set?

**Comment by davidmrichter** [comment]
Sorry for bringing this up again. I was busy to set up Scopes Roles Resources and so on, to get a better understanding on what is actually to devide.

After having that implemented/extented alltogether in SelfHost (Minimal) Sample I have second thoughts on dividing IdenityServer3 into 2 instances(one for Authentication and another for Authorization).

If one divides as described in my first post:
-what is then the remaining functionality in the second part(-SelfHost (Minimal) (from IdentityServer3 Samples) as interim solution for a later full fleged company owned Authorization server)

Based on my current knowledge I would postulate: nothing is remaining 
I think even that my question in the first place doesnot make sense at all!

But Allen did not think so and answered my question.
Can someone hint me towards the point I am quite certainly missing?`

Thank you very much
