### ISSUE TITLE
Link users from several providers to a certain account

### ISSUE THREAD

**Issue by vidarkongsli** [IdentityServer/Thinktecture.IdentityServer3#945]
Given that
 * I use MembershipReboot
 * I have a local account in the database with an associated claim representing a known identifier, e.g. SSN

When a user authenticates for the first time from an external identity provider, how can I look up potential existing accounts for linking, based on the claim value? (I only have usrService.GetByID, userService.GetByUsername, userService.GetByEmail, etc. available, none being a seemingly good match)

**Comment by brockallen** [comment]
There are virtuals you can override from the `MembershipRebootUserService` base class to customize how the external account is mapped to the local one. Unfortunately no docs on these, so you'll just have to read the source (it's not that complicated tho).

https://github.com/IdentityServer/Thinktecture.IdentityServer3.MembershipReboot/blob/master/source/MembershipRebootUserService/MembershipRebootUserService.cs#L173

**Comment by vidarkongsli** [comment]
Thanks for the reply. I have fiddled around with inheriting from MembershipRebootUserService, but I can't figure out how to query the userAccountService for accounts by claim or any other parameter on the   account than id, username or email.

**Comment by brockallen** [comment]
MR has a `IUserAccountQuery<TAccount>` which could be used to query your DB the way you want. It's a property on the `UserAccountService<TAccount>`. You might need to add indexes to the DB based upon how you use this.

**Comment by brockallen** [comment]
Did that work for you?

**Comment by vidarkongsli** [comment]
Yes, once I figured out how to use the API it worked great. Here's the query code I ended up with:
```c-sharp
var accountResult = userAccountService.Query.Query(
   accountList => accountList.Where(
      account => account.ClaimCollection.Any(cl => cl.Type == "uid" && cl.Value == "thevalue")))
          .SingleOrDefault();
if (accountResult != null) { 
            return await ProcessExistingExternalAccountAsync(accountResult.ID, externalUser.Provider, externalUser.ProviderId, externalUser.Claims);
}
```
