### ISSUE TITLE
Claim Information not being passed

### ISSUE THREAD

**Issue by stroebele** [IdentityServer/Thinktecture.IdentityServer3#948]
I have IdentityServer with Membership Reboot and IdentityManager running on a remote server, I've used the Admin UI of IdentityManager to setup a user, and add roles & claims to said user.

I'm developing a WebApi/SPA project that will use the remote server for Auth. Using fiddler I can request a token from the IdentityManagner on the remote box and use this token to against the local WebApi where Authorization is required. If the token is valid the WebApi processes like normal, if the token is bogus I get a 401. Works great.

The problem is when I want additional information about the user none of the claims or identity information is coming across in the princple  on the WebApi. I'm not sure if the problem is at the IdentityServer side, The WebApi side, or if I'm not doing something correctly when getting my token.

Any suggestions on where to look, or tips on troubleshooting the issue would be greatly appreciated.

**Comment by brockallen** [comment]
Did you request scopes with the claims you're expecting? IOW, is the problem that the claims are not in the token, or that your Web API code is not seeing what's in the token?

**Comment by stroebele** [comment]
I believe I have the scopes setup correctly and I'm requesting the proper scope. The scope on the IdentityServer is as follows

 var scopes = new List<Scope>
            {
                new Scope
                {
                    Enabled = true,
                    Name = "publicApi",
                    Description = "Access to our public API",
                    Type = ScopeType.Resource
                }
            };
            scopes.AddRange(StandardScopes.All);


The call I'm doing to get the token from fiddler has the following body
grant_type=password&username=joshua&password=joshua&scope=profile publicApi 

The configuration on the WebApi is as follows 
           app.UseIdentityServerBearerTokenAuthentication(
            new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://dev-vmws03.onlinelogistics.com:44305/identity",
                RequiredScopes = new[] { "publicApi", "profile" }
            });

Where I'm missing the claim is in the principle in the webApi

Is there a way to see what claim information is available in the token?

**Comment by brockallen** [comment]
What claims are you indicating should go into that scope? I don't see any. I think that's why you don't see any claims in your API.

**Comment by stroebele** [comment]
BINGO!!

I didn't realize we needed put the claims in the Scope definition. Incase anyone else stumbles upon this I changed my scope to the following

           var scopes = new List<Scope>
            {
                new Scope
                {
                    Enabled = true,
                    Name = "publicApi",
                    Description = "Access to our public API",
                    Type = ScopeType.Resource,
                    IncludeAllClaimsForUser = true, //I'll filter this down later
                }
            };
            scopes.AddRange(StandardScopes.All);
 
            return scopes;

@brockallen Thanks for the quick followup.
