### ISSUE TITLE
using "post_logout_redirect_uri"

### ISSUE THREAD

**Issue by iltera** [IdentityServer/Thinktecture.IdentityServer3#949]
Hi,

I am trying to bypass the `Logged Out` page with an auto-redirect to the application homepage using `post_logout_redirect_uri` parameter in the url.

I have this code in startup

```C#
RedirectToIdentityProvider = async n =>
{
     if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
     {
           var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
           var postLogoutRedirectUri = "https://domain.com/";

           if (idTokenHint != null)
           {
                 n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                 n.ProtocolMessage.PostLogoutRedirectUri = postLogoutRedirectUri;
            }
      }
}
```
I have `https://domain.com` in both the `ClientPostLogoutRedirectUris` and `ClientRedirectUris` for that client. All I see is the link for that Url at the "Logged Out" screen. That one I already had without defining the `postLogoutRedirectUri` in startup.

What else should I do in order to get an automatic redirect after the logout?

Thanks!

**Comment by brockallen** [comment]
There is no auto-redirect feature.

**Comment by jlegan** [comment]
Brock,

Couldn't this behavior be achieved with a Custom View Service and a simple javascript redirect?

Jim

**Comment by brockallen** [comment]
It could. But there are reasons we don't auto-redirect -- search the closed issues for the various discussions on the topic.

**Comment by jlegan** [comment]
Will do, thanks. I was planning on adding this functionality but after thinking about it I could see why it could be problematic.

**Comment by zsims** [comment]
We just ran into this, should this be mentioned in the docs? https://identityserver.github.io/Documentation/docs/endpoints/endSession.html

**Comment by iltera** [comment]
I just wanted to mention that, too.
The docs say

>post_logout_redirect_uri
>A URI that IdentityServer will redirect to after logout. The URI must be in the list of allowed post logout URIs for the client.

>/connect/endsession?id_token_hint=...&post_logout_redirect_uri=https://myapp.com

That is kind of confusing.

Then, what does `post_logout_redirect_uri` do exactly if we can already achieve getting a link to application with `id_token_hint`, and cannot redirect automatically?

**Comment by leastprivilege** [comment]
Docs updated - see also here

http://www.aaron-powell.com/posts/2015-01-11-auto-redirect-when-logging-out.html

**Comment by iltera** [comment]
I just had a look at the updated docs and find it still confusing because using `post_logout_redirect_uri` doesn't really create a redirect and conflicts with the explanation `A URI that IdentityServer can redirect to after logout (by default a link is displayed)`.

I have an idea on that. Why don't we secure the logout action on idsrv by providing the `id_token_hint` in the first place? What I mean is, I can logout from the application by just using `{idsrv}/connect/endsession`. That means, it could also be called from a malicious page in an iframe. I think in order to be logged out, we should provide the idsrv who we are first, by providing the `id_token_hint` when we call `endsession endpoint`. When we are who we say we are, idsrv can handle the redirect or provide the application uri in the logged out page as it's doing now.

I am not a security expert, but I think that approach could be provided "as an option" in order to prevent malicious logout requests and adds another security level for the application.

What do you think about that?

**Comment by leastprivilege** [comment]
There's a spec. And we implemented it.
