### ISSUE TITLE
Documentation suggestion for /advanced/customServices.html

### ISSUE THREAD

**Issue by ryan1234** [IdentityServer/Thinktecture.IdentityServer3#951]
On http://identityserver.github.io/Documentation/docs/advanced/customServices.html there is a small code snippet that shows how to wire up a custom implementation of IUserService.

```csharp
var factory = new IdentityServerServiceFactory();
factory.UserService = new Registration<MyCustomUserService>();
```
When I tried to connect my implementation this way, I got the error:

```
Cannot implicitly convert type 'Thinktecture.IdentityServer.Core.Configuration.Registration<MyCustomUserService>' to 'Thinktecture.IdentityServer.Core.Configuration.Registration<Thinktecture.IdentityServer.Core.Services.IUserService>
```
I'm sure I'm just missing something, but I found this method (https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/blob/master/source/EntityFramework/SelfHost/Config/Factory.cs#L31) from the samples to work better:

```csharp
var userService = new MyCustomUserService();
factory.UserService = new Registration<IUserService>(resolver => userService);
```
I think it would help to update the customServices.html page with this additional example of how to set the UserService.

**Comment by brockallen** [comment]
Docs are fixed. Thx.

**Comment by brockallen** [comment]
I also cleaned up the EF sample code (on dev branch). It's cleaner now -- the sample you linked above is sort of incorrect given some updates we made to the DI system. Thanks again for bringing it to our attention.
