### ISSUE TITLE
Identity server3: HTTP activity shows password in clear text

### ISSUE THREAD

**Issue by sandeepgaikwad** [IdentityServer/Thinktecture.IdentityServer3#953]
I have configured Identity server3 as a separate MVC app and using it to authenticate and authorize different MVC applications.
All my controllers which have [Authorize] attribute are first redirected to Identity server login page if not authorized, where is gets authorized and returns back.
But when I observe the HTTP activity in fiddler, in one of the requests, I can see my password in clear text.
Isn't that a security threat? 
Or am I missing something in my configurations?
Let me know if more information is required from my end

**Comment by johnkors** [comment]
Use SSL.
