### ISSUE TITLE
Provide renewal of the Autofac IComponentContext in IDependencyResolver to allow runtime resolving of dependencies using factory func registrations

### ISSUE THREAD

**Issue by ambvdijk** [IdentityServer/Thinktecture.IdentityServer3#955]
In my implementation of IUserService.AuthenticateExternalAsync I have different strategies for authenticating the user dependent on the External Provider used to authenticate with. To avoid having to build a big if-tree I created an Interface:

```C#
public interface IExternalAuthenticator
{
    Task<AuthenticateResult> AuthenticateAsync(
        ExternalIdentity identity, SignInMessage message);
}
```

I register multiple (named) instances of this interface in the IdentityServer DI System and a factory Func which I inject into my custom UserService.

```C#
factory.Register(new Registration<IExternalAuthenticator, AuthenticatorA>("ProviderA"));
factory.Register(new Registration<IExternalAuthenticator, AuthenticatorB>("ProviderB"));
factory.Register(new Registration<IExternalAuthenticator, AuthenticatorC>("ProviderC"));

factory.Register
(
    new Registration<Func<ExternalIdentity, IExternalAuthenticator>>
        (
            resolver => id => resolver.Resolve<IExternalAuthenticator>(id.Provider)
        )
);
````

Running this code ends in an exception comming from AutoFac:

System.ObjectDisposedException: This resolve operation has already ended. When registering components using lambdas, the IComponentContext 'c' parameter to the lambda cannot be stored. Instead, either resolve IComponentContext again from 'c', or resolve a Func<> based factory to create subsequent components from.

To resolve this exception I need to request a renewed AutoFac IComponentContext as follows:

```C#
factory.Register
(
    new Registration<Func<ExternalIdentity, IExternalAuthenticator>>
        (
            resolver => 
            {
                var context = resolver.Resolve<IComponentContext>();
                return id => context.ResolveNamed<ExternalAuthenticator>(id.Provider);
            }
        )
);
````

But this isn't possible because IdentityServer's Autofac and with it IComponentContext are ILMerged.

Would it be possible to extend the [IDependencyResolver](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Services/IDependencyResolver.cs) with a method to access a renewed context?

For example:

```C#
internal class AutofacDependencyResolver : IDependencyResolver
{
    readonly IComponentContext ctx;
    public AutofacDependencyResolver(IComponentContext ctx)
    {
        this.ctx = ctx;
    }
    
    public T Resolve<T>(string name)
    {
        if (name != null)
        {
            return ctx.ResolveNamed<T>(name);
        }

        return ctx.Resolve<T>();
    }

    /// <summary>
    /// Provides access to a renewed runtime context
    /// </summary>
    public IDependencyResolver GetContext()
    {
        return new AutofacDependencyResolver(ctx.Resolve<IComponentContext>());
    }
}
```

**Comment by ambvdijk** [comment]
Should I create a pull request for this to help out?

**Comment by brockallen** [comment]
The short of it is that trying to resolve a named dependency doesn't work?

**Comment by ambvdijk** [comment]
No, it has to do with the lifetime of the context using delegate factories in AutoFac.
Here is a small console app to show the problem:

```C#
using System;
using System.Diagnostics;
using System.Runtime.Remoting.Contexts;
using Autofac;

namespace FunkyAutoFac
{
    class Program
    {
        private static void Main(string[] args)
        {
            var builder = new ContainerBuilder();

            builder.RegisterType<StrategyB>().Named<IStrategy>("A");
            builder.RegisterType<StrategyB>().Named<IStrategy>("B");

            builder.Register<Func<string, IStrategy>>(ctx => key => ctx.ResolveNamed<IStrategy>(key));

            var container = builder.Build();

            var factory = container.Resolve<Func<string, IStrategy>>();

            factory("A").Do();
        }
    }

    public interface IStrategy
    {
        void Do();
    }

    public class StrategyA : IStrategy
    {
        public void Do()
        {
            Console.WriteLine("Do A");
        }
    }

    public class StrategyB : IStrategy
    {
        public void Do()
        {
            Console.WriteLine("Do B");
        }
    }
}
```

**Comment by brockallen** [comment]
I guess my real question is why isn't the current implementation broken (since we use named registrations internally). Is it only a problem when the named registration is a delegate?

**Comment by brockallen** [comment]
Ahhh, ok, I see now... you're registering a Func that's executed later than when dependency resolution is happening. So yes, of course, you can't capture the resolver.

**Comment by ambvdijk** [comment]
Yes, exactly! ;-)

Some more info here on [Stackoverflow](http://stackoverflow.com/questions/20583339/autofac-and-func-factories).

**Comment by brockallen** [comment]
So then... why should we allow this? *grin*

**Comment by ambvdijk** [comment]
To allow factory patterns to be used when resolving dependenies. I don't need access to AutoFac or to it's internals. I just need a method to create a new scoped context wrapped in a new IDependencyResolver

Adding this method to the AutofacDependencyResolver whould solve this issue:

internal class AutofacDependencyResolver : IDependencyResolver
{
    //Exisiting code...

    /// <summary>
    /// Provides access to a renewed runtime context
    /// </summary>
    public IDependencyResolver GetContext()
    {
        return new AutofacDependencyResolver(ctx.Resolve<IComponentContext>());
    }
}

**Comment by brockallen** [comment]
What then cleans up the dependencies that are resolved in the new context?

**Comment by ambvdijk** [comment]
The components resolved in this scope still follow the lifetime rules defined during bootstrapping.

**Comment by ambvdijk** [comment]
So if I define StrategyB to be a Singleton using SingleInstance the delegate factory would return the same instance every time it's executed.

**Comment by brockallen** [comment]
Oh right -- since the child context comes from the http constrained context, then i guess AutoFac will dispose at the end of that request.

Ok, I'm convinced -- this is something we can add.

**Comment by brockallen** [comment]
If you want to get started with a PR, please do (sign the CLA too if you haven't already, please). Thx

**Comment by brockallen** [comment]
BTW, it's too bad this issue surfaces at all... IOW, I'd like AutoFac to allow this via the normal context if said context has not yet been disposed. Perhaps there's something subtle I am unaware of...

**Comment by ambvdijk** [comment]
You only need a new context if you are resolving dependencies in your delegate. In this case for example it not necessary:

```
builder.Register<Func<string, IStrategy>>(ctx => key => new StrategyB());
```

**Comment by brockallen** [comment]
right, but does it hurt to always have one? if we did it that way, then our dependency resolver API doesn't have to change

**Comment by ambvdijk** [comment]
Hmm. Not sure...

**Comment by brockallen** [comment]
Mind researching that for me? :)

**Comment by ambvdijk** [comment]
Sure

**Comment by ambvdijk** [comment]
Changing the AutofacDependencyResolver constructor from:
```C#
public AutofacDependencyResolver(IComponentContext ctx)
{
    this.ctx = ctx;
}
```
to
```C#
public AutofacDependencyResolver(IComponentContext ctx)
{
    this.ctx = ctx.Resolve<IComponentContext>();
}
```

Does fix the problem, but i'm not sure of the side effects.

**Comment by brockallen** [comment]
That's good news and I like it better than adding a new API. I still want to know what the cost/tradeoff is. Can you dig into that a bit more? Thx.

**Comment by ambvdijk** [comment]
I will try to figure out what resolving the IComponentContext really does in regard to Lifetime scopes and disposables

**Comment by ambvdijk** [comment]
I think we're safe. It has to do with the concurrency features of autofac. See AutoFac docs about [concurrency](http://autofac.readthedocs.org/en/latest/advanced/concurrency.html)

Let me know what you think!

**Comment by brockallen** [comment]
Yea, it seems ok... but I worry about the wording around "thread specific". Is the non-temporary context thread bound? Can it be used across multiple threads (as would be common with so much async/await code in IdSvr).

**Comment by ambvdijk** [comment]
I will try to write a multi threaded unit test to prove it doesn't break. Maybe even do some measurements to see if performance isn't compromised.

**Comment by alexmg** [comment]
The registration code in AutofacConfig is capturing the temporary component context in the registration and then making that available downstream.

```csharp
var reg = builder.Register(ctx => registration.Factory(new AutofacDependencyResolver(ctx)));
```

This should actually resolve the component context and pass that through instead.

```csharp
var reg = builder.Register(ctx => registration.Factory(new AutofacDependencyResolver(ctx.Resolve<IComponentContext>())));
```

With that in place the original registration in the opening post would have worked.

The context provided will be the lifetime scope that the component lives in. For example, when a service registered with InstancePerLifetimeScope is resolved from a child lifetime scope, it would have that child lifetime scope provided as the context.

**Comment by ambvdijk** [comment]
Hi @alexmg. Thats also what we figured out. Maybe its a good idea to do the change in the autofacConfig instead of the AutofacDependencyResolver constructor. @brockallen what do you think.

But the real question is: What is the effect of resolving a new IComponentContext even if you don't need it?

**Comment by s093294** [comment]
To much stuff here about AutoFac that I dont know much about, but the following statement caught my attention.
```
You only need a new context if you are resolving dependencies in your delegate. In this case for example it's not necessary:

builder.Register<Func<string, IStrategy>>(ctx => key => new StrategyB());
or

builder.Register<IStrategy>(ctx => new StrategyB(ctx.Resolve<SomeDependency>())); 
```

I didnt fully understand if the above example should be broken? Because I have been doing similar for a long time now and its working fine for me. So if I misunderstood the issue, sorry for the reply.

```
            var serviceFactory = new IdentityServerServiceFactory();
            serviceFactory.UserService = new Configuration.Registration<IUserService>(IdentityManagerServiceFactory);
            
and

        public static IUserService IdentityManagerServiceFactory(IDependencyResolver resolver)
        {
            var ctx = resolver.Resolve<OwinEnvironmentService>();
            return new AscendAspNetIdentityUserService(ctx.Environment.ResolveDependency<AscendUserManager>());
        }
```

Please note that: `ctx.Environment.ResolveDependency<AscendUserManager>()` is the our own extensionmethods using Unity instead.

**Comment by ambvdijk** [comment]
Hi @s093294, there is a difference. In your case, you are not resolving a delegate but a direct instance of an object. This will be executed during the "normal" AutoFac resolve flow. But when your are resolving a delegate you are delaying the resolving to runtime.

So this will work:
```C#
builder.Register<IStrategy>(ctx => new StrategyB(ctx.Resolve<SomeDependency>()));
```
But this won't
```C#
builder.Register<Func<string, IStrategy>>(ctx => key => ctx.ResolveNamed<IStrategy>(key));
```

See the difference?

**Comment by s093294** [comment]
Ahh, i see it. Thanks for clarifying.

**Comment by alexmg** [comment]
@ambvdijk The component context is the current lifetime scope that the component is being resolved from. It can be resolved without side effect or performance penalty as the registration and instance already exists. You would also only being doing it for factory registrations if changed in AutofacConfig in the location mentioned previously.
