### ISSUE TITLE
Thinktecture and Microsoft Account Authentication

### ISSUE THREAD

**Issue by sportingdurutti** [IdentityServer/Thinktecture.IdentityServer3#965]
When testing Thinktecture with External Authentication Providers i'm able to achieve this with both ADFS 3.0 and Google. But with Microsoft Account i'm getting some "There was an unexpected error" and returned to {MyURL}/idsrv/callback. 
I can see that the user is created in my Database (as per config i'm using  idSvrFactory.ConfigureCustomUserService("MyIdentityDb") which is pointing to a Database) when using all external providers
What is starnge is that if i refresh  the page or i i login a second time (with the user already in the database), the error dissapears and i can see the logged in user 
Do you have any idea about what is causing the error? Also i'me getting some ID String as the loggedin User, how can i built my claims from the claims received from each provider?

**Comment by leastprivilege** [comment]
as always - turn on logging first.

**Comment by leastprivilege** [comment]
then debug your custom user service.

**Comment by sportingdurutti** [comment]
Ok, i will do taht, but what is the reason that the same code works with ADFS and Google?

**Comment by sportingdurutti** [comment]
Ok, i will do taht, but what is the reason that the same code works with ADFS and Google?

**Comment by sportingdurutti** [comment]
Ok, i will do that, but what is the reason that the same code works with ADFS and Google?

**Comment by leastprivilege** [comment]
Because every identity provider is different?

**Comment by sportingdurutti** [comment]
Yes, i know that , but as the user is created in the database in very case...

**Comment by leastprivilege** [comment]
But that is your code right? So i would debug that.

**Comment by sportingdurutti** [comment]
Yes , it's my code... but why is everything ok after refrshing the page?

**Comment by leastprivilege** [comment]
"Yes , it's my code"

why are you asking me that? start debugging, dude ;)

**Comment by sportingdurutti** [comment]
Sorry if i offended you...i will debug it!

**Comment by leastprivilege** [comment]
You haven't offended me ;) But probably most of your questions would be answered automatically by stepping through the code and looking at the logs.

**Comment by sportingdurutti** [comment]
Yes you are right but the code is the same for both Google and Microsoft Logins (taken from your samples), so i was just wondering if for Microsoft would there be any reason for a diferent behaviour. My code is as simple as 
var macc = new MicrosoftAccountAuthenticationOptions
{
AuthenticationType = "macc",
Caption = "Microsoft Account",
SignInAsAuthenticationType = signInAsType,
ClientId = "my client ID",
ClientSecret = "my client Secret",
};
app.UseMicrosoftAccountAuthentication(macc);

**Comment by sportingdurutti** [comment]
After enabling Log that's what i get
Thinktecture.IdentityServer.Core.Configuration.Hosting.LogProviderExceptionLogger: Unhandled exception
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at BrockAllen.MembershipReboot.UserClaim..ctor(String type, String value)
   at BrockAllen.MembershipReboot.UserClaimCollection..ctor(IEnumerable`1 claims)
   at Thinktecture.IdentityServer.MembershipReboot.MembershipRebootUserService`1.UpdateAccountFromExternalClaimsAsync(Guid accountID, String provider, String providerId, IEnumerable`1 claims)
   at Thinktecture.IdentityServer.MembershipReboot.MembershipRebootUserService`1.<AccountCreatedFromExternalProviderAsync>d__27.MoveNext()
When refreshing the page i get
Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: External identity successfully validated by user service
Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: issuing cookie
Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController: redirecting to: https://ewkku030009668.bdp.pt/idsrv/permissions
and it's ok

**Comment by leastprivilege** [comment]
and after debugging? What's null?

**Comment by sportingdurutti** [comment]
Thnk's for your concern. As i'm using MembershipReboot to manage users in both Identity Server and Identity Manager i'm now debugging MembershipReboot project to see why there is an exception on Microsoft Account authentication

**Comment by leastprivilege** [comment]
I'd rather debug the user service in identity server.

**Comment by sportingdurutti** [comment]
The UserService in identity server.uses MembershipRebootUserService which in turn uses BrockAllen.MembershipReboot, the last one causing the exception caugth after "AuthenticateExternalAsync" in "return await ProcessNewExternalAccountAsync(tenant, externalUser.Provider, externalUser.ProviderId, externalUser.Claims);" I will try to debug now BrockAllen.MembershipReboot

**Comment by sportingdurutti** [comment]
Done it! In  BrockAllen.MembershipReboot,   public UserClaim(string type, string value) the is somehin glike 
if (String.IsNullOrWhiteSpace(value)) throw new ArgumentNullException("value");
I'me getting some empty values for some Claims from Microsoft Account...will try to correct that!

**Comment by sportingdurutti** [comment]
Done it! In BrockAllen.MembershipReboot, public UserClaim(string type, string value) the is somehing glike
if (String.IsNullOrWhiteSpace(value)) throw new ArgumentNullException("value");
I'me getting some empty values for some Claims from Microsoft Account...will try to correct that!

**Comment by deserthero** [comment]
i faced this issue only with microsoft account and it was due to the email claim didn't returned from microsoft although i request it.

Can any one help me if he faced same issue before
