### ISSUE TITLE
Make ExternalIdentity FromClaims() public instead of internal

### ISSUE THREAD

**Issue by promontis** [IdentityServer/Thinktecture.IdentityServer3#967]
Hi guys!

When implementing a custom grant validator, this method is really usefull! The AuthenticateExternalAsync() method eventually needs an ExternalIdentity object and I'm using the method to map from claims to this class. Could you make it public like it was (it has been changed into internal some commits ago). 

Thnx!

**Comment by promontis** [comment]
If you want me to create a PR, I am happy to do so btw

**Comment by brockallen** [comment]
Sorry we missed this for 1.2. We'll get this in for 1.3.

**Comment by brockallen** [comment]
Ok, done. Thanks!
