### ISSUE TITLE
How do I redirect users to a predetermined url after login?

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#969]
I have one link when i have pasted to url that will redirect me to login Page after the login done i need to go back to the same url which was i am trying access. how can i do this..?

**Comment by loctanvo** [comment]
The most common way to do this is to embed the information in the `state` variable when redirecting to the IdServer. This way, on the callback, you have some information on how to redirect the user after you get the callback from IdServer. If you use the [OIDC client middleware](http://leastprivilege.com/2014/06/12/using-discovery-and-katana-middleware-to-write-an-openid-connect-web-client/), it handles these things for you.

**Comment by leastprivilege** [comment]
Either that - or store any state information you want to preserve in a cookie before you do the redirect to the OIDC provider.

**Comment by RajMondaz** [comment]
I got it thanks..
