### ISSUE TITLE
OpenID Connect Hybrid Flow and IdentityServer v3

### ISSUE THREAD

**Issue by alexeyauslender** [IdentityServer/Thinktecture.IdentityServer3#970]
I would like to ask regarding Dominick blog post http://leastprivilege.com/2014/10/10/openid-connect-hybrid-flow-and-identityserver-v3/ OpenID Connect Hybrid Flow and IdentityServer v3.
One point that I didn’t understand ,why should we request access token and authorization code once again ,nevertheless we requested it through OpenIdConnectAuthenticationOptions configuration.I mean it was possible to retrieve it in such way :
claims.Add(new Claim(“access_token”, n.ProtocolMessage.AccessToken));
claims.Add(new Claim(“expires_at”,DateTime.Now.AddSeconds(Double.Parse(n.ProtocolMessage.ExpiresIn)).ToLocalTime().ToString()));
claims.Add(new Claim(“refresh_token”, n.Code));
claims.Add(new Claim(“id_token”, n.ProtocolMessage.IdToken));
Why should we retrieve it separately through the same client id (katanaclient)?

**Comment by loctanvo** [comment]
[Hybrid flow](http://openid.net/specs/openid-connect-core-1_0.html#HybridFlowAuth) is simply one of the flows specified in the OpenId Connect standard. If it doesn't fit you, you don't need to use it. There are several reasons to use the Hybrid flow, and here are a few we have seen:

Firstly, as Dominick points out, the Microsoft OpenId Connect middleware only supports hybrid + form post:

>Lastly, hybrid flow is the only flow supported by the Microsoft OpenID Connect authentication middleware (in combination with a form post response mode), and before we added support for hybrid flow to IdentityServer, interop was a bit complicated (see here).

If you don't want to use the middleware, you don't need to consider this.

We have one client using the hybrid flow, and it's a mobile application. The application is using [refresh tokens](http://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess) for long lived access. In that case, you [can't retrieve refresh tokens using implicit flow](http://openid.net/specs/openid-connect-core-1_0.html#Authentication). In your code example you have the following: `claims.Add(new Claim(“refresh_token”, n.Code));`. I think that's incorrect. The code you receive is not the refresh token, but a authorization code which you in turn can use to request a refresh token.

**Comment by leastprivilege** [comment]
My statement might not be 100% correct - the OIDC MW is optimized for hybrid flow (with Azure AD as backend) - but it can also do implicit by setting the response_type to id_token or id_token token.

**Comment by leastprivilege** [comment]
@loctanvo is right - you need to pass back the code to the token endpoint to get the refresh token.

**Comment by alexeyauslender** [comment]
So the only reason we are requesting idsrv in this sample once again is in order to exchange authorization code with refresh token,otherwise we have got all needed claims (access token ,id token and authorization code)?
Regarding   @loctanvo answer I understood that we are running hybrid flow through middleware and that what I actually meant to do.

**Comment by leastprivilege** [comment]
Requesting a code only - and exhanging that with a refresh/access/id token would work equally well - the OIDC MW does not help you a lot with that though.
