### ISSUE TITLE
InitialConfiguration

### ISSUE THREAD

**Issue by sadeghhp** [IdentityServer/Thinktecture.IdentityServer3#971]
Hi, where is Initial Configuration server setup, like version 2 ?

**Comment by leastprivilege** [comment]
in startup.cs ;)

**Comment by sadeghhp** [comment]
:D tnx!
I mean some wizard like in IdentityServer2 demonstration

**Comment by leastprivilege** [comment]
yes - I understood you - it is still called startup.cs ;)
