### ISSUE TITLE
Localization / I18n

### ISSUE THREAD

**Issue by superstevek** [IdentityServer/Thinktecture.IdentityServer3#973]
I know there is the LocalizationService for tailoring the messages etc that get returned, but how do you go about internationalizing the front end (i.e. the labels etc within the html).  We use TurquoiseOwl for doing I18n translations and I have been (so far) unable to get it to work with identity server 3. It taps into the main application at the ReleaseRequestState stage to perform its translation on the html that is going to the client.  When i use it with identity server 3 it hits the ReleaseRequestState for all .css or .js that are being sent but not for the main page.  

Any help on this would be greatly appreciated or if there is a different way to perform I18n translations in identity server 3 then info on that would be great.

**Comment by brockallen** [comment]
You can customize the views by building a view service. Check the docs and samples.

**Comment by superstevek** [comment]
Hi Brock.  I have tried using both the default view service using local CSS and html and also tried with a custom view service (as per the samples), both ways allow me to change the actual html but i cant get it to plug into the I18n module either way.  If I go to the Asset directly (e.g. https://idserver/assets/_login.html) then it gets picked up by the module and translated okay, but if i go the normal route (e.g. https://idserver/login?signin=fd0bd8be4bd770bf8369183eb0781766) then it remains untranslated as it doesnt get picked up by the module at ReleaseRequestState.

**Comment by johnkors** [comment]
idsrv is isolated to the OWIN pipeline (if you use the .Map function). Does TurquiseOwl support OWIN?

https://github.com/turquoiseowl/i18n/issues/156

**Comment by superstevek** [comment]
Hi John, hmm good question, i dont think it does, this change alludes to being helpful when moving to an Owin runtime but no more .... https://github.com/turquoiseowl/i18n/issues/173

**Comment by superstevek** [comment]
John, i assume from your IdentityServer3.Contrib.Localization project that you use idserv in a localized/internationalized way, can i ask what method/package you use for translation of the views?

**Comment by johnkors** [comment]
The ```IdentityServer3.Contrib.Localization``` package only translates [known idsrv-events, messages and scopes](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Resources/T4resx.cs) , so whatever extra resource texts you would need for your views you'd have to handle yourself. 

In our project, we're currently supporting just one of the languages in that package, so haven't looked into doing I18n for our own stuff outside idsrv, but we would probably go down the same path as how idsrv does it.

**Comment by superstevek** [comment]
ok thanks for your help

**Comment by brockallen** [comment]
All set then?

**Comment by superstevek** [comment]
Yes,thanks very much
