### ISSUE TITLE
ResourceActionAuthorize vs ResourceAuthorize Attribute

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/Thinktecture.IdentityServer3#974]
Hi

In the pluralsight webapi2 security lecture Dominick goes with this attribute:

[ResourceActionAuthorize("read", "data")]
public class AuthorizationManager : ClaimsAuthorizationManager

with the post http://leastprivilege.com/2014/06/24/resourceaction-based-authorization-for-owin-and-mvc-and-web-api/ this attribute is used:

[ResourceAuthorize(ChinookResources.AlbumActions.View, ChinookResources.Album)]
app.UseResourceAuthorization(new ChinookAuthorization());

Is ResourceAuthorize the latest "greatest" using Identity Server3?

Thank you very much 
David

**Comment by davidmrichter** [comment]
in sourcecode of IdentityModel I found:

namespace Thinktecture.IdentityModel.WebApi
{
    [Obsolete("We recommend using the version based on OWIN middleware instead")]
    public class ResourceActionAuthorizeAttribute : AuthorizeAttribute

==> closed - ResourceAuthorize the latest "greatest"

**Comment by tofutim** [comment]
Where does one locate this OWIN middleware?

**Comment by johnkors** [comment]
I believe a rewrite is in the making, but it's available thru the following NuGets.

http://www.nuget.org/packages/Thinktecture.IdentityModel.Owin.ResourceAuthorization.Mvc/
http://www.nuget.org/packages/Thinktecture.IdentityModel.Owin.ResourceAuthorization.WebApi/

Source:
https://github.com/IdentityModel/Thinktecture.IdentityModel/tree/master/source
