### ISSUE TITLE
Extra claims provided to CustomGrantValidationResult constructor aren't included with resulting JWT

### ISSUE THREAD

**Issue by nathan-alden** [IdentityServer/Thinktecture.IdentityServer3#975]
I've plugged in an implementation of `ICustomGrantValidator` that validates a Facebook access token, then performs a local database lookup to find a matching user. I am passing some of the data returned by my call to Facebook's `/me` endpoint as claims in the `CustomGrantValidationResult` constructor:

```csharp
var customGrantValidationResult = new CustomGrantValidationResult(
    responseJson["name"].Value<string>(),
    "facebook",
    new[]
    {
        new Claim(Thinktecture.IdentityServer.Core.Constants.ClaimTypes.Name, responseJson["name"].Value<string>()),
        new Claim(Thinktecture.IdentityServer.Core.Constants.ClaimTypes.Email, responseJson["email"].Value<string>())
    });
```

The `sub` claim is correct--it matches my Facebook name--but the additional claims don't make their way into the resulting JWT. Am I missing a configuration somewhere or is this a bug?

JWT claims:

```json
{
    "exp": 1424798197, 
    "sub": "<redacted>", 
    "iss": "<redacted>", 
    "idp": "idsrv", 
    "client_id": "facebook", 
    "auth_time": 1424794597, 
    "scope": "read", 
    "amr": "facebook", 
    "nbf": 1424794597, 
    "aud": "<redacted>"
}
```

**Comment by nathan-alden** [comment]
A related question: My `FacebookCustomGrantValidator` is doing the mapping between a Facebook user and a user in my local database. Assuming this mapping succeeds, is `FacebookCustomGrantValidator` the proper place to populate the principal with the mapped claims? Currently, I have it populating with Facebook's claims just for testing purposes, but the goal is to have JWTs represent user information stored in my local database. Is there some place further in the pipeline where performing this work is more appropriate?

**Comment by johnkors** [comment]
Yeah, IUserService is what you're after for mapping ( AuthenticateExternalAsync and GetProfileDataAsync ). There's a custom user service sample in the sample repo.

**Comment by nathan-alden** [comment]
After looking again at the samples, I am not sure that IUserService is what I want. I do not want to use Identity Server's apparently built-in authentication views and such. My web application uses client-side templating. The only thing I need Identity Server for is to convert third-party access tokens into JWTs (currently working perfectly for Facebook and Google+), and support retrieving JWTs for my own identity provider by way of username/password authentication (client credentials flow, I believe). IUserService does not appear to be called by the pipeline when calling `/connect/token`. The problem I stated in my original post still remains: Claims given to the `CustomGrantValidationResult` constructor do not seem to be being applied to the resulting JWT.

**Comment by leastprivilege** [comment]
If you are not authenticating users (or not using the scope claim/profile concept) - then you can take control over claims by implementing IClaimsProvider (or by deriving from DefaultClaimsProvider and adding custom behavior).

**Comment by nathan-alden** [comment]
Thanks for the advice, Dominick. :+1: Is `ICustomGrantValidator` the appropriate mechanism by which to validate third-party access tokens that the client already has? I read your article about [assertion flow](http://leastprivilege.com/2013/12/23/advanced-oauth2-assertion-flow-why/), and it seems like the answer is yes. I just want to make sure I'm not using the pipeline incorrectly.

As far as `CustomGrantValidationResult` goes, I am curious about the purpose of the `IEnumerable<Claim>` parameter if the claims don't end up in the resulting JWT.

**Comment by nathan-alden** [comment]
After digging extensively through the Identity Server source code, I discovered the problem: extra claims are either ignored or never asked for (via `IUserService.GetProfileDataAsync`) if the matching scope's `IncludeAllClaimsForUser` flag is `false`. When I set it to `true`, the extra claims were included.
