### ISSUE TITLE
DI System flawed in cooperation with other IoC Containers

### ISSUE THREAD

**Issue by DerAlbertCom** [IdentityServer/Thinktecture.IdentityServer3#976]
I was trying today to use IdentityServer 3 (1.1.1) in an existing application which uses StructureMap as IoC. 

I find no way to tell IdSrv to use them, because of the hardwired Autofac. 

So i tried other ways. the Factory and the Registrations seems a good place to start. But they have a problem, because the don't work with the current scope of the Autofac Dependency Resolver. 

My idea is that i can use the current IOwinContext to store and use a Scoped Version of the StructureMap Container and use the in my Registration for the Services.

From my Understanding the 

https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/4a44a9f03879c85bbba50cc04c55fc4311436c1a/source/Core/Configuration/Hosting/AutofacContainerMiddleware.cs should make a Scoped Container, and add the current IOwinContext to the scope.

The problem is that the Factory seems not to use the scope version of the IoC Container.

So that this
```csharp
            factory.Register<IUserService>(new Registration<IUserService>(dr =>
                {
                    var context = dr.Resolve<IOwinContext>();
                    return null;
                }));
```
and also
```csharp
            factory.UserService = new Registration<IUserService>(dr =>
                {
                    var context = dr.Resolve<IOwinContext>();
                    return null;
                });
```

fails on dr.Resolve<IOwinContext>() because it is not registered. 

But without the current IOwinContext, cannot access the request specific instances of the SM-IoC, and use the right LifeCycles.

Am i missing something here?

**Comment by brockallen** [comment]
Your service can have an `OwinEnvironment` injected into it.

**Comment by DerAlbertCom** [comment]
OwinEnvironmentService .... tested that, seems to work.

But that's not dependency injection, it is service lookup. And that is harder to test and not usual.

Now i have to write
```csharp
     public IdentityServerClientStore(OwinEnvironmentService owin)
        {
            m_repository = owin.GetStructureMapInstance<IRepository<ApiClient>>();
            m_logger = Logger.GetLogger(GetType());
        }
```
instead of
```
        public IdentityServerClientStore(IRepository<ApiClient> repository, ILogger logger)
        {
            m_repository = repository;
            m_logger = logger;
        }
```
Which makes i harder to test, harder to write the services.


I, and probaly other would prefer something like this.
```
var factory = new IdentityServerServiceFactory
{
    UserService = new Registration<IUserService>(dr => dr.GetStructureMapInstance<IdentityServerUserService>()), 
    ClientStore = new Registration<IClientStore>(dr => dr.GetStructureMapInstance<IdentityServerClientStore>()), 
    ScopeStore = new Registration<IScopeStore>(dr => dr.GetStructureMapInstance<IdentityServerScopeStore>())
};
```
The Registration Function is called, and StructureMap resolves the instance, but 
*System.InvalidOperationException: An error occurred when trying to create a controller of type 'TokenEndpointController'. Make sure that the controller has a parameterless public constructor. ---> Autofac.Core.DependencyResolutionException: A delegate registered to create instances of 'System.Object' returned null.*




These are the extension methods, for resolving from the application container.
```
public static T GetStructureMapInstance<T>(this Thinktecture.IdentityServer.Core.Services.IDependencyResolver resolver)
{
    var owin = resolver.Resolve<OwinEnvironmentService>();
    return owin.GetStructureMapInstance<T>(); 
}

public static T GetStructureMapInstance<T>(this OwinEnvironmentService owin)
{
    var context = new OwinContext(owin.Environment);
    var scope = context.Request.Get<IDependencyScope>("ioc.dependencyScope");
    return (T)scope.GetService(typeof(T));
}
```

**Comment by brockallen** [comment]
Sorry, I misunderstood -- I thought you might be looking for access to the OWIN environment. That's how we provide it. 

As for our DI -- I don't feel like rehashing it here. We've had this questions asked (and discussed) many times already. Search the closed issues for these discussions to understand our position.

**Comment by brockallen** [comment]
To follow up, is your delegate in the registration returning anything?

**Comment by DerAlbertCom** [comment]
Turns out, that Scoped Containers in StructureMap behaves a little different, solved: http://blog.der-albert.com/2015/02/26/identityserver-v3-und-eigene-dependency-injection/

**Comment by huysentruitw** [comment]
@DerAlbertCom what do you think about this slightly modified solution using Autofac? Instead of writing my own middleware, I decided to use the Autofac OWIN middleware:

```C#
app.UseAutofacMiddleware(autofacContainer);
```

Then I modified your `GetInstanceFromApplicationDependencyResolver`:

```C#
public static T GetInstanceFromApplicationDependencyResolver<T>(this Thinktecture.IdentityServer.Core.Services.IDependencyResolver resolver)
{
    var owin = resolver.Resolve<OwinEnvironmentService>();
    var context = new OwinContext(owin.Environment);
    var scope = context.Request.Get<ILifetimeScope>("autofac:OwinLifetimeScope");
    return scope.Resolve<T>();
}
```
