### ISSUE TITLE
Permission to copy parts of documentation

### ISSUE THREAD

**Issue by vigsgb** [IdentityServer/Thinktecture.IdentityServer3#977]
I am creating documentation for a project I am wrapping up in which I used the Thinktecture Identity Server.   I would like to know if it is ok to mention in my document that the core of the project is built around the Thinktecture Identity server and if I could also copy parts of the documentation to my document.

My understanding of the Apache license would permit me to do so but I wanted clarification.

Thanks much

**Comment by leastprivilege** [comment]
You are right - the license allows it. Proper source attribution would be welcome of course.
