### ISSUE TITLE
Validate the client before redirecting to login

### ISSUE THREAD

**Issue by jageall** [IdentityServer/Thinktecture.IdentityServer3#978]
The authorize endpoint doesn't validate that a client exists in the store before [redirecting to the login lines 144-147](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/3d03c544d1f38e9fd0afe85f59e4f70c8b8d4b63/source/Core/Endpoints/Connect/AuthorizeEndpointController.cs#L144-L147) screen. 

It only gets to the [client validation on line 160](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/3d03c544d1f38e9fd0afe85f59e4f70c8b8d4b63/source/Core/Endpoints/Connect/AuthorizeEndpointController.cs#L160) if the user is authenticated.  This leads to the user being shown the signin prompt for a process which can never complete.

It would be better if an error was either shown or sent back to the caller instead of redirecting to login

**Comment by leastprivilege** [comment]
We try to avoid any db roundtrips before the use is authenticated. but i can see the dilemma.

**Comment by jageall** [comment]
for valid clients the round trip will be mitigated to some extent by caching. and by better, I meant for the user, the logs are easily good enough to figure out what's going on from my point of view.

**Comment by jageall** [comment]
good grief! now i have reread it my previous comment is awful. What I meant was it is really easy for me to figure out what is going on as a developer because the logs are awesome :). As a user, I am not sure if it something i did or some incompetent developer/admin on the server.

**Comment by leastprivilege** [comment]
So you are saying usability wins over security?

**Comment by jageall** [comment]
now i have re-read your comment I see what you mean. It's been a long week.  
After thinking about this some more, I think that the way it works is probably correct. 

Although the end user experience isn't necessarily great, I think they are most likely to hit it if there is a configuration issue (which is how we found it) or someone/client is misbehaving.

Feel free to close it if no one has anything further to add.

**Comment by leastprivilege** [comment]
in both situations I am not sure what a user would do about it. Either the app is misconfigured or it is an attack. Either way - the use would be stuck.

**Comment by jageall** [comment]
Exactly, so the UX is really only a teeny bit better if you check first, for something that could be abused. I am now completely of the opinion that it is fine the way it is
