### ISSUE TITLE
After logout from Idrsv3 Instead of showing core/logout Page i need show Login Page how i can get this..?

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#979]

**Comment by loctanvo** [comment]
Have a look at the [documentation](http://identityserver.github.io/Documentation/docs/endpoints/endSession.html). Right now, no automatic redirect is done. Read [this](https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/956) if you're interested. Automatic redirect is [soon supported](https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/957), and is currently done on the dev branch. If you need this now, you can always redirect with javascript in the logout view (given that you have your own view for logout).

**Comment by brockallen** [comment]
The login page can't really just be shown without a client application requesting authentication.

**Comment by RajMondaz** [comment]
i am asking in the client application only after logout in the client application i need to redirect to login page or some other page.

**Comment by brockallen** [comment]
So then you'd have the redirect URL be a page in the client app that requires authentication, which would then redirect back to the login page in IdSvr. You'll have to enable the auto redirect feature that we'll be adding in 1.2 (in the next week or so).

**Comment by RajMondaz** [comment]
ok..
