### ISSUE TITLE
In the javascript client from idsrv3  sample

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#982]
After My Login successful in the java script client , i need to get the flag true if the user is valid. where i can get this information in java script client.

**Comment by brockallen** [comment]
What do you mean?

**Comment by RajMondaz** [comment]
In idsrv3 samples we have JavaScript Implicit Client . in this after login is done i need to set the value to the variable (IsAuthenticated=true). oidc.js in which function i can get this ( true or false) information.

**Comment by brockallen** [comment]
Well, you have an id_token and presumably you've validated it (either on your own or via the TokenManager). That means the user is "logged in".
