### ISSUE TITLE
assembly name update

### ISSUE THREAD

**Issue by gilm0079** [IdentityServer/Thinktecture.IdentityServer3#984]
Any chance the IdSvr3 Core project assembly name could be updated?  I noticed if I need to do deeper debugging and I swap out the IdSvr3 Nuget package with the source then the Thinktecture.IdentityServer3.MembershipReboot project causes an assembly reference build error.  It is looking for the assembly "Thinktecture.IdentityServer3" whereas the source version of Core has the assembly name in the project file set to "Thinktecture.IdentityServer.Core".  If I change the assembly name in the Core project file to match what the membership reboot plugin is looking for then it builds.

Also, not sure if this is a problem.  It doesn't seem to be affecting anything that I've noticed.  Just figured I would let you know.  Since v3 came out of beta, I noticed that the namespace changed from ...IdentityServer.v3 to ...IdentityServer3.  I've also seen references to just IdentityServer (without the 3).  Not sure if that matters.

Anywho, having fun working with the IdSvr3 project. I'm sure you guys are experts, but it's definitely been a challege for someone like me who is new to the OAuth, Token auth in app development.  Thanks!

**Comment by brockallen** [comment]
If you just mean in the .csproj,. then done on dev.

**Comment by leastprivilege** [comment]
That broke ilmerge

**Comment by brockallen** [comment]
Ok, I think my powershell kung fu is strong... updated on dev
