### ISSUE TITLE
Serving subdomains with same CodeFlowClient 

### ISSUE THREAD

**Issue by cdmm** [IdentityServer/Thinktecture.IdentityServer3#986]
Hello 
Is there a possibility to serve subdomains with the same code flow client. The code of those subdomains is same but the IdSrv cannot recognize the client based on the url.

www.domain.com
sub1.domain.com
sub2.domain.com

Thanks 
cdmm

**Comment by leastprivilege** [comment]
A client can have more than one redirect URI. If they are logically different clients - create rather multiple clients.

**Comment by cdmm** [comment]
Thank you! It worked fine!
