### ISSUE TITLE
Sign out all users

### ISSUE THREAD

**Issue by c0dem0nkee** [IdentityServer/Thinktecture.IdentityServer3#987]
Is it possible to log out groups of users currently signed into IdSrv?  I have a scenario where I need to force all users to sign out and also a scenario where a group of users need to be signed out.  Is this possible?

**Comment by leastprivilege** [comment]
Not natively - you could write out some database flag - and check that in IUserService.IsActiveAsync.

**Comment by c0dem0nkee** [comment]
Ok, I am using a custom user service anyway so I'll implement that.  Cheers
