### ISSUE TITLE
Single sign out

### ISSUE THREAD

**Issue by Thor-Kristian-Valderhaug** [IdentityServer/Thinktecture.IdentityServer3#988]
Hi

I'm currently using IdentityServer3 as a federation server. And have some trouble with implementing single sign out. The Identity providers I'm using communicate over SAML 2 protocol, and require that the initial sign out request be done in the front channel. 

So my question is therefore is there any config i can do on IdentityServer3 to make it use the front channel for the initial sign out request. And is there any extension points where i can hook into to provide the redirect URL that the IdentityServer3 should use when retrieving a sign out from the relying party ?

**Comment by brockallen** [comment]
Hmm... this is usually something that would be done via the middleware. IOW, when you logout of IdSvr, we just trigger a signout to the IdP middleware you used and let it then do what's needed. 

Does the SAML2 middleware support front channel? We might have to do some investigation to see if or how that would work,.

**Comment by leastprivilege** [comment]
@AndersAbel would know

**Comment by Thor-Kristian-Valderhaug** [comment]
@brockallen, The use of front channel in SAML2 is defined in [SAMLCore](http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf), and [SAMLProof](http://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf)

**Comment by brockallen** [comment]
Sure, but does your SAML2 middleware implement that?

**Comment by AndersAbel** [comment]
The Kentor.AuthServices middleware does not (yet) support sign out. It's on the todo list https://github.com/KentorIT/authservices/issues/29.

**Comment by Thor-Kristian-Valderhaug** [comment]
@brockallen, I'm implemnting the SAML2 middleware my self. So I can extend it if necessary. The question is if it is possible to get the IdSvr to redirect the user client to the logout URL of the IdP used ?

For the only place I have found that I can extend the log out process is the SignOutAsync method of IUserService. And i don't see how i would be able to redirect from this extension point

**Comment by leastprivilege** [comment]
The Katana authentication middleware has a hook for signing out - you need to implement that to play nice with the rest of the pipeline.
