### ISSUE TITLE
MVC Client As Application - error?

### ISSUE THREAD

**Issue by pircjernej** [IdentityServer/Thinktecture.IdentityServer3#990]
I created Identity server and mvc client and work fine,
but If I put my MVC Application on address:

http://www.somedomain.com/myMvcApp

and change RedirectUri in MCV to:
http://www.somedomain.com/myMvcApp

and change RedirectUris in Server Clients.cs also to:
http://www.somedomain.com/myMvcApp

the redirect don't work OK the base page is displayed.
Is this error or by design?

I wan't to have diferent client applications on diferend sub folders.

**Comment by leastprivilege** [comment]
Check the logs.
