### ISSUE TITLE
In JavaScript Implicit Client Which is SignInCallback function.?

### ISSUE THREAD

**Issue by RajMondaz** [IdentityServer/Thinktecture.IdentityServer3#991]
I need to know which is the Redirect function in JavaScript Implicit Client. after login is done we will be redirect to some location i need to know that function name. (same in the mvc client we are having the SignInCallback  function)

**Comment by adestis-ds** [comment]
Just looked thru the code and assuming you mean the callback after redirect:

In the JavaScriptImplicitClient-Simple:

if (window.location.hash) {
            token = processTokenCallback();
}
--> So the processTokenCallback() is the callback function.

In 

Line 154:
if (window.location.hash) {
            handleCallback();
}
--> So the handleCallback() is the callback function but the magic is hidden in mgr.processTokenCallbackAsync() in oidc.js (Line 1081)

Regards

Dirk
