### ISSUE TITLE
Custom View Service Logged Out behavior

### ISSUE THREAD

**Issue by jlegan** [IdentityServer/Thinktecture.IdentityServer3#994]
Hit an issue today that is stumping me a bit.

I implemented a custom view service and up until this point I have been using the same code from the repository for each of the pages. I noticed an odd iframe rendering issue on loggedOut.html when I first switched from the embedded to custom view service but it wasn't until today that I dug into it. 

In my MVC client I am setting the PostLogoutRedirectUri in UseOpenIdConnectAuthentication as well as setting it in the ProtocolMessage for a LogoutRequest when a RedirectToIdentityProvider event occurs. 

However when I get to the CustomViewServer, my LoggedOutViewModel looks like:

````
((Thinktecture.IdentityServer.Core.ViewModels.CommonViewModel)(model)).CurrentUser	null
((Thinktecture.IdentityServer.Core.ViewModels.CommonViewModel)(model)).LogoutUrl	null
((Thinktecture.IdentityServer.Core.ViewModels.CommonViewModel)(model)).SiteName	"Lockdown (Local Debug)"
((Thinktecture.IdentityServer.Core.ViewModels.CommonViewModel)(model)).SiteUrl	"https://127.0.0.1:21465/core/"
model.ClientName	null
model.IFrameUrls	{System.Linq.Enumerable.WhereSelectListIterator<string,string>} [0] = "https://127.0.0.1:21465/core/connect/endsessioncallback"
model.RedirectUrl	null
````

When the page renders, I am left with a large empty iframe in the middle with a content of:
`<iframe class="signout" ng-repeat="url in model.iFrameUrls" ng-src="{{url}}"></iframe>`

Also, possibly unrelated is the fact that I seem to have stopped receiving the logout problem (i.e. Are you sure you want to logout?". That may have been a setting I changed but I looked through the docs and could not find it.

Any thoughts on what could be causing this behavior?

Thanks,

Jim

**Comment by brockallen** [comment]
Trace the HTTP requests/redirects so we have some more info on what page we're really on. It feels like some JS is not running on your page.

**Comment by jlegan** [comment]
Brock,

I will track traces later today but on a whim I commented out the registration of my custom view service, falling back to the embedded view service. While I do not get the iframe (I agree, it seems to be javascript related), I still do not see the redirect link nor did I receive the page prompting for logout.

Thanks,

Jim

**Comment by brockallen** [comment]
When the client redirects to the end session endpoint in IdSvr, that then redirects you to the logout page (so those are 2 diff pages in IdSvr). I guess it's clear you're on the latter since that's the one that has all the NG code.

**Comment by jlegan** [comment]
Brock,

I tracked down the iframe display issue and the issue exists in the same app as well. The reference to the page-loggedOut is missing from the loggedOut.html page dom which is where the display:none exists.

The redirect link still is not working on my end, even if I comment out my custom view service and use the embedded one so I will look into that further. 

However I am curious if you know off of the top of your head why I would be skipping the logout confirmation page altogether. I ensured that I following the documentation (MVC sample from the docs) to a tee. 

I have a client with a PostLogoutRedirectUris, in my MVC app I have the same URI's set and my log out controller action looks like this:

````
Request.GetOwinContext().Authentication.SignOut();
            return Redirect("/");
````

If I set break points in my custom view service, I break into both:

````
public virtual async Task<System.IO.Stream> Login(LoginViewModel model, SignInMessage message)
````
and 
````
public virtual Task<System.IO.Stream> LoggedOut(LoggedOutViewModel model)
````

but never 
````
public virtual Task<System.IO.Stream> Logout(LogoutViewModel model)
````

**Comment by jlegan** [comment]
Another mystery solved.

The lack of a logout prompt is directly related to the cookie conversation we had the other day. Idv3 has a very short lived cookie on purpose and the lack of that cookie is what is causing the skipping of the confirmation page to occur in conjunction with the id_token hint per: https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/906

Still can't get the redirect links to appear but I will keep you posted.

**Comment by jlegan** [comment]
Brock,

I am still working through this. I did upgrade to 1.2.1 while I was at it as I wanted to put my hands on the Cors Policy work. I enabled auto-redirect with a 1 sec delay to confirm that it would not fix the issue and it did not. I will get back at it on Monday morning. 

Thanks,

Jim
