### ISSUE TITLE
Custom User Service to authenticate against Active Directory

### ISSUE THREAD

**Issue by rajarameshvarma** [IdentityServer/Thinktecture.IdentityServer3#995]
I am trying to create a custom user service for the Identity server. My user store will be multiple Active Directories. I have implemented Local Login.
    public Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password, SignInMessage message)
        {
            AuthenticationService service = new AuthenticationService();
            ResponseStatus status = service.Authenticate(username, password);

            CustomUser user;

            if(status == ResponseStatus.Success)
            {
                user =
                new CustomUser()
                {
                    Subject = username,
                    Username = username,
                    Claims = new List<Claim>
                    {
                        new Claim(Constants.ClaimTypes.PreferredUserName, username)
                    }
                };

                Users.Add(user);

                return Task.FromResult<AuthenticateResult>(new AuthenticateResult(user.Subject, user.Username));
            }
            else
            {
                return Task.FromResult<AuthenticateResult>(null);
            }
        }

"Users" is a static List of CustomUser class. If I understand correctly this "Users" list will be in the memory and is used in other methods like "IsActiveAsync".
    public Task<bool> IsActiveAsync(ClaimsPrincipal subject)
        {
            var user = Users.SingleOrDefault(x => x.Subject == subject.GetSubjectId());
            return Task.FromResult(user != null);
        }

Does this really help when I am using AD as this is not going to check if the user is active in AD. Do we really need to keep users in the memory? Or Is my implementation is off the track for this scenario?

Thanks for the help.

**Comment by brockallen** [comment]
I think you're confused -- the in memory Users is only used as an example when using the InMemoryUserService. For a real implementation of the user service, you'd not keep that list and you'd instead check back with the store (DB, AD, whatever) to check things like IsActive.

**Comment by tjrobinson** [comment]
@rajarameshvarma I've created this as a starting point, which seems to at least partially work:

https://gist.github.com/tjrobinson/0ad6c790e90d7a385eb1

It's based on the LocalRegistrationUserService from the CustomUserService sample but with the List<CustomUser> removed as @brockallen mentioned.

**Comment by brockallen** [comment]
Can we close this?

**Comment by rajarameshvarma** [comment]
Thanks Allen for correcting me. Thanks @tjrobinson this really helpful.

**Comment by pashute** [comment]
@tjrobinson didn't you need to create a ClaimsIdentityFactory with the AD so it should work? 
Where did you set the ConnectionString?
