### ISSUE TITLE
OpenID issue on Chrome

### ISSUE THREAD

**Issue by jsucupira** [IdentityServer/Thinktecture.IdentityServer3#996]
I am using IdentityServer3 on a MVC application.  Whenever I try to login I get the following error when using Google Chrome.  It works just fine in IE.

"The webpage at https://localhost:44300/identity/login?signin=9d5580f27067f26e5e81724c91b7c21b might be temporarily down or it may have moved permanently to a new web address.
Error code: ERR_SPDY_PROTOCOL_ERROR".

The application that I am trying to run is from the following example. "https://github.com/IdentityServer/Thinktecture.IdentityServer3.Samples/tree/master/source/MVC%20Authentication"

Any help will be appreciated it.

Thank you.

**Comment by leastprivilege** [comment]
Never seen that before - but I bet some weird Chrome problem on your machine (I use Chrome all the time) - I'd investigate this: ERR_SPDY_PROTOCOL_ERROR

**Comment by leastprivilege** [comment]
Any news on that?

**Comment by jsucupira** [comment]
I was able to run the same project on a different computer with no issue.  I tried re-installing chrome on the computer I am having issues with no success.  The computer that I am having issues with is running Windows 10 previews.

**Comment by leastprivilege** [comment]
OK. No idea. Never tested on Windows 10 - closing.
