### ISSUE TITLE
How to divide IdenityServer3 into 2 instances(one for Authentication and another for Authorization)

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/Thinktecture.IdentityServer3#997]
Sorry for bringing this up again. 
I was busy to set up Scopes, Roles, Resources and so on, to get a better understanding on what is actually to divide.

Meanwhile Brook Allen closed the 944 Issue https://github.com/IdentityServer/Thinktecture.IdentityServer3/issues/944 
and I could not find how to reopen the issue. So I created a new one.

After having that implemented/extented alltogether in SelfHost (Minimal) Sample I have second thoughts on dividing IdenityServer3 into 2 instances(one for Authentication and another for Authorization).

If one divides as described in my first post:
-what is then the remaining functionality in the second part(-SelfHost (Minimal) (from IdentityServer3 Samples) as interim solution for a later full fleged company owned Authorization server)

Based on my current knowledge I would postulate: nothing is remaining 
I think even that my question in the first place doesnot make sense at all!

But Allen did not think so and answered my question.
Can someone hint me towards the point I am quite certainly missing?`

Thank you very much

**Comment by brockallen** [comment]
Normally it would not make sense to break them apart -- perhaps I should have added that comment to the other thread.

I guess I don't follow what you're trying to ask. Do you mean beyond the self host sample, how do you really host IdSvr in a robust way (i.e. scalable, available, etc)?

**Comment by leastprivilege** [comment]
I don't see any practical point in breaking up the current idsrv into two parts. It's a token service - credential in/token out. that easy.

**Comment by davidmrichter** [comment]
Now we have an external professional hoster which hosts: 
-http://www.adnovum.ch/en/solutions/products/nevis/nevisproxy.html
-http://www.adnovum.ch/en/solutions/products/nevis/nevisauth.html
-http://www.adnovum.ch/en/solutions/products/nevis/nevisidm.html
As I now understand its using SAML 1.1/ 2.0 identity assertions. 
All our products should use this for authentification. meaning our customers only have one username/pw combination. But we have no direct config access on this Server, meaning we cannot add new roles and claims without filing in requests eventually answered after months.

Now we intent to build up several new Rest Apis in our company. Also we understand that those Adnovum Nevis components are not Oauth compatible. So Our company needs its own scalable robust Authorisation Server in addition to the NEVIS component. To my knowledge this is a Federation of two Identity Servers, right? Saml Tokens from NEVIS need to be trusted by the OAuth IDentityServer(second in Idenitification chain). The later will then just add more claims to the users.
Thats why I came up with the WsFederation instance surrogate as Nevis(producing SAML Tokens) and then a Pure Identity SErver as OAUTH Authorisation Server (wrapping the Saml Tokens) in federation. 

Does that reasoning make sense? Somehow I feel that I am missing crucial points.
If it makes sense: is there any guidance (code, samples, configs) on how to configure the thinktecture identity Server as to the scenario above?

Thank you very much

**Comment by leastprivilege** [comment]
Sure - you can add your WS-Federation provider as an external identity provider. Check the docs 
https://identityserver.github.io/Documentation/docs/configuration/identityProviders.html

**Comment by leastprivilege** [comment]
Closing this. Confusing name.
